FormSection.create_or_update!(
  {
    unique_id: "child_preferences_section",
    name_i18n: {
      en: "Nested Child's Preferences",
      km: "ចំណង់ចំណូល​ចិត្ត​របស់​កុមារ Nested"
    },
    description_i18n: {
      en: "Child's Preferences Subform",
      km: "ទម្រង់​រង​ចំណង់ចំណូលចិត្ត​របស់​កុមារ"
    },
    parent_form: "case",
    visible: false,
    order: 10,
    order_form_group: 130,
    order_subform: 1,
    form_group_keyed: false,
    editable: true,
    core_form: false,
    is_nested: true,
    is_first_tab: false,
    initial_subforms: 1,
    subform_prevent_item_removal: false,
    subform_append_only: false,
    subform_header_links: [],
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    collapsed_field_names: [
      "wishes_preference_relocated",
      "wishes_name"
    ],
    fields_attributes: [
      {
        name: "wishes_name",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Person(s) child wishes to locate",
          km: "មនុស្ស​ដែល​កុមារ​ចង់​ផ្លាស់ទៅ​នៅ​ជា​មួយ"
        },
        order: 0,
        hidden_text_field: false,
        collapsed_field_for_subform_section_id: 1630,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        collapsed_field_for_subform_unique_id: "child_preferences_section"
      },
      {
        name: "wishes_preference_relocated",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Preference of the child to be relocated with this person",
          km: "ចំណូល​ចិត្ត​របស់​កុមារ​​ត្រូវ​ផ្លាស់ទី​នៅ​ជា​មួយ​មនុស្ស​ម្នាក់នេះ"
        },
        option_strings_text_i18n: [
          {
            id: "first_choice",
            display_text: {
              en: "First choice",
              km: "ជម្រើស​ទីមួយ"
            }
          },
          {
            id: "second_choice",
            display_text: {
              en: "Second choice",
              km: "ជម្រើស​ទីពីរ"
            }
          },
          {
            id: "third_choice",
            display_text: {
              en: "Third choice",
              km: "ជម្រើស​ទីបី"
            }
          }
        ],
        order: 1,
        hidden_text_field: false,
        collapsed_field_for_subform_section_id: 1630,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        collapsed_field_for_subform_unique_id: "child_preferences_section"
      },
      {
        name: "wishes_relationship",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "What is this person's relationship to the child?",
          km: "តើ​មនុស្ស​ម្នាក់នេះ​មាន​ទំនាក់ទំនង​អ្វី​ជា​មួយ​កុមារ?"
        },
        option_strings_source: "lookup lookup-family-relationship",
        order: 2,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_address",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Last Known Address",
          km: "អាសយដ្ឋាន​ដែល​បាន​ស្គាល់​ចុងក្រោយ"
        },
        order: 3,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_landmark",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Landmark",
          km: "ទីតាំងសម្គាល់"
        },
        order: 4,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_location",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Last Known Location",
          km: "ទីតាំង​ដែល​បាន​ស្គាល់​ចុងក្រោយ"
        },
        option_strings_source: "Location",
        order: 5,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_telephone",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Telephone",
          km: "លេខទូរសព្ទ"
        },
        order: 6,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        }
    ],
    module_ids: [
      "primeromodule-cp"
    ]
  }
)

FormSection.create_or_update!(
  {
    unique_id: "child_wishes",
    name_i18n: {
      en: "Child's Wishes",
      km: "បំណង​របស់​កុមារ"
    },
    description_i18n: {
      en: "Child's Wishes",
      km: "បំណង​របស់​កុមារ"
    },
    parent_form: "case",
    visible: false,
    order: 10,
    order_form_group: 90,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "care_arrangements_15731",
    editable: true,
    core_form: false,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    subform_append_only: false,
    subform_header_links: [],
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    fields_attributes: [
      {
        name: "assessment_requested_by",
        type: "text_field",
        multi_select: false,
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Assessment requested by",
          km: "បាន​ស្នើសុំ​ការ​ប៉ាន់ប្រមាណ​ដោយ"
        },
        order: 0,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "assessment_requested_on",
        type: "date_field",
        multi_select: false,
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: false,
        disabled: false,
        display_name_i18n: {
          en: "Assessment requested on",
          km: "បាន​ស្នើសុំ​ការ​ប៉ាន់​ប្រមាណ​នៅ"
        },
        help_text_i18n: {
          en: "This field is used for the Workflow status.",
          km: "កន្លែង​បញ្ចូល​នេះ​ត្រូវ​បាន​ប្រើ​សម្រាប់​ស្ថានភាព​លំហូ​រការងារ។"
        },
        order: 1,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "case_plan_due_date",
        type: "date_field",
        multi_select: false,
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: false,
        disabled: false,
        display_name_i18n: {
          en: "Date Case Plan Due",
          km: "កាលបរិច្ឆេទ​ផុត​​កំណត់​ផែនការករណី"
        },
        order: 2,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_child_family_tracing",
        type: "radio_button",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Does child want to trace family members?",
          km: "តើ​កុមារ​ចង់​ស្វែងរក​សមាជិក​គ្រួសារ​ដែ​រឬទេ?"
        },
        option_strings_source: "lookup lookup-yes-no",
        order: 3,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_reason_no_tracing",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "If the child does NOT want family tracing , explain why",
          km: "ប្រសិន​បើ​កុមារ​មិន​ចង់​​ស្វែងរក​គ្រួសារ សូម​ពន្យល់​អំពី​មូលហេតុ"
        },
        order: 4,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_reunification",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Does the child want family reunification?",
          km: "តើ​កុមារ​ចង់​ឲ្យ​មាន​ការ​បង្រួមបង្រួម​គ្រួសារ​ដែ​រឬទេ?"
        },
        option_strings_text_i18n: [
          {
            id: "yes_as_soon_as_possible",
            display_text: {
              en: "Yes, as soon as possible",
              km: "បាទ/ចាស ឲ្យ​បាន​ឆាប់​តាម​ដែលអាច​ធ្វើ​បាន"
            }
          },
          {
            id: "yes_but_later",
            display_text: {
              en: "Yes, but later",
              km: "បាទ/ចាស ប៉ុន្តែ​នៅ​ពេល​ក្រោយ"
            }
          },
          {
            id: "not_sure",
            display_text: {
              en: "Not sure",
              km: "មិន​ប្រាកដ​"
            }
          },
          {
            id: "no",
            display_text: {
              en: "No",
              km: "ទេ"
            }
          }
        ],
        order: 5,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_reason_no_reunification",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "If 'No', 'Not sure', or 'Yes, but later', explain why",
          km: "ប្រសិនបើ 'ទេ', 'មិនប្រាកដ' ឬ 'បាទ/ចាស​ ប៉ុន្តែ​ពេលក្រោយ' សូម​ពន្យល់​អំពី​មូលហេតុ"
        },
        order: 6,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_contacted",
        type: "radio_button",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Has the child heard from/been in contact with any relatives?",
          km: "តើ​កុមារ​បាន​ទទួល​ដំណឹង/មាន​ទំនាក់ទំនង​ជា​មួយ​សាច់ញាតិដែរ​ឬទេ?"
        },
        option_strings_source: "lookup lookup-yes-no",
        order: 7,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_contacted_details",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Please Give Details",
          km: "សូម​ផ្ដល់​ព័ត៌មាន​លម្អិត"
        },
        order: 8,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "child_preferences_section",
        type: "subform",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Child's Preferences",
          km: "ចំណង់ចំណូល​ចិត្ត​របស់​កុមារ"
        },
        order: 9,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        subform_unique_id: "child_preferences_section"
      },
      {
        name: "wishes_care_arrangement_desired",
        type: "radio_button",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Does the child wish to continue in the current care arrangement?",
          km: "តើ​កុមារ​​ចង់​បន្ត​ស្នាក់​នៅ​ក្នុង​ការរៀបចំ​ថែទាំ​បច្ចុប្បន្ន​ដែរ​ឬទេ?"
        },
        option_strings_source: "lookup lookup-yes-no",
        order: 10,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_reason_no_care_arrangement",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "If the child does NOT want to stay in the current care arrangement, explain why",
          km: "ប្រសិន​បើ​កុមារ​មិន​ចង់​ស្នាក់នៅ​ក្នុងការ​រៀបចំ​ថែទាំ​បច្ចុប្បន្ន សូម​ពន្យល់​អំពី​មូលហេតុ"
        },
        order: 11,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_care_arrangement_type_desired",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Type of care arrangement child wishes to have",
          km: "ប្រភេទ​ការ​រៀបចំ​ថែទាំ​ដែល​កុមារ​ចង់​ឲ្យ​មាន"
        },
        option_strings_text_i18n: [
          {
            id: "independent_living",
            display_text: {
              en: "Independent Living",
              km: "ការ​រស់នៅ​ដោយ​ឯករាជ្យ"
            }
          },
          {
            id: "alternative_interim_care",
            display_text: {
              en: "Alternative interim care",
              km: "ការ​ថែទាំ​បណ្ដោះអាសន្ន​ជំនួស"
            }
          },
          {
            id: "with_husband_wife_partner",
            display_text: {
              en: "With husband/wife/partner",
              km: "ជា​មួយ​ប្ដី/ប្រពន្ធ/ដៃគូ"
            }
          },
          {
            id: "other_family",
            display_text: {
              en: "Other family",
              km: "គ្រួសារ​ផ្សេង"
            }
          },
          {
            id: "dont_know",
            display_text: {
              en: "Don't know",
              km: "មិន​ដឹង"
            }
          },
          {
            id: "other",
            display_text: {
              en: "Other",
              km: "ផ្សេងៗ"
            }
          }
        ],
        order: 12,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_care_arrangement_type_other",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "If type of care arrangement child wishes to have is Other, specify",
          km: "ប្រសិន​បើប្រភេទ​​ការរៀបចំ​ថែទាំ​ដែល​កុមារ​ចង់​បាន​ គឺ​ផ្សេងៗ សូម​បញ្ជាក់"
        },
        order: 13,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_location_plan_live",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Where does the child wish/plan to live?",
          km: "តើ​កុមារ​ចង់/មានគម្រោង​រស់នៅ​ទីណា?"
        },
        option_strings_source: "Location",
        order: 14,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_address_plan_live",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Street where does the child wish/plan to live?",
          km: "អាសយដ្ឋាន​ផ្លូវ​ដែល​កុមារ​ចង់/មាន​កម្រោង​រស់​នៅ?"
        },
        order: 15,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "wishes_landmarks_plan_live",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Landmarks where does the child wish/plan to live?",
          km: "ទីតាំង​ដែល​កុមារ​ចង់/មាន​កម្រោង​រស់​នៅ?"
        },
        order: 16,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        }
    ],
    module_ids: [
      "primeromodule-cp"
    ]
  }
)

