FormSection.create_or_update!(
  {
    name_en: "API form",
    description_en: "List of fields to shared on API",
    name_km: "ទម្រង់ API",
    description_km: "ចំណុចក្នុងទម្រង់ដែលចែករំលែកនៅលើ API",
    unique_id: "cp_api_form",
    parent_form: "case",
    visible: true,
    order: 999,
    order_form_group: 999,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "identification_registration",
    editable: true,
    core_form: false,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "id",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "id",
        help_text_en: "",
        display_name_km: "លេខកូដ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "case_id",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "case_id",
        help_text_en: "",
        display_name_km: "លេខកូដករណី",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "case_id_display",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Case ID",
        display_name_km: "លេខកូដករណី",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "oscar_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "OSCaR Status",
        help_text_en: "(If this case is a Referral from OSCaR.)",
        display_name_km: "ស្ថានភាពក្នុង OSCaR",
        help_text_km: "(ប្រសិនបើករណីនេះ​គឺជាការបញ្ជូនពី OSCaR)",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "oscar_number",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "OSCaR Number",
        display_name_km: "លេខកូដកុមារ (កំណត់ដោយ OSCaR)",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "mosvy_number",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "MoSVY Number",
        display_name_km: "លេខកូដកុមារ (កំណត់ដោយ ក្រសួង ស.អ.យ.)",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "name_first",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "name_first",
        help_text_en: "name_first",
        display_name_km: "នាមខ្លួន",
        help_text_km: "នាមខ្លួន",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "name_last",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: true,
        show_on_minify_form: true,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Surname",
        display_name_km: "នាមត្រកូល",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: true
      },
      {
        name: "sex",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: false,
        disabled: true,
        display_name_en: "Sex",
        display_name_km: "ភេទ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-gender",
        autosum_total: false,
        autosum_group: "",
        required: true,
        matchable: true
      },
      {
        name: "date_of_birth",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: false,
        disabled: true,
        display_name_en: "date_of_birth",
        help_text_en: "date_of_birth",
        display_name_km: "ថ្ងៃខែឆ្នាំកំណើត",
        help_text_km: "ថ្ងៃខែឆ្នាំកំណើត",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "location_current",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: false,
        disabled: true,
        display_name_en: "Current Location",
        display_name_km: "អាសយដ្ឋានបច្ចុប្បន្ន",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "owned_by",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: false,
        disabled: true,
        display_name_en: "Caseworker Code",
        display_name_km: "លេខកូដអ្នកកាន់ករណី",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "User",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "owned_by_agency",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: false,
        disabled: true,
        display_name_en: "Agency",
        display_name_km: "អង្គភាព",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Agency",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "owned_by_phone",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Caseworker Mobile Phone",
        display_name_km: "លេខទូរស័ព្ទអ្នកកាន់ករណី",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "protection_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: false,
        disabled: true,
        display_name_en: "Category of child",
        help_text_en: "",
        display_name_km: "ប្រភេទកុមារ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-protection-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "created_at",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: true,
        show_on_minify_form: true,
        type: "date_field",
        editable: false,
        disabled: true,
        display_name_en: "created_at",
        display_name_km: "បានបង្កើតនៅ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: true,
        date_include_time: true
      },
      {
        name: "protection_status_oscar",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: false,
        display_name_en: "Protection Status from OSCaR",
        help_text_en: "",
        display_name_km: "ស្ថានភាពកិច្ចការពារពី OSCaR",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "transitions_changed_at",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: false,
        disabled: false,
        display_name_en: "Transitions changed at",
        display_name_km: "ការផ្ទេរបានផ្លាស់ប្តូរនៅ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        date_include_time: true
      },
      {
        name: "oscar_short_id",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: true,
        display_name_en: "Child Short ID (OSCaR)",
        help_text_en: "",
        display_name_km: "លេខកូដកុមារ (លេខកូដខ្លីកំណត់ដោយ OSCaR)",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "interview_subject",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Consent Obtained From",
        display_name_km: "​បាន​ទទួលការ​យល់ព្រមពី",
        option_strings_text_en: [
          {
            id: "individual",
            display_text: "Individual"
          },
          {
            id: "caregiver",
            display_text: "Caregiver"
          },
          {
            id: "other",
            display_text: "Other (please specify)"
          }
        ],
        option_strings_text_km: [
          {
            id: "individual",
            display_text: "កុមារ"
          },
          {
            id: "caregiver",
            display_text: "អ្នកថែទាំ"
          },
          {
            id: "other",
            display_text: "ផ្សេងៗ (សូម​បញ្ជាក់)"
          }
        ],
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_source_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        display_name_km: "ប្រសិនបើ​ផ្សេងៗ សូម​បញ្ជាក់",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "referral_notes_oscar",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Referral notes from OSCaR",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "risk_level",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Risk Level",
        help_text_en: "This field is on the Concerns for the Child form and the Risk Assessment form.",
        guiding_questions_en: "High Risk – A child is likely to be seriously harmed or injured, subjected to immediate or ongoing sexual abuse or be permanently disabled, trafficked or die if left in his/her present circumstances without protective intervention.\nAn immediate decision should be made as to whether immediate action is required to protect the child. If not contact and an assessment of the child’s safety/needs must be completed within 24 hours.\n\nMedium Risk- A child is likely to suffer some degree of harm if he or she remains in the home without an effective protective intervention plan. Intervention is warranted, however there is no evidence that the child is at risk of imminent serious injury or death. The difference between medium and high risk is if high the child is likely to be at risk of harm if urgent action is not taken.\nContact with the child and an assessment of the child’s safety and his/her needs and a decision about any protective action required must be completed within 72 hours\n\nLow Risk - The home is considered safe for children, however there are concerns about the potential for a child to be at risk if services are not provided to prevent the need for protective intervention. Most low risk cases require work to prevent further risks from emerging.\nContact with the child and an assessment of the child’s safety and his/her needs must be completed within 5 days.\n\nNo Action - The home is considered safe for the child and there are no indications of potential risks to the child.\nOffer any advice required and consider referring onto other agencies or sources of support for the family if required and end involvement.",
        display_name_km: "កម្រិត​ហានិភ័យ",
        help_text_km: "ផ្នែកនេះមាននៅក្នុងទម្រង់បញ្ហាដែលជាកង្វល់ និងទម្រង់បា៉ន់ប្រមាណហានិភ័យកុមារ។",
        guiding_questions_km: "ហានិភ័យខ្ពស់ - កុមារទំនងជាត្រូវបានធ្វើបាប ឬរងរបួសយ៉ាងធ្ងន់ធ្ងរ ទទួលរងការរំលោភបំពានផ្លូវភេទពេលថ្មីៗនេះ ឬកំពុងបន្តទទួលរងការលោភបំពានផ្លូវភេទ ឬត្រូវពិការជាអចិន្ត្រៃយ៍ ត្រូវគេជួញដូរ ឬស្លាប់ ប្រសិនបើត្រូវបានគេទុកចោលក្នុងកាលៈទេសៈបច្ចុប្បន្នរបស់គាត់ដោយគ្មានអន្តរាគមន៍ការពារ។ គួរសម្រេចចិត្តជាបន្ទាន់ថា តើត្រូវចាត់វិធានការបន្ទាន់ដើម្បីការពារកុមារដែរឬទេ។ ប្រសិនបើមិនធ្វើដូច្នេះទេ ត្រូវតែធ្វើការទាក់ទង និងធ្វើការបា៉ន់ប្រមាណអំពីសុវត្ថិភាព/តម្រូវការរបស់កុមារក្នុងអំឡុងពេល ២៤ ម៉ោង។\n\nហានិភ័យមធ្យម - កុមារទំនងជាទទួលរងគ្រោះថ្នាក់ខ្លះ ប្រសិនបើគាត់នៅតែស្ថិតនៅក្នុងផ្ទះដោយមិនមានផែនការអន្តរាគមន៍ការពារដែលមានប្រសិទ្ធភាព។ ការធ្វើអន្តរាគមន៍គឺជាការចាំបាច់ ប៉ុន្តែ មិនមានភ័ស្តុតាងណាមួយដែលបង្ហាញថា កុមារមានហានិភ័យនៃការរងរបួសធ្ងន់ធ្ងរ ឬស្លាប់នោះទេ។ ភាពខុសគ្នារវាងហានិភ័យមធ្យមនិងខ្ពស់ គឺ ប្រសិនបើខ្ពស់ កុមារទំនងជាមានគ្រោះថ្នាក់ ប្រសិនបើវិធានការបន្ទាន់មិនត្រូវបានធ្វើឡើងទេនោះ។\nទាក់ទងជាមួយកុមារ ហើយធ្វើការបា៉ន់ប្រមាណទៅលើសុវត្ថិភាពកុមារនិងតម្រូវការរបស់គាត់ និងការសម្រេចចិត្តអំពីសកម្មភាពការពារណាមួយដែលត្រូវតែធ្វើឧ្យចប់ក្នុងរយៈពេល ៧២ ម៉ោង\n\nហានិភ័យទាប - ស្ថានភាពនៅផ្ទះត្រូវបានចាត់ទុកថា មានសុវត្ថិភាពសម្រាប់កុមារ ក៏ប៉ុន្តែ មានការព្រួយបារម្ភថា កុមារអាចមានហានិភ័យ ប្រសិនបើសេវាមិនត្រូវបានគេផ្តល់ដើម្បីទប់ស្កាត់។ ករណីហានិភ័យទាបភាគច្រើន ត្រូវការឱ្យមានការទប់ស្កាត់ដើម្បីរារាំងហានិភ័យមិនឱ្យកើត​ឡើង។ទាក់ទងជាមួយកុមារ ហើយធ្វើការបា៉ន់ប្រមាណទៅលើសុវត្ថិភាពកុមារនិងតម្រូវការរបស់គាត់ឱ្យចប់ក្នុងរយៈពេល ៥ ថ្ងៃ។\n\nគ្មានសកម្មភាព - ស្ថានភាពនៅផ្ទះត្រូវបានចាត់ទុកថាជាកន្លែងមានសុវត្ថិភាពសម្រាប់កុមារ ហើយមិនមានសញ្ញាណាបង្ហាញពីហានិភ័យដែលអាចកើតមានចំពោះកុមារទេ។  ផ្តល់ដំបូន្មានដែលត្រូវការ និងពិចារណាបញ្ជូនទៅទីភ្នាក់ងារផ្សេងទៀត ឬប្រភពផ្សេងទៀតនៃការគាំទ្រសម្រាប់គ្រួសារប្រសិនបើចាំបាច់ និងបញ្ចប់ករណី។",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-risk-level",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "age",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Age",
        display_name_km: "អាយុ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: true,
        matchable: true
      }
    ]
  }
)

