FormSection.create_or_update!(
  {
    name_en: "Child's Wellbeing Scoring",
    description_en: "",
    name_km: "ពិន្ទុសរុបនៃការបា៉ន់ប្រមាណផ្នែកសុខុមាលភាពកុមារ",
    unique_id: "cp_child_s_wellbeing_scoring",
    parent_form: "case",
    visible: true,
    order: 70,
    order_form_group: 2,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "child_s_wellbeing_assessment_74328",
    editable: true,
    core_form: false,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "assessment_consent",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Has the family been provided a copy of the information sheet explaining the purpose of this assessment, how their rights to confidentiality will be respected, how this information will be stored and how they can request access to their case file?",
        help_text_en: "",
        guiding_questions_en: "Before the interview begins, I would like to read the following points for your confirmation: 1) Rights of the child and family / caregiver: Your (your child) participation in this outreach is voluntary. This form is used as a request for approval for this interview. If you (your child) agree, I will start asking questions. You have the right not to answer or stop the question at any time. You (your child) may also refuse the proposed service. 2) Confidentiality: All information you provide will be kept confidential. All data will be stored and only those who will provide services to children and parents / caregivers who can find out the information needed. This is aimed at ensuring the children and parents / caregivers get the best possible service. However, if in urgent situations, there is information to be provided to the authorities as in court, cases that endanger the child or the parent or caregiver, then the child and the parent or caregiver will be informed accordingly. 3) Risk and Benefit: During this interview, I might ask things that can make you (your child) sad, upset, angry or uncomfortable. However, this question is necessary to know your (your child) condition so the right type of protection and social welfare services could be determined. The purpose of this outreach is to give children and parents / caregivers access to the services as needed.",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_requested_on",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Assessment initiated on",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "case_plan_due_date",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date Case Plan Due",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "wellbeing_scoring_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Child’s Wellbeing Assessment Scoring",
        help_text_en: "",
        display_name_km: "ពិន្ទុសរុបនៃការបា៉ន់ប្រមាណសុខុមាលភាពកុមារ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "health_scoring",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: true,
        display_name_en: "Health score",
        help_text_en: "Automatically updated",
        display_name_km: "ពិន្ទុសុខភាព",
        help_text_km: "ធ្វើបច្ចុប្បន្នភាពដោយស្វ័យប្រវត្តិ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-scoring-f82eeaa",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_scoring",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: true,
        display_name_en: "Education score",
        help_text_en: "Automatically updated",
        display_name_km: "ពិន្ទុអប់រំ",
        help_text_km: "ធ្វើបច្ចុប្បន្នភាពដោយស្វ័យប្រវត្តិ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-scoring-f82eeaa",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "emotional_scoring",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: true,
        display_name_en: "Emotional and Social score",
        help_text_en: "Automatically updated",
        display_name_km: "ពិន្ទុសុខភាពផ្លូវចិត្ត និងទំនាក់ទំនងសង្គម",
        help_text_km: "ធ្វើបច្ចុប្បន្នភាពដោយស្វ័យប្រវត្តិ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-scoring-f82eeaa",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "home_scoring",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: true,
        display_name_en: "Safety and Environment score",
        help_text_en: "Automatically updated",
        display_name_km: "ពិន្ទុសុវត្ថិភាព និងបរិស្ថាន",
        help_text_km: "ធ្វើបច្ចុប្បន្នភាពដោយស្វ័យប្រវត្តិ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-scoring-f82eeaa",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "food_scoring",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: true,
        display_name_en: "Nutrition score",
        help_text_en: "Automatically updated",
        display_name_km: "ពិន្ទុអាហារូបត្ថម្ភ",
        help_text_km: "ធ្វើបច្ចុប្បន្នភាពដោយស្វ័យប្រវត្តិ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-scoring-f82eeaa",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "overall_child_wellbeing_assessment_score",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Overall Child Wellbeing Assessment score",
        help_text_en: "To calculate sum all the domain scores and divide by 5. Decimal numbers must be rounded, if the decimals are less than 0.5 then round it down, if the decimals are 0.5 or more then round it up (for example, 2.4 should be 2 and 2.7 should be 3).\r\nIf one or more domains are 1-Very Poor consider high risk.\r\nIf more than three domains are 2- Poor consider high risk.",
        display_name_km: "ពិន្ទុសរុបនៃការបា៉ន់ប្រមាណផ្នែកសុខុមាលភាពកុមារ",
        help_text_km: "ចូរបូកពិន្ទុសរុបផ្នែកទាំងអស់ ហើយចែកនឹង ៥ ។ ក្នុងករណីពិន្ទុមានទសភាគ ត្រូវបង្គត់។បើមានផ្នែកណា ១ ឬច្រើនជាង១ ទទួលបានពិន្ទុ ១ - ខ្សោយខ្លាំង កំណត់ថាមានហានិភ័យខ្ពស់។ បើមានផ្នែកចំនួនច្រើនជាង ៣​ ទទួលបានពិន្ទុ ២ - ខ្សោយ កំណត់ថាមានហានិភ័យខ្ពស់។",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-scoring-f82eeaa",
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

