FormSection.create_or_update!(
  {
    name_en: "Child's Views",
    description_en: "Child's Views",
    name_km: "មតិយោបល់កុមារ",
    description_km: "មតិយោបល់កុមារ",
    unique_id: "cp_views_subform_child_view_section",
    parent_form: "case",
    visible: false,
    order: 999,
    order_form_group: 999,
    order_subform: 1,
    form_group_keyed: false,
    editable: true,
    core_form: false,
    is_nested: true,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "child_view_date",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of the child's viewpoint",
        help_text_en: "",
        display_name_km: "កាលបរិច្ឆេទនៃមតិយោបល់កុមារ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_view_subject",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Subject of the child's viewpoint",
        help_text_en: "",
        display_name_km: "ប្រធានបទនៃមតិយោបល់កុមារ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_view",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Child's views and wishes",
        help_text_en: "Child's views and wishes regarding their needs and care and living arrangements.",
        display_name_km: "មតិយោបល់ និងបំណង​",
        help_text_km: "មតិយោបល់ និងបំណង​កុមារ ទាក់ទងនឹងតម្រូវការ​ និងការថែទាំ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

FormSection.create_or_update!(
  {
    name_en: "Carer's Views",
    description_en: "Carer's Views",
    name_km: "មតិយោបល់អ្នកថែទាំ",
    description_km: "មតិយោបល់អ្នកថែទាំ",
    unique_id: "cp_views_subform_carer_view_section",
    parent_form: "case",
    visible: false,
    order: 999,
    order_form_group: 999,
    order_subform: 1,
    form_group_keyed: false,
    editable: true,
    core_form: false,
    is_nested: true,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "carer_view_date",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of the carer's viewpoint",
        help_text_en: "",
        display_name_km: "កាលបរិច្ឆេទនៃមតិយោបល់អ្នកថែទាំ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "carer_view_subject",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Subject of the carer's viewpoint",
        help_text_en: "",
        display_name_km: "ប្រធានបទនៃមតិយោបល់អ្នកថែទាំ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "carer_view",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Details about the Carer's views",
        help_text_en: "Child's carer's views regarding the child and their experience of and capacity for caring for the child.",
        display_name_km: "សេចក្តីលម្អិតពីមតិយោបល់អ្នកថែទាំ",
        help_text_km: "មតិយោបល់អ្នកថែទាំទាក់ទងនឹងកុមារ​ និងបទពិសោធន៍ និងសមត្ថភាពរបស់គាត់ក្នុងការថែទាំកុមារ។",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

FormSection.create_or_update!(
  {
    name_en: "View of Professionals",
    description_en: "View of Professionals",
    name_km: "មតិយោបល់អ្នកជំនាញ",
    description_km: "មតិយោបល់អ្នកជំនាញ",
    unique_id: "cp_views_subform_professional_view_section",
    parent_form: "case",
    visible: false,
    order: 999,
    order_form_group: 999,
    order_subform: 1,
    form_group_keyed: false,
    editable: true,
    core_form: false,
    is_nested: true,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "professional_view_date",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of the professional's viewpoint",
        help_text_en: "",
        display_name_km: "កាលបរិច្ឆទនៃមតិយោបល់អ្នកជំនាញ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "professional_view_subject",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Subject of the professional's viewpoint",
        help_text_en: "",
        display_name_km: "ប្រធានបទនៃមតិយោបល់អ្នកជំនាញ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "professional_view",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Details about the professional's views",
        help_text_en: "View of professionals who know the child (such as education, health workers and other NGO staff).",
        display_name_km: "សេចក្តីលម្អិតពីមតិយោបល់អ្នកជំនាញ",
        help_text_km: "មតិយោបល់អ្នកជំនាញដែលស្គាល់កុមារ (ដូចជា បុគ្គលិកអប់រំ បុគ្គលិកសុខាភិបាល និង បុគ្គលិកអង្គការ) ។",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

FormSection.create_or_update!(
  {
    name_en: "Views and Wishes",
    description_en: "",
    name_km: "មតិយោបល់ និងបំណង​",
    description_km: "",
    unique_id: "cp_views",
    parent_form: "case",
    visible: true,
    order: 80,
    order_form_group: 2,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "child_s_wellbeing_assessment_74328",
    editable: true,
    core_form: false,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "views_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Form for capturing viewpoints on the child's situation from the child, the caregiver, and professionals involved with child and the child's family",
        help_text_en: "",
        display_name_km: "កំណត់ត្រាមតិយោបល់ និងបំណងរបស់កុមារ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "does_the_child_want_to_trace_family_members",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child want to trace family members?",
        help_text_en: "",
        display_name_km: "តើ​កុមារ​ចង់​ស្វែងរក​សមាជិក​គ្រួសារ​ដែ​រឬទេ?",
        help_text_km: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "if_the_child_does_not_want_family_tracing_explain_why",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If the child does NOT want family tracing , explain why",
        help_text_en: "",
        display_name_km: "ប្រសិន​បើ​កុមារ​មិន​ចង់​​ស្វែងរក​គ្រួសារ សូម​ពន្យល់​អំពី​មូលហេតុ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "does_the_child_want_family_reunification",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Does the child want family reunification?",
        help_text_en: "",
        display_name_km: "តើ​កុមារ​ចង់​ឲ្យ​មាន​ការ​បង្រួមបង្រួម​គ្រួសារ​ដែ​រឬទេ?",
        option_strings_text_en: [
          {
            id: "yes_as_soon_as_possible_79783",
            display_text: "Yes, as soon as possible"
          },
          {
            id: "yes_but_later_77976",
            display_text: "Yes, but later"
          },
          {
            id: "not_sure_38324",
            display_text: "Not sure"
          },
          {
            id: "no_31213",
            display_text: "No"
          }
        ],
        option_strings_text_km: [
          {
            id: "yes_as_soon_as_possible_79783",
            display_text: "បាទ/ចាស ឲ្យ​បាន​ឆាប់​តាម​ដែលអាច​ធ្វើ​បាន"
          },
          {
            id: "yes_but_later_77976",
            display_text: "បាទ/ចាស ប៉ុន្តែ​នៅ​ពេល​ក្រោយ"
          },
          {
            id: "not_sure_38324",
            display_text: "មិន​ប្រាកដ​"
          },
          {
            id: "no_31213",
            display_text: "ទេ"
          }
        ],
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "if_yes_with_whom_does_the_child_want_to_live_with",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "If yes, with whom does the child want to live with?",
        help_text_en: "",
        display_name_km: "បើបាទ/ច៎ាស, តើកុមារចង់រស់នៅជាមួយនរណា?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-family-relationship",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "if_no_not_sure_or_yes_but_later_explain_why",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If 'No', 'Not sure', or 'Yes, but later', explain why",
        help_text_en: "",
        display_name_km: "ប្រសិនបើ 'ទេ', 'មិនប្រាកដ' ឬ 'បាទ/ចាស​ ប៉ុន្តែ​ពេលក្រោយ' សូម​ពន្យល់​អំពី​មូលហេតុ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "does_the_child_wish_to_continue_in_the_current_care_arrangement",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child wish to continue in the current care arrangement?",
        help_text_en: "",
        display_name_km: "តើ​កុមារ​​ចង់​បន្ត​ស្នាក់​នៅ​ក្នុង​ការរៀបចំ​ថែទាំ​បច្ចុប្បន្ន​ដែរ​ឬទេ?",
        help_text_km: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "if_not_please_explain_why",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If not, please explain why",
        help_text_en: "",
        display_name_km: "បើទេ ចូរពន្យល់ហេតុអ្វី",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "type_of_care_arrangement_child_wishes_to_have",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: true,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Type of care arrangement child wishes to have",
        help_text_en: "",
        display_name_km: "ប្រភេទ​ការ​រៀបចំ​ថែទាំ​ដែល​កុមារ​ចង់​បាន",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-type-of-care-arrangement-f46aca5",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "if_other_please_specify",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If other, please specify",
        help_text_en: "",
        display_name_km: "បើផ្សេងទៀត ចូរបញ្ជាក់",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "where_does_the_child_wishplan_to_live",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Where does the child wish/plan to live?",
        help_text_en: "Enter country, province, district, commune, village when searching for a location",
        display_name_km: "តើ​កុមារ​ចង់/មានគម្រោង​រស់នៅ​ទីណា?",
        help_text_km: "សូមបញ្ចូល ប្រទេស::រាជធានី/ខេត្ត::ស្រុក/ខ័ណ្ឌ::ឃុំ/សង្កាត់::ភូមិ ពេលស្វែងរកទីតាំង",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "address_where_does_the_child_wishplan_to_live",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Address where the child wish/plan to live?",
        help_text_en: "House number, street number and relevant landmarks",
        display_name_km: "អាសយដ្ឋាន​ដែល​កុមារ​ចង់ទៅ​រស់​នៅ?",
        help_text_km: "លេខផ្ទះ លេខផ្លូវ និង ទីកន្លែងសម្គាល់",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_views_subform_child_view_section",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "subform",
        editable: true,
        disabled: false,
        display_name_en: "Child's Views",
        help_text_en: "",
        display_name_km: "មតិយោបល់កុមារ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        subform_unique_id: "cp_views_subform_child_view_section"
      },
      {
        name: "cp_views_subform_carer_view_section",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "subform",
        editable: true,
        disabled: false,
        display_name_en: "Carer's Views",
        help_text_en: "",
        display_name_km: "មតិយោបល់អ្នកថែទាំ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        subform_unique_id: "cp_views_subform_carer_view_section"
      },
      {
        name: "cp_views_subform_professional_view_section",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "subform",
        editable: true,
        disabled: false,
        display_name_en: "View of Professionals",
        help_text_en: "",
        display_name_km: "មតិយោបល់អ្នកជំនាញ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        subform_unique_id: "cp_views_subform_professional_view_section"
      }
    ]
  }
)

