FormSection.create_or_update!(
  {
    unique_id: "tracing_actions_section",
    name_i18n: {
      en: "Nested Tracing Action",
      km: "សកម្មភាព​ស្វែងរក"
    },
    description_i18n: {
      en: "Tracing Action Subform",
      km: "ទម្រង់​ស្វែងរក"
    },
    parent_form: "case",
    visible: false,
    order: 20,
    order_form_group: 130,
    order_subform: 2,
    form_group_keyed: false,
    editable: true,
    core_form: false,
    is_nested: true,
    is_first_tab: false,
    initial_subforms: 1,
    subform_prevent_item_removal: false,
    subform_append_only: false,
    subform_header_links: [],
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    collapsed_field_names: [
      "date_tracing",
      "tracing_type"
    ],
    fields_attributes: [
      {
        name: "date_tracing",
        type: "date_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Date of tracing",
          km: "កាលបរិច្ឆេទ​ស្វែងរក​"
        },
        order: 0,
        hidden_text_field: false,
        collapsed_field_for_subform_section_id: 1709,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        collapsed_field_for_subform_unique_id: "tracing_actions_section"
      },
      {
        name: "tracing_type",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Type of action taken",
          km: "ប្រភេទនៃការស្វែងរក"
        },
        option_strings_text_i18n: [
          {
            id: "case_by_case_tracing",
            display_text: {
              en: "Case by Case Tracing",
              km: "ការស្វែងរកតាមករណីនីមួយៗ"
            }
          },
          {
            id: "individual_tracing",
            display_text: {
              en: "Individual Tracing",
              km: "ការ​ស្វែងរកករណីម្នាក់ៗ"
            }
          },
          {
            id: "mass_tracing",
            display_text: {
              en: "Mass Tracing",
              km: "ការ​ស្វែងរក​ជាក្រុម"
            }
          },
          {
            id: "photo_tracing",
            display_text: {
              en: "Photo Tracing",
              km: "ការ​ស្វែងរកតាម​រូបថត"
            }
          },
          {
            id: "referral_to_ngo",
            display_text: {
              en: "Referral to NGO",
              km: "បញ្ជូន​ទៅ​អង្គការ​មិនមែន​រដ្ឋាភិបាល"
            }
          },
          {
            id: "referral_to_icrc",
            display_text: {
              en: "Referral to ICRC",
              km: "បញ្ជូន​ទៅ ICRC"
            }
          }
        ],
        order: 1,
        hidden_text_field: false,
        collapsed_field_for_subform_section_id: 1709,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        collapsed_field_for_subform_unique_id: "tracing_actions_section"
      },
      {
        name: "address_tracing",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Address/Village where the tracing action took place",
          km: "អាសយដ្ឋាន/ភូមិ​ដែល​សកម្មភាព​ស្វែងរក​កើតឡើង"
        },
        order: 2,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "location_tracing",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Location of Tracing",
          km: "ទីតាំង​ស្វែងរក"
        },
        option_strings_source: "Location",
        order: 3,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "tracing_action_description",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Action taken and remarks",
          km: "សកម្មភាព និង​កំណត់​សម្គាល់"
        },
        order: 4,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "tracing_outcome",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Outcome of tracing action",
          km: "លទ្ធផល​នៃ​សកម្មភាព​ស្វែងរក"
        },
        option_strings_text_i18n: [
          {
            id: "pending",
            display_text: {
              en: "Pending",
              km: "កំពុង​រង់ចាំ"
            }
          },
          {
            id: "successful",
            display_text: {
              en: "Successful",
              km: "ជោគជ័យ"
            }
          },
          {
            id: "unsuccessful",
            display_text: {
              en: "Unsuccessful",
              km: "មិន​ជោគជ័យ"
            }
          },
          {
            id: "yes",
            display_text: {
              en: "Yes",
              km: "បាទ/ចា៎ស"
            }
          }
        ],
        order: 5,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "next_steps_tracing",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "If tracing is unsuccessful, what is the next step?",
          km: "ប្រសិនបើការស្វែងរកមិនបានជោគជ័យ តើត្រូវធ្វើអ្វីបន្តទៀត?"
        },
        help_text_i18n: {
          en: ""
        },
        order: 6,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        }
    ],
    module_ids: [
      "primeromodule-cp"
    ]
  }
)

FormSection.create_or_update!(
  {
    unique_id: "tracing",
    name_i18n: {
      en: "Tracing",
      km: "ការ​ស្វែងរក"
    },
    description_i18n: {
      en: "Tracing",
      km: "ការ​ស្វែងរក"
    },
    parent_form: "case",
    visible: true,
    order: 10,
    order_form_group: 3,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "tracing",
    editable: true,
    core_form: false,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    subform_append_only: false,
    subform_header_links: [],
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    fields_attributes: [
      {
        name: "matched_tracing_request_id",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: false,
        disabled: true,
        display_name_i18n: {
          en: "Matched Tracing Request ID",
          km: "ផ្គូផ្គង​លេខកូដ​ស្វែងរក​"
        },
        order: 0,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path: "tracing_request",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "separation_separator",
        type: "separator",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Separation History: only applies to a child not living under parental care",
          km: "ប្រវត្តិបែកពីគ្រួសារ៖ អនុវត្តចំពោះតែកុមារដែលបែកពីឪពុក/ម្តាយ"
        },
        help_text_i18n: {
          en: ""
        },
        order: 1,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "tracing_status",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Tracing Status",
          km: "ស្ថានភាព​​ស្វែងរក"
        },
        option_strings_source: "lookup lookup-tracing-status",
        order: 2,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "date_of_separation",
        type: "date_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Date of Separation",
          km: "កាលបរិច្ឆេទ​នៃការបែកពីគ្រួសារ"
        },
        order: 3,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: true,
        mandatory_for_completion: false,
        },
      {
        name: "separation_cause",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "What was the main cause of separation?",
          km: "មូលហេតុ​ចម្បង​"
        },
        option_strings_source: "lookup lookup-separation-cause",
        order: 4,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: true,
        mandatory_for_completion: false,
        },
      {
        name: "separation_cause_other",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "If Other, please specify",
          km: "ប្រសិនបើ​ផ្សេងទៀត សូម​បញ្ជាក់"
        },
        order: 5,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: true,
        mandatory_for_completion: false,
        },
      {
        name: "separation_other_applicable_causes",
        type: "select_box",
        multi_select: true,
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "If applicable, what were other causes of separation? ",
          km: "ប្រសិនបើ​មាន​ តើ​អ្វី​ជា​មូលហេតុ​​ផ្សេង​ទៀត​នៃការបែកចេញពីគ្រួសារ?"
        },
        option_strings_source: "lookup lookup-separation-cause",
        order: 6,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "separation_details",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Circumstances of Separation (please provide details)",
          km: "សូម​ផ្ដល់​ព័ត៌មាន​លម្អិត"
        },
        help_text_i18n: {
          en: "",
          km: ""
        },
        order: 7,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "separation_additional_movements",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Describe additional movements between place of separation and current location",
          km: "ពិពណ៌នាអំពីការ​ផ្លាស់ទីរបស់កុមារ​រវាងទីកន្លែងដែលកុមារបែកគ្នា និងទីកន្លែងដែលកុមាររស់នៅបច្ចុប្បន្ន"
        },
        order: 8,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "separation_witnessed_violence",
        type: "radio_button",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Did the child face or witness any type of violence, threat or harm during his/her journey?",
          km: "តើកុមារធ្លាប់ឃើញ ឬរងនូវអំពើហិង្សា, ការគំរាមកំហែង ឬគ្រោះថ្នាក់ក្នុងអំឡុងពេលធ្វើដំណើរដែរឬទេ?"
        },
        help_text_i18n: {
          en: ""
        },
        option_strings_source: "lookup lookup-yes-no-unknown",
        order: 9,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "separation_witnessed_violence_comments",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Details about what the child faced / witnessed",
          km: "ព័ត៌មានលម្អិតអំពីអ្វីដែលកុមារបានឃើញ/ជួបប្រទះ"
        },
        order: 10,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "address_separation",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Separation Address (Place)",
          km: "អាសយដ្ឋានដែលបែកពីគ្រួសារ"
        },
        order: 11,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "location_separation",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Separation Location",
          km: "ទីតាំងបែក"
        },
        option_strings_source: "Location",
        order: 12,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: true,
        mandatory_for_completion: false,
        },
      {
        name: "additional_tracing_info",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Additional info that could help in tracing?",
          km: "ព័ត៌មាន​បន្ថែម​​ដែល​អាច​ជួយ​ក្នុងការ​ស្វែងរក?"
        },
        order: 13,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "evacuation_status",
        type: "radio_button",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Has child been evacuated?",
          km: "តើ​កុមារ​ត្រូវ​បាន​ជម្លៀស​​ចេញ​ដែរ​ឬទេ?"
        },
        option_strings_source: "lookup lookup-yes-no",
        order: 14,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "evacuation_agent",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "If yes, through which organization?",
          km: "ប្រសិន​បើ​បាទ/ចា៎ស តើ​តាមរយៈ​អង្គការ​ណា​?"
        },
        order: 15,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "evacuation_from",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Evacuated From",
          km: "​ជម្លៀស​ចេញ​ពី"
        },
        order: 16,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "evacuation_date",
        type: "date_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Evacuation Date",
          km: "កាលបរិច្ឆេទនៃការ​ជម្លៀស​"
        },
        order: 17,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "evacuation_to",
        type: "text_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Evacuated To",
          km: "ជម្លៀស​ទៅ"
        },
        order: 18,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "care_arrangements_arrival_date",
        type: "date_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Arrival Date",
          km: "កាលបរិច្ឆេ​ទ​មក​ដល់"
        },
        order: 19,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        },
      {
        name: "tracing_actions_section",
        type: "subform",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          en: "Tracing Actions",
          km: "សកម្មភាព​ស្វែងរក"
        },
        order: 20,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false,
        subform_unique_id: "tracing_actions_section"
      }
    ],
    module_ids: [
      "primeromodule-cp"
    ]
  }
)

