FormSection.create_or_update!(
  {
    name_en: "Consent for Referrals",
    description_en: "Consent for Referrals",
    name_ar: "موافقة على الإحالة",
    description_ar: "موافقة على الإحالة",
    name_ku: "رەزامەندی بۆ رەوانەکردن",
    description_ku: "رەزامەندی بۆ رەوانەکردن",
    'name_ku-IQ': "رازەمەندی بۆ رەوانەکرنێ",
    'description_ku-IQ': "رازەمەندی بۆ رەوانەکرنێ",
    unique_id: "consent_for_referrals",
    parent_form: "case",
    visible: true,
    order: 10,
    order_form_group: 65,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "consent_for_referrals",
    editable: true,
    core_form: false,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "consent_release_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information by Referral Type",
        display_name_ar: "موافقة على الإفصاح عن معلومات حسب نوع الإحالة",
        display_name_ku: "رەزامەندی لەسەر دەرخستنی زانیاریەكان بەپێی جۆری رەوانەکردن",
        'display_name_ku-IQ': "رازەمەندی بۆ بەلاڤکرنا پێزانینا ل گوری جورێ رەوانەکرنێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_security",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Security Services",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى دوائر الأمن",
        display_name_ku: "رەزامەندی لەسەر دەرخستنی زانیاریەكان بۆ خزمەتگوزاریەكانی ئاسایش",
        'display_name_ku-IQ': "رازەمەندی بۆ بەلاڤکرنا پێزانینا بو خزمەتگوزاریێن ئێمناهیێ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_security_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Security Name, Facility or Agency/Organization as applicable",
        display_name_ar: "حدد اسم المسؤول الأمني أو الهيئة أو المؤسسة الأمنية حسب الاقتضاء",
        display_name_ku: "دیاریكردنی ناوی ئاسایش، دەزگا یان ئاژانس / رێكخراو بەپێی پێویست",
        'display_name_ku-IQ': "ناڤێ ئێمناهیێ دیارکە، سازی یان ئاژانس یان رێکخراو لديف چێبوونێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_psychosocial",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Psychosocial Services",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات الدعم النفسي والاجتماعي",
        display_name_ku: "رەزامەندی لەسەر دەرخستنی زانیاریەكان بۆ خزمەتگوزاریە دەروونیەكان",
        'display_name_ku-IQ': "رازەمەندی بۆ بەلاڤکرنا پێزانینا بۆ خزمەتگوزاریێن دەروونی",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_psychosocial_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Psychosocial Name, Facility or Agency/Organization as applicable",
        display_name_ar: "حدد اسم الأخصائي الاجتماعي أو الهيئة أو المؤسسة التي تقدم الدعم النفسي الاجتماعي حسب الاقتضاء",
        display_name_ku: "دیاریكردنی ناوی دەروونی، دەزگا یان ئاژانس / رێكخراو بەپێی پێویست",
        'display_name_ku-IQ': "ناڤێ دەروونێ جڤاکی دیارکە، سازی یان ئاژانس یان رێکخراو لديف چێبوونێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_health",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Health/Medical Services",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى الخدمات الصحية / الطبية",
        display_name_ku: "رەزامەندی لەسەر دەرخستنی زانیاریەكان بۆ خزمەتگوزاریە تەندروستی/پزیشكیەكان",
        'display_name_ku-IQ': "رازەمەندی بۆ بەلاڤکرنا پێزانینا بۆ خزمەتگوزاریێن ساخلەمی یان پزیشکی",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_health_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Health/Medical Name, Facility or Agency/Organization as applicable",
        display_name_ar: "حدد اسم الأخصائي الصحي/الطبي أو المنشأة أو المؤسسة الطبية حسب الاقتضاء",
        display_name_ku: "دیاریكردنی ناوی تەندروستی / پزیشكی، دەزگا یان ئاژانس / رێكخراو بەپێی پێویست",
        'display_name_ku-IQ': "ناڤێ ساخلەمی یان پزیشکی دیارکە، سازی یان ئاژانس یان رێکخراو لديف چێبوونێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_safehouse",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Safe House/Shelter",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى بيت آمن / مأوى",
        display_name_ku: "رەزامەندی لەسەر دەرخستنی زانیاریەكان بۆ خانەی ئارام / پەناگە",
        'display_name_ku-IQ': "رازەمەندی بۆ بەلاڤکرنا پێزانینا بۆ مالا ئارام یان پەناگە",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_safehouse_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Safe House/Shelter Name, Facility or Agency/Organization as applicable",
        display_name_ar: "حدد اسم البيت الآمن / المأوى أو المنشأة أو الهيئة أو المؤسسة المعنية حسب الاقتضاء",
        display_name_ku: "دیاریكردنی ناوی خانەی ئارام/ پەناگە، دەزگا یان ئاژانس / رێكخراو بەپێی پێویست",
        'display_name_ku-IQ': "ناڤێ مالا ئارام یان پەناگەهی دیارکە، سازی یان ئاژانس یان رێکخراو",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_legal",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Legal Assistance Services",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات المساعدة القانونية",
        display_name_ku: "رەزامەندی لەسەر دەرخستنی زانیاریەكان بۆ خزمەتگوزاریەكانی هاوكاری یاسایی",
        'display_name_ku-IQ': "رازەمەندی بۆ بەلاڤکرنا پێزانینا بۆ خزمەتگوزاریێن هاریکاریا قانونی",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_legal_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Legal Assistance Name, Facility or Agency/Organization as applicable",
        display_name_ar: "حدد اسم أخصائي المساعدة القانونية أو الهيئة أو المؤسسة التي تقدم خدمات المساعدة القانونية حسب الاقتضاء",
        display_name_ku: "دیاریكردنی ناوی هاوكاری یاسایی، دەزگا یان ئاژانس / رێكخراو بەپێی پێویست",
        'display_name_ku-IQ': "ناڤێ هاریکاریا قانونی دیارکە، سازی یان ئاژانس یان رێکخراو لديف چێبوونێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_protection",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Protection Services",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات الحماية",
        display_name_ku: "رەزامەندی لەسەر دەرخستنی زانیاریەكان بۆ خزمەتگوزاریەكانی پاراستن",
        'display_name_ku-IQ': "رازەمەندی بۆ بەلاڤکرنا پێزانینا بۆ خزمەتگوزاریێن پاراستنێ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_protection_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Protection Services Name, Facility or Agency/Organization as applicable",
        display_name_ar: "حدد اسم أخصائي خدمات الحماية أو الهيئة أو المؤسسة المعنية التي تقدم خدمات الحماية حسب الاقتضاء",
        display_name_ku: "دیاریكردنی ناوی خزمەتگوزاریەكانی پاراستن، دەزگا یان ئاژانس / رێكخراو بەپێی پێویست",
        'display_name_ku-IQ': "ناڤێ خزمەتگوزاریێن پاراستنێ دیارکە، سازی یان ئاژانس یان رێکخراو لديف چێبوونێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_livelihoods",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Livelihoods Services",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات سبل العيش",
        display_name_ku: "رەزامەندی لەسەر دەرخستنی زانیاریەكان بۆ خزمەتگوزاریەكانی بژێوی",
        'display_name_ku-IQ': "رازەمەندی بۆ بەلاڤکرنا پێزانینا بۆ خزمەتگوزاریێن ژیارێ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_livelihoods_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Livelihoods Services Name, Facility or Agency/Organization as applicable",
        display_name_ar: "حدد اسم أخصائي خدمات سبل العيش أو الهيئة أو المؤسسة المعنية التي تقدم خدمات سبل العيش حسب الاقتضاء",
        display_name_ku: "دیاریكردنی ناوی خزمەتگوزاریەكانی بژێوی، دەزگا یان ئاژانس / رێكخراو بەپێی پێویست",
        'display_name_ku-IQ': "ناڤێ خزمەتگوزاریێن ژیارێ دیارکە، سازی یان ئاژانس یان رێکخراو لديف چێبوونێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Other Services",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات أخرى",
        display_name_ku: "رەزامەندی لەسەر دەرخستنی زانیاریەكان بۆ خزمەتگوزاری دیكە",
        'display_name_ku-IQ': "رازەمەندی بۆ بەلاڤکرنا پێزانینا بۆ خزمەتگوزاریێن دی",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_other_details",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If other services, please specify service, name and agency",
        display_name_ar: "في حالة خدمات أخرى، يرجى تحديد اسم الأخصائي المعني أو المؤسسة المعنية بتقديم هذه الخدمات",
        display_name_ku: "ئەگەر خزمەتگوزاری دیكە لە ئارادابوو، تكایە خزمەتگوزارییەکە، ناو و ئاژانسەكە دیاریبكە",
        'display_name_ku-IQ': "ئەگەر خزمەتگوزاریێن دی هەبن، هیڤیدارین وان خزمەتگوزاریا، ناڤ و ئاژانسێ دیارکە",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

