FormSection.create_or_update!(
  {
    name_en: "Survivor Information",
    description_en: "Survivor Information",
    name_ar: "معلومات عن الناجية",
    description_ar: "معلومات عن الناجية",
    name_ku: "زانیاری رزگاربوو",
    description_ku: "زانیاری رزگاربوو",
    'name_ku-IQ': "پێزانینێن رزگاربووی",
    'description_ku-IQ': "پێزانینێن رزگاربووی",
    unique_id: "gbv_survivor_information",
    parent_form: "case",
    visible: true,
    order: 10,
    order_form_group: 20,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "identification_registration",
    editable: true,
    core_form: false,
    is_nested: false,
    is_first_tab: true,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "case_id",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Long ID",
        display_name_ar: "الرمز التعريفي المطول",
        display_name_ku: "ناسنامەی درێژ",
        'display_name_ku-IQ': "ناسناما درێژ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "short_id",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Case ID",
        display_name_ar: "رقم تعريف الحالة",
        display_name_ku: "ناسنامەی  كەیس",
        'display_name_ku-IQ': "ناسناما کەیسی",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "marked_for_mobile",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "tick_box",
        editable: false,
        disabled: true,
        display_name_en: "Marked for mobile?",
        tick_box_label_en: "Yes",
        display_name_ar: "تم تأشيرة في الهاتف المحمول",
        tick_box_label_ar: "نعم",
        display_name_ku: "نیشانەكراو بۆ مۆبایل",
        tick_box_label_ku: "بەڵێ",
        'display_name_ku-IQ': "دەستنینشانکریە بۆ موبایلێ؟",
        'tick_box_label_ku-IQ': "بەلێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Case Status",
        display_name_ar: "الوضع الراهن للحالة",
        display_name_ku: "باری كەیس",
        'display_name_ku-IQ': "بارودوخێ کەیسی",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-case-status",
        autosum_total: false,
        autosum_group: "",
        selected_value: "open",
        required: false
      },
      {
        name: "name",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Name",
        display_name_ar: "الاسم",
        display_name_ku: "ناو",
        'display_name_ku-IQ': "ناڤ",
        multi_select: false,
        hidden_text_field: true,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "survivor_code_no",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Survivor Code",
        display_name_ar: "رمز الناجية",
        display_name_ku: "كۆدی رزگاربوو",
        'display_name_ku-IQ': "کودێ رزگاربووی",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "age",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Age",
        help_text_en: "A number needs to be written in English",
        display_name_ar: "العمر",
        help_text_ar: "",
        display_name_ku: "تەمەن",
        help_text_ku: "",
        'display_name_ku-IQ': "تەمەن",
        'help_text_ku-IQ': "ژمارە بگشتی دڤێت ب زمانێ ئنگلیزى بهێنە نڤێسان",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "date_of_birth",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of Birth",
        display_name_ar: "تاريخ الميلاد",
        display_name_ku: "رێكەوتی لەدایكبوون",
        'display_name_ku-IQ': "روژا ژدایکبوونێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        date_validation: "not_future_date"
      },
      {
        name: "sex",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Sex",
        display_name_ar: "الجنس",
        display_name_ku: "رەگەز",
        'display_name_ku-IQ': "رەگەز",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-gender",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "gbv_ethnicity",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Clan or Ethnicity",
        display_name_ar: "الطائفة أو الإثنية",
        display_name_ku: "هۆز یان نەژاد",
        'display_name_ku-IQ': "هوز یان نەژاد",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-ethnicity",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "country_of_origin",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Country of Origin",
        display_name_ar: "البلد الأصلي",
        display_name_ku: "وڵاتی بنچینەیی",
        'display_name_ku-IQ': "وەلاتێ رەسەن",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-country",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "gbv_nationality",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Nationality (if different than country of origin)",
        display_name_ar: "الجنسية (إذا كانت مختلفة عن البلد الأصلي)",
        display_name_ku: "رەگەزنامە (ئەگەر لە وڵاتی بنچینەیی جیاواز بوو)",
        'display_name_ku-IQ': "نەتەوە، (ئەگەر وەك وەلاتێ رەسەن نەبیت)",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-nationality",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "gbv_religion",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Religion",
        display_name_ar: "الدين",
        display_name_ku: "ئاین",
        'display_name_ku-IQ': "ئاین",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-religion",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "maritial_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Current Civil/Marital Status",
        display_name_ar: "الحالة المدنية / الزوجية الحالية",
        display_name_ku: "باری شارستانی / هاوسەرگیری لە ئێستادا",
        'display_name_ku-IQ': "بارودوخێ نوکە یێ مەدەنی یان هەڤژینیێ؟",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-marital-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "dependents_no",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Number and age of children and other dependents",
        display_name_ar: "عدد الأطفال والمعالين الآخرين وأعمارهم",
        display_name_ku: "ژمارەو تەمەنی منداڵ و کەسانی نزیکی دی",
        'display_name_ku-IQ': "ژمارە و تەمەنێ زاروکا",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "occupation",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Occupation",
        display_name_ar: "المهنة",
        display_name_ku: "پیشە",
        'display_name_ku-IQ': "کار",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "gbv_displacement_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Displacement Status at time of report",
        display_name_ar: "وضع النزوح في وقت الإبلاغ",
        display_name_ku: "باری ئاوارەبوون لە كاتی ریپۆرتكردن",
        'display_name_ku-IQ': "بارودوخێ ئاوارەبوونێ ل دەمێ نڤیسینا راپورتێ",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-displacement-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "gbv_disability_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Is the Survivor a Person with Disabilities?",
        display_name_ar: "هل تعاني الناجية من إعاقة؟",
        display_name_ku: "ئایا رزگاربوو کەسێکی خاوەن پێداویستی تایبەتە؟",
        'display_name_ku-IQ': "ئەرێ رزگاربوو کەسەکێ خودان پێدڤیێن تایبەتە؟",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-disability-type-with-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "unaccompanied_separated_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Is the Survivor an Unaccompanied Minor, Separated Child, or Other Vulnerable Child?",
        display_name_ar: "هل الناجية من القصّر غير المصحوبين أو من الأطفال المنفصلين عن ذويهم أو من الأطفال المستضعفين من فئات أخرى؟",
        display_name_ku: "ئایا رزگاربوو پێنەگەیشتوویەكی تەنیایە، منداڵێكی دابڕاوە، یان منداڵێكی دیکەیە کە مەترسی لەسەرە؟",
        'display_name_ku-IQ': "ئەرێ رزگاربوو سنێلەکێ بتنێ یە، زاروکەکێ جودابوویی ژ خێزانا خویە یان ژ زاروکێن دی یێن لاوازە؟",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-unaccompanied-separated-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "section_heading_child_survivors_less_than_18_years_old",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Child Survivors (less than 18 years old)",
        display_name_ar: "الناجيات من الأطفال (دون الـ 18 من العمر)",
        display_name_ku: "منداڵی رزگاربوو (كەمتر لە تەمەنی 18 ساڵی)",
        'display_name_ku-IQ': "رزگاربوویێن زاروك (ل ژێر تەمەنێ ١٨ سالیێ",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        field_tags: [
          "child"
        ],
        required: false
      },
      {
        name: "survivor_lives_alone",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "If the survivor is a child, does he/she live alone?",
        display_name_ar: "هل الناجي طفل / هل الناجية طفلة، هل يعيش لوحده / تعيش لوحدها؟",
        display_name_ku: "ئەگەر رزگاربوو منداڵە، ئایا بە تەنیا دەژی؟",
        'display_name_ku-IQ': "ئەرێ رزگاربوو زاروکە، ئەرێ ئەو بتنێ دژیت؟",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        field_tags: [
          "child"
        ],
        required: false
      },
      {
        name: "survivor_caretaker",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "If the survivor lives with someone, what is the relation between her/him and the caretaker?",
        display_name_ar: "هل يعيش الناجي / تعيش الناجية مع شخص آخر يرعاها، ما العلاقة بينها وبين الشخص الراعي / مقدم الرعاية لها؟",
        display_name_ku: "ئەگەر رزگاربوو لەگەڵ كەسێكی دیکەدا دەژی، پەیوەندی نێوانی ئەوو چاودێرەكەی چیە؟",
        'display_name_ku-IQ': "ئەرێ رزگاربوو دگەل کەسەکی دژیت، پەیوەندی دناڤبەرا وان چیە؟",
        option_strings_text_en: [
          {
            id: "parent_guardian",
            display_text: "Parent/Guardian"
          },
          {
            id: "relative",
            display_text: "Relative"
          },
          {
            id: "spouse_cohabitating",
            display_text: "Spouse/Cohabitating"
          },
          {
            id: "other_please_specify",
            display_text: "Other, please specify"
          }
        ],
        option_strings_text_ar: [
          {
            id: "parent_guardian",
            display_text: "أحد الوالدين / وصي"
          },
          {
            id: "relative",
            display_text: "أحد الأقرباء"
          },
          {
            id: "spouse_cohabitating",
            display_text: "زوج / شريك دون زواج"
          },
          {
            id: "other_please_specify",
            display_text: "أخرى، يرجى التحديد"
          }
        ],
        option_strings_text_ku: [
          {
            id: "parent_guardian",
            display_text: "دایک یان باوک / بەخێوكار"
          },
          {
            id: "relative",
            display_text: "خزم"
          },
          {
            id: "spouse_cohabitating",
            display_text: "هاوسەر / هاوژین"
          },
          {
            id: "other_please_specify",
            display_text: "هی تر، تكایە دەستنیشانی بكە"
          }
        ],
        'option_strings_text_ku-IQ': [
          {
            id: "parent_guardian",
            display_text: "دەیباب یان پارێزڤان"
          },
          {
            id: "relative",
            display_text: "کەس و کار"
          },
          {
            id: "spouse_cohabitating",
            display_text: "هەڤژین"
          },
          {
            id: "other_please_specify",
            display_text: "یێن دی، هیڤیدارین دەستنیشان بکە"
          }
        ],
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        field_tags: [
          "child"
        ],
        required: false
      },
      {
        name: "survivor_caretaker_other",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If other relation between her/him and the caretaker, please specify.",
        display_name_ar: "في حال وجود علاقة أخرى بين الناجي/الناجية ومقدم الرعاية له/لها، يرجى التحديد.",
        display_name_ku: "ئەگەر پەیوەندی تر لەنێوان ئەوو چاودێرەكەی هەیە، تكایە دەستنیشانی بكە.",
        'display_name_ku-IQ': "ئەگەر پەیوەندیێن دی دناڤبەرا وی و چاڤدێری بن، هیڤیدارین دیار بکەی",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        field_tags: [
          "child"
        ],
        required: false
      },
      {
        name: "caretaker_marital_status",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "What is the caretaker's current marital status?",
        display_name_ar: "الحالة المدنية / الزوجية الراهنه لمقدم الرعاية للناجية",
        display_name_ku: "باری هاوسەرگیری چاوێریكارەكە چییە لە ئێستادا؟",
        'display_name_ku-IQ': "بارودوخێ هەڤژینیێ چاڤدێری چییە؟",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-marital-status-unknown",
        autosum_total: false,
        autosum_group: "",
        field_tags: [
          "child"
        ],
        required: false
      },
      {
        name: "caretaker_occupation",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "What is the caretaker's primary occupation?",
        display_name_ar: "المهنة الرئيسية الحالية لمقدم الرعاية للناجية؟",
        display_name_ku: "پیشەی سەرەكی چاودێرەكە چییە؟",
        'display_name_ku-IQ': "کارێ سەرەکی یێ چاڤدێری چییە؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        field_tags: [
          "child"
        ],
        required: false
      }
    ]
  }
)

