FormSection.create_or_update!(
  {
    name_en: "Protection Concerns",
    description_en: "Protection Concerns",
    unique_id: "protection_concern",
    parent_form: "case",
    visible: true,
    order: 20,
    order_form_group: 30,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "bia",
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "risk_level",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Risk Level",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-risk-level",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "case_priority",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Priority",
        help_text_en: "",
        option_strings_text_en: [
          {
            id: "2_days",
            display_text: "2 days"
          },
          {
            id: "1_week",
            display_text: "1 week"
          },
          {
            id: "30_days",
            display_text: "30 days"
          },
          {
            id: "non_urgent_enter_date",
            display_text: "Non Urgent (enter date)"
          }
        ],
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "case_priority_date",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Re-assessment date",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "protection_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: true,
        display_name_en: "Primary Protection Concern Old",
        help_text_en: "If 'Separated' is selected, enter 'cause of separation' on the Separation Details form.",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-protection-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "protection_concerns",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: true,
        display_name_en: "Protection Concerns Old",
        help_text_en: "",
        guiding_questions_en: "CR-CP: الطفل والد \nCR-CS: الطفل متزوج \nCR-CC: الطفل معيل \nCR-TP: طفلة حامل \nCR-LW: الطفل يعمل في أسوأ انواع العمالة \nCR-LO: الطفل عامل \nCR-NE: الطفل عرضة لعدم الالتحاق بالمدرسة \nCR-SE: الطفل بحاجة الى تعليم خاص \nCR-AF: الطفل مرتبط مع قوات او جماعات مسلحة \nCR-CL: الطفل جانح \nSC-CH: الطفل رب للأسرة \nSC-IC: الطفل ضمن رعاية مؤسسية \nSC-FC: الطفل ضمن رعاية بديلة \nDS-BD: الطفل يعاني من اعاقة بصرية \nDS-DF: الطفل يعاني من اعاقة سمعية \nDS-PM: الطفل يعاني من إعاقة جسدية \nDS-PS: الطفل يعاني من إعاقة جسدية شديدة \nDS-MM: الطفل يعاني من إعاقة عقلية \nDS-MS: الطفل يعاني من إعاقة عقلية شديدة \nDS-SD: الطفل يعاني من اعاقة نطقية \nSM-MI: الطفل يعاني من أمراض عقلية أو نفسية \nSM-MN: الطفل يعاني من سوء تغذية \nSM-CI: الطفل يعاني من أمراض مزمنة \nSM-CC: الطفل يعاني من حالة طبية حرجة \nSM-OT: الطفل يعاني من حالة طبية أخرى \nFU-TR: الطفل يحتاج الى تتبع الأقارب \nFU-FR: الطفل يحتاج الى لم شمل \nLP-ND: الطفل لا يملك أوراق قانونية \nTR-PI: الطفل يعاني من مشاكل جسدية أو نفسية بسبب التعذيب \nTR-HO: الطفل أجبر على أفعال شنيعة \nTR-WV: الطفل شاهد على عنف تعرض له الأخرين \nLP-AN: الطفل تعرض للعنف المبني على النوع أو الجنس \nLP-MD: الطفل تعرض للعنف أو للاستغلال أو للاهمال \nLP-MS: الطفل تعرض لعدة نزوحات (تنقلات) \nLP-RR: الطفل معرض للتهميش أو الرفض من المجتمع \nLP-BN: الطفل معرض للإعادة القصرية \nLP-NA: لا وصول الى الخدمة \nSM-DP: الحمل القصري \nSC-SC: طفل منفصل \nSC-UC: طفل غير مصحوب \nSV-VA: الناجي من العنف الجنسي في بلد اللجوء \nSV-VO: الناجي من العنف الجنسي في بلد المنشأ \nSV-VF:  الناجي من العنف الجنسي أثناء الطيران ",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-protection-concerns",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "protection_concerns_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: true,
        display_name_en: "If Other, please specify Old",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "primary_protection_concern",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Primary protection concern",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-primary-protection-concern",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "other_protection_concerns",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Other protection concerns",
        help_text_en: "",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-other-protection-concern",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "specify_the_gbv_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Specify the GBV Type",
        help_text_en: "as per GBV classification tool",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-gbv-sexual-violence-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "lpan_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Specify the LP-AN Type",
        help_text_en: "",
        option_strings_text_en: [
          {
            id: "violence_or_abuse",
            display_text: "Violence or abuse"
          },
          {
            id: "neglect",
            display_text: "Neglect"
          }
        ],
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "specificneedsconcers",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Specific Need",
        help_text_en: "",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-specific-need",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "urgent_protection_concern",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Urgent Protection Concern?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "displacement_status",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Displacement Status",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-displacement-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "unhcr_protection_code",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "UNHCR Protection Code",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "protection_concern_from_child",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Briefly describe the child's major concern/issue",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "unhcr_needs_codes",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: false,
        disabled: true,
        display_name_en: "Secondary Protection Concerns",
        help_text_en: "This field is populated automatically based on the Protection Concerns entered.",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-unhcr-needs-codes",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "disability_type",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Disability Type",
        option_strings_text_en: [
          {
            id: "mental_disability",
            display_text: "Mental Disability"
          },
          {
            id: "physical_disability",
            display_text: "Physical Disability"
          },
          {
            id: "both",
            display_text: "Both"
          }
        ],
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "bia_wishes_child_intervention",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child wish for intervention or particular support in relation to any of the above areas?",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "bia_wishes_child_intervention_details",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If yes, give details",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "intervention_in_conflict_wishes_child",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "If the assessment shows the need for intervention that is in addition or in conflict with the wishes of the child, has this been discussed with the child?",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "intervention_in_conflict_wishes_child_reason",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If not, why not? If this has been discussed what is the outcome?",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "steps_to_ensure_safety",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If the child is at risk, outline what steps are needed to ensure their safety and well-being",
        help_text_en: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

