FormSection.create_or_update!(
  {
    name_en: "Consent for Referrals",
    description_en: "Consent for Referrals",
    name_fr: "Consentement pour référencement",
    description_fr: "Consentement pour référencement",
    name_ar: "موافقة على الإحالة",
    description_ar: "موافقة على الإحالة",
    'name_ar-LB': "Consent for Referrals",
    'description_ar-LB': "Consent for Referrals",
    name_es: "Consent for Referrals",
    description_es: "Consent for Referrals",
    unique_id: "consent_for_referrals",
    parent_form: "case",
    visible: true,
    order: 10,
    order_form_group: 65,
    order_subform: 0,
    form_group_keyed: false,
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    form_group_id: "consent_for_referrals",
    fields_attributes: [
      {
        name: "consent_release_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information by Referral Type",
        display_name_fr: "Consentement pour partage d'informations par type de référencement",
        display_name_ar: "موافقة على الإفصاح عن معلومات حسب نوع الإحالة",
        'display_name_ar-LB': "Consent to Release Information by Referral Type",
        display_name_es: "Consent to Release Information by Referral Type",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_security",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Security Services",
        display_name_fr: "Consentement pour partage d'information avec des services de sécurité",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى دوائر الأمن",
        'display_name_ar-LB': "Consent to Release Information to Security Services",
        display_name_es: "Consent to Release Information to Security Services",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_security_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Security Name, Facility or Agency/Organization as applicable",
        display_name_fr: "Détailler le nom du service de sécurité, organisation ou agence",
        display_name_ar: "حدد اسم المسؤول الأمني أو الهيئة أو المؤسسة الأمنية حسب الاقتضاء",
        'display_name_ar-LB': "Specify Security Name, Facility or Agency/Organization as applicable",
        display_name_es: "Specify Security Name, Facility or Agency/Organization as applicable",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_psychosocial",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Psychosocial Services",
        display_name_fr: "Consentement pour partage d'informations avec un service psychosocial",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات الدعم النفسي والاجتماعي",
        'display_name_ar-LB': "Consent to Release Information to Psychosocial Services",
        display_name_es: "Consent to Release Information to Psychosocial Services",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_psychosocial_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Psychosocial Name, Facility or Agency/Organization as applicable",
        display_name_fr: "Détailler le nom de l'organisation ou agence en charge du service psychosocial",
        display_name_ar: "حدد اسم الأخصائي الاجتماعي أو الهيئة أو المؤسسة التي تقدم الدعم النفسي الاجتماعي حسب الاقتضاء",
        'display_name_ar-LB': "Specify Psychosocial Name, Facility or Agency/Organization as applicable",
        display_name_es: "Specify Psychosocial Name, Facility or Agency/Organization as applicable",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_health",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Health/Medical Services",
        display_name_fr: "Consentement pour partage d'informations avec un service médical ou de santé",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى الخدمات الصحية / الطبية",
        'display_name_ar-LB': "Consent to Release Information to Health/Medical Services",
        display_name_es: "Consent to Release Information to Health/Medical Services",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_health_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Health/Medical Name, Facility or Agency/Organization as applicable",
        display_name_fr: "Détailler le nom de l'organisation ou agence en charge du service médical ou de santé",
        display_name_ar: "حدد اسم الأخصائي الصحي/الطبي أو المنشأة أو المؤسسة الطبية حسب الاقتضاء",
        'display_name_ar-LB': "Specify Health/Medical Name, Facility or Agency/Organization as applicable",
        display_name_es: "Specify Health/Medical Name, Facility or Agency/Organization as applicable",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_safehouse",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Safe House/Shelter",
        display_name_fr: "Consentement pour partage d'information avec maison ou abris sûr",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى بيت آمن / مأوى",
        'display_name_ar-LB': "Consent to Release Information to Safe House/Shelter",
        display_name_es: "Consent to Release Information to Safe House/Shelter",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_safehouse_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Safe House/Shelter Name, Facility or Agency/Organization as applicable",
        display_name_fr: "Détailler le nom du  l'organisation ou agence pour services de maison ou abris sûr",
        display_name_ar: "حدد اسم البيت الآمن / المأوى أو المنشأة أو الهيئة أو المؤسسة المعنية حسب الاقتضاء",
        'display_name_ar-LB': "Specify Safe House/Shelter Name, Facility or Agency/Organization as applicable",
        display_name_es: "Specify Safe House/Shelter Name, Facility or Agency/Organization as applicable",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_legal",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Legal Assistance Services",
        display_name_fr: "Consentement pour partage d'information avec des services d'assistance juridique",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات المساعدة القانونية",
        'display_name_ar-LB': "Consent to Release Information to Legal Assistance Services",
        display_name_es: "Consent to Release Information to Legal Assistance Services",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_legal_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Legal Assistance Name, Facility or Agency/Organization as applicable",
        display_name_fr: "Détailler le nom de l'organisation ou agence en charge du service d'assistance juridique",
        display_name_ar: "حدد اسم أخصائي المساعدة القانونية أو الهيئة أو المؤسسة التي تقدم خدمات المساعدة القانونية حسب الاقتضاء",
        'display_name_ar-LB': "Specify Legal Assistance Name, Facility or Agency/Organization as applicable",
        display_name_es: "Specify Legal Assistance Name, Facility or Agency/Organization as applicable",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_protection",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Protection Services",
        display_name_fr: "Consentement pour partage d'information avec des services de protection",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات الحماية",
        'display_name_ar-LB': "Consent to Release Information to Protection Services",
        display_name_es: "Consent to Release Information to Protection Services",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_protection_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Protection Services Name, Facility or Agency/Organization as applicable",
        display_name_fr: "Détailler le nom de l'organisation ou agence en charge du service de protection",
        display_name_ar: "حدد اسم أخصائي خدمات الحماية أو الهيئة أو المؤسسة المعنية التي تقدم خدمات الحماية حسب الاقتضاء",
        'display_name_ar-LB': "Specify Protection Services Name, Facility or Agency/Organization as applicable",
        display_name_es: "Specify Protection Services Name, Facility or Agency/Organization as applicable",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_livelihoods",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Livelihoods Services",
        display_name_fr: "Consentement pour partage d'information avec des services en charge des moyens de subsistance",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات سبل العيش",
        'display_name_ar-LB': "Consent to Release Information to Livelihoods Services",
        display_name_es: "Consent to Release Information to Livelihoods Services",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_livelihoods_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Specify Livelihoods Services Name, Facility or Agency/Organization as applicable",
        display_name_fr: "Détailler le nom de l'organisation ou agence en charge des services moyens de subsistance",
        display_name_ar: "حدد اسم أخصائي خدمات سبل العيش أو الهيئة أو المؤسسة المعنية التي تقدم خدمات سبل العيش حسب الاقتضاء",
        'display_name_ar-LB': "Specify Livelihoods Services Name, Facility or Agency/Organization as applicable",
        display_name_es: "Specify Livelihoods Services Name, Facility or Agency/Organization as applicable",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Consent to Release Information to Other Services",
        display_name_fr: "Consentement pour partage d'information avec d'autres services",
        display_name_ar: "موافقة على الإفصاح عن معلومات إلى خدمات أخرى",
        'display_name_ar-LB': "Consent to Release Information to Other Services",
        display_name_es: "Consent to Release Information to Other Services",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "consent_to_share_info_by_other_details",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If other services, please specify service, name and agency",
        display_name_fr: "Pour d'autres services, veuillez détailler le nom de l'organisation ou agence en charge pour ce service",
        display_name_ar: "في حالة خدمات أخرى، يرجى تحديد اسم الأخصائي المعني أو المؤسسة المعنية بتقديم هذه الخدمات",
        'display_name_ar-LB': "If other services, please specify service, name and agency",
        display_name_es: "If other services, please specify service, name and agency",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

