FormSection.create_or_update!(
  {
    name_en: "Nested Incident Details Subform",
    description_en: "Nested Incident Details Subform",
    name_fr: "Nested Incident Details Subform",
    description_fr: "Nested Incident Details Subform",
    name_ar: "Nested Incident Details Subform",
    description_ar: "Nested Incident Details Subform",
    'name_ar-LB': "Nested Incident Details Subform",
    'description_ar-LB': "Nested Incident Details Subform",
    name_es: "Nested Incident Details Subform",
    description_es: "Nested Incident Details Subform",
    unique_id: "incident_details_subform_section",
    parent_form: "case",
    visible: false,
    order: 20,
    order_form_group: 110,
    order_subform: 1,
    form_group_keyed: false,
    editable: true,
    core_form: true,
    is_nested: true,
    is_first_tab: false,
    initial_subforms: 1,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    collapsed_field_names: [
      "cp_incident_violence_type",
      "incident_date"
    ],
    fields_attributes: [
      {
        name: "cp_incident_identification_violence",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Identification of Incident",
        display_name_fr: "Identification of Incident",
        display_name_ar: "Identification of Incident",
        'display_name_ar-LB': "Identification of Incident",
        display_name_es: "Identification of Incident",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-incident-identification",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_violence_header",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Incident",
        display_name_fr: "Incident",
        display_name_ar: "Incident",
        'display_name_ar-LB': "Incident",
        display_name_es: "Incident",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "incident_date",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of Incident",
        display_name_fr: "Date of Incident",
        display_name_ar: "Date of Incident",
        'display_name_ar-LB': "Date of Incident",
        display_name_es: "Date of Incident",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_location_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Area of the Incident",
        display_name_fr: "Area of the Incident",
        display_name_ar: "Area of the Incident",
        'display_name_ar-LB': "Area of the Incident",
        display_name_es: "Area of the Incident",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-incident-location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_location_type_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If 'Other', please specify",
        display_name_fr: "If 'Other', please specify",
        display_name_ar: "If 'Other', please specify",
        'display_name_ar-LB': "If 'Other', please specify",
        display_name_es: "If 'Other', please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "incident_location",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Location of the Incident",
        display_name_fr: "Location of the Incident",
        display_name_ar: "Location of the Incident",
        'display_name_ar-LB': "Location of the Incident",
        display_name_es: "Location of the Incident",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_timeofday",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Time of Incident",
        display_name_fr: "Time of Incident",
        display_name_ar: "Time of Incident",
        'display_name_ar-LB': "Time of Incident",
        display_name_es: "Time of Incident",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-time-of-day",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_timeofday_actual",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Please specify the actual time of the Incident",
        display_name_fr: "Please specify the actual time of the Incident",
        display_name_ar: "Please specify the actual time of the Incident",
        'display_name_ar-LB': "Please specify the actual time of the Incident",
        display_name_es: "Please specify the actual time of the Incident",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_violence_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Type of Violence",
        display_name_fr: "Type of Violence",
        display_name_ar: "Type of Violence",
        'display_name_ar-LB': "Type of Violence",
        display_name_es: "Type of Violence",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-cp-violence-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_previous_incidents",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Has the case been previously abused?",
        display_name_fr: "Has the case been previously abused?",
        display_name_ar: "Has the case been previously abused?",
        'display_name_ar-LB': "Has the case been previously abused?",
        display_name_es: "Has the case been previously abused?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_previous_incidents_description",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If yes please describe in brief",
        display_name_fr: "If yes please describe in brief",
        display_name_ar: "If yes please describe in brief",
        'display_name_ar-LB': "If yes please describe in brief",
        display_name_es: "If yes please describe in brief",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_abuser_header",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Perpetrator information",
        display_name_fr: "Perpetrator information",
        display_name_ar: "Perpetrator information",
        'display_name_ar-LB': "Perpetrator information",
        display_name_es: "Perpetrator information",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_abuser_name",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Name",
        display_name_fr: "Name",
        display_name_ar: "Name",
        'display_name_ar-LB': "Name",
        display_name_es: "Name",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_nationality",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Nationality",
        display_name_fr: "Nationality",
        display_name_ar: "Nationality",
        'display_name_ar-LB': "Nationality",
        display_name_es: "Nationality",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-country",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "perpetrator_sex",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Sex",
        display_name_fr: "Sex",
        display_name_ar: "Sex",
        'display_name_ar-LB': "Sex",
        display_name_es: "Sex",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-gender",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_date_of_birth",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of Birth",
        display_name_fr: "Date of Birth",
        display_name_ar: "Date of Birth",
        'display_name_ar-LB': "Date of Birth",
        display_name_es: "Date of Birth",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_age",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Age",
        display_name_fr: "Age",
        display_name_ar: "Age",
        'display_name_ar-LB': "Age",
        display_name_es: "Age",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_national_id_no",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "National ID Number",
        display_name_fr: "National ID Number",
        display_name_ar: "National ID Number",
        'display_name_ar-LB': "National ID Number",
        display_name_es: "National ID Number",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_other_id_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Type of Other ID Document",
        display_name_fr: "Type of Other ID Document",
        display_name_ar: "Type of Other ID Document",
        'display_name_ar-LB': "Type of Other ID Document",
        display_name_es: "Type of Other ID Document",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_other_id_no",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Number of Other ID Document",
        display_name_fr: "Number of Other ID Document",
        display_name_ar: "Number of Other ID Document",
        'display_name_ar-LB': "Number of Other ID Document",
        display_name_es: "Number of Other ID Document",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_marital_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Social Status",
        display_name_fr: "Social Status",
        display_name_ar: "Social Status",
        'display_name_ar-LB': "Social Status",
        display_name_es: "Social Status",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-marital-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_mobile_phone",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Mobile Phone",
        display_name_fr: "Mobile Phone",
        display_name_ar: "Mobile Phone",
        'display_name_ar-LB': "Mobile Phone",
        display_name_es: "Mobile Phone",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_phone",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Land Phone",
        display_name_fr: "Land Phone",
        display_name_ar: "Land Phone",
        'display_name_ar-LB': "Land Phone",
        display_name_es: "Land Phone",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_address",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Address",
        display_name_fr: "Address",
        display_name_ar: "Address",
        'display_name_ar-LB': "Address",
        display_name_es: "Address",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_occupation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Occupation",
        display_name_fr: "Occupation",
        display_name_ar: "Occupation",
        'display_name_ar-LB': "Occupation",
        display_name_es: "Occupation",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_relationship",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Relationship with the victim",
        display_name_fr: "Relationship with the victim",
        display_name_ar: "Relationship with the victim",
        'display_name_ar-LB': "Relationship with the victim",
        display_name_es: "Relationship with the victim",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-perpetrator-relationship",
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

FormSection.create_or_update!(
  {
    name_en: "Incident Details",
    description_en: "Incident details information about a child.",
    name_fr: "Incident Details",
    description_fr: "Incident details information about a child.",
    name_ar: "Incident Details",
    description_ar: "Incident details information about a child.",
    'name_ar-LB': "Incident Details",
    'description_ar-LB': "Incident details information about a child.",
    name_es: "Incident Details",
    description_es: "Incident details information about a child.",
    unique_id: "incident_details_container",
    parent_form: "case",
    visible: false,
    order: 0,
    order_form_group: 30,
    order_subform: 0,
    form_group_keyed: false,
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    form_group_id: "identification_registration",
    fields_attributes: [
      {
        name: "incident_details",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "subform",
        editable: true,
        disabled: false,
        display_name_en: "Incident Details",
        display_name_fr: "Incident Details",
        display_name_ar: "Incident Details",
        'display_name_ar-LB': "Incident Details",
        display_name_es: "Incident Details",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        subform_sort_by: "summary_date",
        required: false,
        subform_unique_id: "incident_details_subform_section"
      }
    ]
  }
)

