# frozen_string_literal: true

perpetrator_subform_fields = [
  Field.new(
    'mobile_visible' => true,
    'required' => true,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'name' => 'violations_ids',
    'type' => 'select_box',
    'multi_select' => true,
    'display_name_en' => 'Violation(s) for which the perpetrator is allegedly responsible',
    'option_strings_source' => 'violations',
    'guiding_questions_en' => 'The MRM remains distinct from criminal investigations and the legal responsibility of an alleged perpetrator can only be established by a court of law. However, it is helpful to do all feasible efforts - with due consideration for the protection and confidentiality of victims, witnesses, sources and MRM monitors - to attribute incidents of grave violations against children to a specific perpetrator.'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_category',
    'type' => 'select_box',
    'display_name_en' => 'Type of perpetrator',
    'option_strings_source' => 'lookup lookup-perpetrator-category-type',
    'guiding_questions_en' => "Armed force: Includes police, intelligence and other Governmental security forces, provided that they can be characterized as parties to the conflict. Also includes pro-Government militias that operate under the Government's command and control.  Armed group: Includes pro-Government militias that are not formally under the Government's command and control.  Other party to the conflict: Includes international forces, whether United Nations (UN) or non-UN-mandated.  Unknown: Even when the perpetrator is unknown, the CTFMR needs to be satisified that the violation was perpetrated by a party to the conflict, and thus conflict-related",
    'help_text_en' => 'This field is mandatory'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_sub_category',
    'type' => 'select_box',
    'display_name_en' => 'To which type of armed force or group did the alleged perpetrator(s) belong?',
    'option_strings_source' => 'lookup lookup-armed-force-group-type',
    'visible' => false
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'armed_force_group_party_name',
    'type' => 'select_box',
    'display_name_en' => 'To which armed force, group, or other party did the perpetrator belong?',
    'option_strings_source' => 'lookup lookup-armed-force-group-or-other-party',
    'guiding_questions_en' => 'CTFMRs should ensure that the lists of perpetrators in the MRM IMS are as comprehensive and up-to-date as possible. In case new parties need to be added to the list, or should an armed force change its name, please contact the MRM Technical Reference Group.',
    'option_strings_condition' => {
      'armed-force' => { 'eq' => { 'perpetrator_category' => 'armed_force' } },
      'armed-group' => { 'eq' => { 'perpetrator_category' => 'armed_group' } },
      'other-party' => { 'eq' => { 'perpetrator_category' => 'other_party_to_the_conflict' } }
    }
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => false,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'armed_force_name',
    'type' => 'select_box',
    'display_name_en' => 'If armed force, please select as appropriate',
    'option_strings_source' => 'lookup lookup-armed-force-name',
    'guiding_questions_en' => 'CTFMRs should ensure that the lists of perpetrators in the MRM IMS are as comprehensive and up-to-date as possible. In case new parties need to be added to the list, or should an armed force change its name, please contact the MRM Technical Reference Group.'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => false,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'armed_group_name',
    'type' => 'select_box',
    'display_name_en' => 'If armed group, please select as appropriate',
    'option_strings_source' => 'lookup lookup-armed-group-name',
    'guiding_questions_en' => 'CTFMRs should ensure that the lists of perpetrators in the MRM IMS are as comprehensive and up-to-date as possible. In case new parties need to be added to the list, or should an armed group change its name or fragment into multiple groups, please contact the MRM Technical Reference Group.'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => false,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'other_party_name',
    'type' => 'select_box',
    'display_name_en' => 'If other party to the conflict, please select as appropriate',
    'option_strings_source' => 'lookup lookup-other-party-name',
    'guiding_questions_en' => 'CTFMRs should ensure that the lists of perpetrators in the MRM IMS are as comprehensive and up-to-date as possible. In case new parties need to be added to the list, please contact the MRM Technical Reference Group.'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_number',
    'type' => 'numeric_field',
    'display_name_en' => 'Number of individual perpetrators within the group perpetrator (if known)'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_number_estimate',
    'type' => 'tick_box',
    'tick_box_label_en' => 'Yes',
    'display_name_en' => 'Is this number estimated?'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_children',
    'type' => 'select_box',
    'display_name_en' => 'Did the group of perpetrators include children?',
    'option_strings_source' => 'lookup lookup-yes-no-unknown',
    'help_text_en' => "If yes, this should be reflected in the 'Recruitment and use' form."
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_children_number',
    'type' => 'numeric_field',
    'display_name_en' => 'If so, how many? (if known)'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_children_number_estimate',
    'type' => 'tick_box',
    'tick_box_label_en' => 'Yes',
    'display_name_en' => 'Is this number estimated? '
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_sex',
    'type' => 'select_box',
    'display_name_en' => 'Sex of the perpetrator',
    'option_strings_source' => 'lookup lookup-gender-mixed'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'name' => 'perpetrator_nationality',
    'type' => 'select_box',
    'multi_select' => true,
    'display_name_en' => 'Nationality of the perpetrator',
    'option_strings_source' => 'lookup lookup-nationality'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'name' => 'perpetrator_ethnicity',
    'type' => 'select_box',
    'multi_select' => true,
    'display_name_en' => 'Ethnicity of the perpetrator',
    'option_strings_source' => 'lookup lookup-ethnicity'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'name_perpetrator',
    'type' => 'textarea',
    'display_name_en' => 'Name/nickname of the perpetrator(s)'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'rank_perpetrator',
    'type' => 'text_field',
    'display_name_en' => 'Rank of the perpetrator'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_arrest',
    'type' => 'select_box',
    'display_name_en' => 'Was the perpetrator arrested?',
    'option_strings_source' => 'lookup lookup-yes-no-unknown'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'arrest_details',
    'type' => 'textarea',
    'display_name_en' => 'Please provide additional details'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_detention',
    'type' => 'select_box',
    'display_name_en' => 'Was the perpetrator detained?',
    'option_strings_source' => 'lookup lookup-yes-no-unknown'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'details_detention',
    'type' => 'textarea',
    'display_name_en' => 'Please provide additional details '
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_conviction',
    'type' => 'select_box',
    'display_name_en' => 'Was the perpetrator convicted?',
    'option_strings_source' => 'lookup lookup-yes-no-unknown'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'details_conviction',
    'type' => 'textarea',
    'display_name_en' => 'Please provide additional details  '
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_additional_details',
    'type' => 'textarea',
    'display_name_en' => 'Additional details',
    'help_text_en' => 'E.g. chain of command; information on specific unit/role of the perpetrator; type of uniform worn; consistency between the way in which the violations were committed and the modus operandi of the group; specific details on individual perpetrator(s), if known e.g. name, sex, age, nationality, ethnicity, language(s) spoken, rank; apparent role of command'
  ),
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'editable' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrator_verified',
    'type' => 'radio_button',
    'display_name_en' => 'Is this perpetrator verified for MRM purposes?',
    'guiding_questions_en' => 'The MRM remains distinct from criminal investigations and the legal responsibility of an alleged perpetrator can only be established by a court of law. However, it is helpful to do all feasible efforts - with due consideration for the protection and confidentiality of victims, witnesses, sources and MRM monitors - to attribute incidents of grave violations against children to a specific perpetrator. When all other elements of an incident are verified  except for the attribution to a perpetrator - which may prove difficult for a variety of reasons -  the said incident may be considered verified even if the perpetrator is alleged.',
    'option_strings_source' => 'lookup lookup-yes-no'
  )
]

perpetrator_subform = FormSection.create_or_update!(
  name_en: 'Nested Perpetrator Subform',
  fields: perpetrator_subform_fields,
  description_en: 'Nested Perpetrator Subform',
  unique_id: 'perpetrator_subform_section',
  parent_form: 'incident',
  visible: false,
  order: 10,
  order_form_group: 80,
  order_subform: 1,
  editable: true,
  core_form: true,
  is_nested: true,
  is_first_tab: false,
  initial_subforms: 1,
  collapsed_field_names: ['perpetrator_category', 'armed_force_group_party_name'],
  mobile_form: false,
  subform_append_only: false
)

perpetrator_fields = [
  Field.new(
    'mobile_visible' => true,
    'required' => false,
    'show_on_minify_form' => false,
    'hidden_text_field' => false,
    'autosum_total' => false,
    'autosum_group' => '',
    'hide_on_view_page' => false,
    'visible' => true,
    'disabled' => false,
    'multi_select' => false,
    'name' => 'perpetrators',
    'type' => 'subform',
    'editable' => true,
    'subform_section' => perpetrator_subform,
    'collapse' => 'expanded',
    'display_name_en' => 'Perpetrator'
  )
]

FormSection.create_or_update!(
  name_en: 'Perpetrator(s)',
  fields: perpetrator_fields,
  description_en: 'Perpetrator(s)',
  unique_id: 'perpetrators',
  parent_form: 'incident',
  visible: true,
  order: 20,
  order_form_group: 80,
  order_subform: 0,
  editable: true,
  core_form: true,
  is_first_tab: false,
  initial_subforms: 0,
  mobile_form: false,
  form_group_id: 'additional_details'
)
