FormSection.create_or_update!(
  {
    name_en: "Protection Concerns",
    description_en: "Protection concerns",
    'name_ar-IQ': "شؤون الحماية",
    'description_ar-IQ': "شؤون الحماية",
    name_ku: "نیگەرانیەکانى پاراستن",
    description_ku: "نیگەرانیەکانى پاراستن",
    unique_id: "protection_concern",
    parent_form: "case",
    visible: true,
    order: 20,
    order_form_group: 30,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "identification_registration",
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "protection_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Separation Status",
        'display_name_ar-IQ': "حالة الانفصال",
        display_name_ku: "دۆخی جیابونەوە",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-protection-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "non_uasc_protection_explanation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If child is not UASC but needs tracing as a protection, provide brief explanation",
        'display_name_ar-IQ': "إذا كان الطفل ليس من الاطفال المنفصلين او غير المصحوبين ولكنه يحتاج إلى تتبع كحماية ، قدم شرحًا موجزًا",
        display_name_ku: "ئەگەر مندالەکە UASC نەبێت بەلام پێویستى بە بەدواداچوونى پاراستن بێت، بە کورتى رونبکەرەوە",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "urgent_protection_concern",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Urgent Protection Concern?",
        'display_name_ar-IQ': "شؤون الحماية الطارئة",
        display_name_ku: "نیگەرانى  پاراستنى پێویست؟",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "risk_level",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Risk Level",
        help_text_en: "If you change the risk level from the original risk level (from Registration / Assessment phase), please record the original risk level in the field below.",
        'display_name_ar-IQ': "مستوى الخطورة",
        'help_text_ar-IQ': "إذا قمت بتغيير مستوى الخطورة من مستوى الخطورة الأصلي (من مرحلة التسجيل / التقييم) ، يرجى تسجيل مستوى الخطورة الأصلي في الحقل أدناه.",
        display_name_ku: "ئاستى مەترسى",
        help_text_ku: "ئه گه ر ئاستى مەترسى بگوريت له ئاستى مەترسى بنه ره تي (دياركردن /توماركردن) تكاية توماركردنئ ئاستى مەترسى بنه ره تي له فیلدئ خوارەوە",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-risk-level",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "risk_level_previous",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Original Risk Level (From Registration / Assessment Phase)",
        'display_name_ar-IQ': "مستوى الخطورة الاصلي ( من مرحلة التسجيل / التقييم)",
        display_name_ku: "ئاستى مەترسى بنه ره تي (دياركردن /توماركردن)",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-risk-level",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "displacement_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Population group",
        'display_name_ar-IQ': "المجموعة السكانية",
        display_name_ku: "گروپى دانشتوان",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-displacement-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "unhcr_protection_code",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "UNHCR Protection Code",
        help_text_en: "This field is deprecated in v1.2 and replaced by unchr_needs_code",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "protection_concerns",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Protection Concerns",
        'display_name_ar-IQ': "شؤون لحماية",
        display_name_ku: "نیگەرانیەکانى پاراستن",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-protection-concerns",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "protection_concerns_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        'display_name_ar-IQ': "اذا كانت اخرى, حد رجاء",
        display_name_ku: "ئەگەر ئەویتر، تکایە رونبکەوە",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "unhcr_needs_codes",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "UNHCR Needs Codes",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-unhcr-needs-codes",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "disability_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Disability Type",
        'display_name_ar-IQ': "نوع الاعاقة",
        display_name_ku: "جۆرى کەمئەندامی",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-disability-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

