# frozen_string_literal: true

gbv_follow_up_subform_section_fields = [
  Field.new(name: 'followup_date',
            show_on_minify_form: true,
            mobile_visible: true,
            type: 'date_field',
            display_name_en: 'Date of follow up session'),
  Field.new(name: 'service_type_provided',
            show_on_minify_form: true,
            mobile_visible: true,
            type: 'select_box',
            display_name_en: 'Type of service provided by me/my organization',
            'option_strings_source' => 'lookup lookup-gbv-service-type'),
  Field.new(name: 'follow_up_comments',
            type: 'textarea',
            display_name_en: 'Comments',
            'help_text_en' => 'What did the survivor tell you? What additional needs '\
                                'does she have? What challenges did you face in the '\
                                'follow up session (e.g. survivors did not present)?'),
  Field.new(name: 'need_follow_up_visit',
            type: 'radio_button',
            display_name_en: 'Is there a need for further follow up visits?',
            'option_strings_source' => 'lookup lookup-yes-no'),
  Field.new(name: 'when_follow_up_visit_should_happen',
            type: 'date_field',
            display_name_en: 'If yes, when do you recommend the next visit to take place?',
            display_conditions_subform: { 'eq' => { 'need_follow_up_visit' => 'true' } }),
  Field.new(name: 'follow_up_survivor_share_needs',
            type: 'radio_button',
            display_name_en: 'Did the survivor share any new needs or concerns during the follow up appointment?',
            option_strings_source: 'lookup lookup-yes-no'),
  Field.new(name: 'follow_up_survivor_share_needs_text',
            mobile_visible: true,
            type: 'text_field',
            display_name_en: 'If yes, please describe the needs and revise the Case Action Plan section accordingly',
            display_conditions_subform: { 'eq' => { 'follow_up_survivor_share_needs' => 'true' } }),
  Field.new(name: 'recommend_case_closed',
            mobile_visible: false,
            type: 'radio_button',
            display_name_en: 'If needs are met, do you recommend that the case be closed?',
            option_strings_source: 'lookup lookup-yes-no-not-applicable-needs-not-met'),
  Field.new(name: 'case_action_plan_implementation_timing',
            mobile_visible: true,
            show_on_minify_form: true,
            type: 'select_box',
            display_name_en: 'How long did it take you to implement the Case Action Plan for this incident?',
            'option_strings_source' => 'lookup lookup-assessment-duration'),
  Field.new(name: 'progress_made_towards_goals',
            mobile_visible: true,
            type: 'separator',
            display_name_en: 'Progress made towards goals',
            'help_text_en' => 'Evaluate Progress Made Towards goals agreed on in Survivor Assessment & Case Action Plan'),
  Field.new(name: 'gbv_assessment_progress_safety',
            mobile_visible: true,
            type: 'radio_button',
            display_name_en: 'Progress towards Safety goals',
            'option_strings_source' => 'lookup lookup-assessment-progress'),
  Field.new(name: 'gbv_assessment_progress_safety_text',
            mobile_visible: true,
            type: 'textarea',
            display_name_en: 'Explain Progress towards Safety goals'),
  Field.new(name: 'gbv_assessment_progress_health',
            mobile_visible: true,
            type: 'radio_button',
            display_name_en: 'Progress towards Heath care goals',
            'option_strings_source' => 'lookup lookup-assessment-progress'),
  Field.new(name: 'gbv_assessment_progress_health_text',
            mobile_visible: true,
            type: 'textarea',
            display_name_en: 'Explain Progress towards Heath care goals'),
  Field.new(name: 'gbv_assessment_progress_psychosocial',
            mobile_visible: true,
            type: 'radio_button',
            display_name_en: 'Progress towards Psychosocial Support goals',
            'option_strings_source' => 'lookup lookup-assessment-progress'),
  Field.new(name: 'gbv_assessment_progress_psychosocial_text',
            mobile_visible: true,
            type: 'textarea',
            display_name_en: 'Explain Progress towards Psychosocial Support goals'),
  Field.new(name: 'gbv_assessment_progress_justice',
            mobile_visible: true,
            type: 'radio_button',
            display_name_en: 'Progress towards Justice/legal goals',
            'option_strings_source' => 'lookup lookup-assessment-progress'),
  Field.new(name: 'gbv_assessment_progress_justice_text',
            mobile_visible: true,
            type: 'textarea',
            display_name_en: 'Explain Progress towards Access to Justice/legal goals'),
  Field.new(name: 'gbv_assessment_other_goals_list',
            mobile_visible: true,
            type: 'textarea',
            display_name_en: 'Other goals (list here)'),
  Field.new(name: 'gbv_assessment_other_goals',
            mobile_visible: true,
            type: 'radio_button',
            display_name_en: 'Progress towards other goals',
            'option_strings_source' => 'lookup lookup-assessment-progress'),
  Field.new(name: 'gbv_assessment_other_goals_text',
            mobile_visible: true,
            type: 'textarea',
            display_name_en: 'Explain Progress towards other goals')
]

gbv_follow_up_subform_section = FormSection.create_or_update!(
  visible: false,
  is_nested: true,
  order_form_group: 60,
  order: 10,
  order_subform: 1,
  unique_id: 'gbv_follow_up_subform_section',
  parent_form: 'case',
  fields: gbv_follow_up_subform_section_fields,
  editable: true,
  initial_subforms: 0,
  mobile_form: true,
  name_en: 'Nested GBV Follow Up Subform',
  description_en: 'Nested GBV Follow Up Subform',
  collapsed_field_names: %w[followup_service_type followup_date]
)

action_plan_subform_section_fields = [
  Field.new(
    name: 'service_type',
    mandatory_for_completion: true,
    mobile_visible: true,
    type: 'select_box',
    display_name_en: 'Type of Need',
    'option_strings_source' => 'lookup lookup-gbv-service-type'
  ),
  Field.new(
    name: 'action_plan_description',
    show_on_minify_form: true,
    mobile_visible: true,
    type: 'textarea',
    display_name_en: 'Describe the action plan to address this need'
  ),
  Field.new(
    name: 'service_intervertion_type',
    mobile_visible: true,
    type: 'select_box',
    display_name_en: 'Type of Intervention',
    'option_strings_source' => 'lookup lookup-gbv-intervention-type'
  ),
  Field.new(
    name: 'service_referral',
    mandatory_for_completion: true,
    mobile_visible: true,
    type: 'select_box',
    display_name_en: 'How will the survivor access this service',
    'option_strings_source' => 'lookup lookup-service-referred'
  ),
  Field.new(
    name: 'service_referral_written_consent',
    mandatory_for_completion: true,
    mobile_visible: true,
    show_on_minify_form: true,
    type: 'radio_button',
    display_name_en: 'Did you receive informed consent from survivor to release personal Information for the purpose' \
                     ' of referrals?',
    'option_strings_source' => 'lookup lookup-yes-no'
  ),
  Field.new(
    name: 'service_referral_name',
    mobile_visible: true,
    type: 'text_field',
    display_name_en: 'Specify Name, Facility or Agency/Organization as applicable'
  ),
  Field.new(
    name: 'service_appointment_date',
    mobile_visible: true,
    type: 'date_field',
    display_name_en: 'Appointment Date'
  ),
  Field.new(
    name: 'service_appointment_time',
    mobile_visible: false,
    type: 'text_field',
    display_name_en: 'Appointment Time'
  ),
  Field.new(
    name: 'service_provider',
    mobile_visible: true,
    type: 'text_field',
    display_name_en: 'Service Provider'
  ),
  Field.new(
    name: 'service_location',
    mobile_visible: false,
    type: 'text_field',
    display_name_en: 'Service Location'
  ),
  Field.new(
    name: 'service_referral_notes',
    mobile_visible: false,
    type: 'textarea',
    display_name_en: 'Notes',
    'help_text_en' => 'Highlight challenges, resources and other relevant considerations'
  ),
  Field.new(
    name: 'service_referral_mandatory_reporting',
    type: 'radio_button',
    display_name_en: 'If mandatory reporting laws apply, did you report the incident to the police/public authorities?',
    'option_strings_source' => 'lookup lookup-yes-no-not-applicable'
  ),
  Field.new(
    name: 'service_referral_mandatory_reporting_inform_survivor',
    type: 'radio_button',
    display_name_en: 'If yes, did you inform the survivor and/or her caregiver of the mandatory reporting laws prior to making the report?',
    'option_strings_source' => 'lookup lookup-yes-no-not-applicable',
    display_conditions_subform: { 'eq' => { 'service_referral_mandatory_reporting' => 'true' } }
  ),
  Field.new(
    name: 'service_provided',
    type: 'radio_button',
    display_name_en: 'Was the service provided?',
    'option_strings_source' => 'lookup lookup-yes-no-not-applicable'
  ),
  Field.new(
    name: 'service_provided_date',
    type: 'date_field',
    display_name_en: 'If yes, when was the service provided?',
    display_conditions_subform: { 'eq' => { 'service_provided' => 'true' } }
  ),
  Field.new(
    name: 'action_taken_details',
    mobile_visible: true,
    type: 'textarea',
    display_name_en: 'Details about action taken'
  )
]

action_plan_subform_section = FormSection.create_or_update!(
  visible: false,
  is_nested: true,
  mobile_form: true,
  order_form_group: 60,
  order: 50,
  order_subform: 1,
  unique_id: 'action_plan_subform_section',
  parent_form: 'case',
  fields: action_plan_subform_section_fields,
  editable: true,
  initial_subforms: 0,
  name_en: 'Nested Action Plan',
  description_en: 'Action Plan Subform',
  collapsed_field_names: %w[service_type service_appointment_date]
)

action_plan_form_fields = [
  Field.new(name: 'action_plan_approved',
            type: 'tick_box',
            tick_box_label_en: 'Yes',
            editable: false,
            disabled: true,
            display_name_en: 'Approved by Manager'),
  Field.new(name: 'action_plan_approved_date',
            type: 'date_field',
            editable: false,
            disabled: true,
            display_name_en: 'Date'),
  Field.new(name: 'action_plan_approved_comments',
            type: 'textarea',
            editable: false,
            disabled: true,
            display_name_en: 'Manager Comments'),
  Field.new(name: 'approval_status_action_plan',
            type: 'select_box',
            display_name_en: 'Approval Status',
            editable: false,
            disabled: true,
            option_strings_source: 'lookup lookup-approval-status'),
  Field.new(name: 'action_explanation_header',
            show_on_minify_form: true,
            mobile_visible: true,
            type: 'separator',
            display_name_en: 'Actions ', # Note the extra trailing space!
            'help_text_en' => 'Please add all needs that you identified in the assessment. Use the Add button to add other needs that should be part of the Action Plan.'),
  Field.new(name: 'action_plan_section',
            show_on_minify_form: true,
            mobile_visible: true,
            type: 'subform', 'editable' => true,
            'subform_section' => action_plan_subform_section,
            display_name_en: 'Actions'),
  Field.new(name: 'service_referral_case_action_plan_timing',
            mobile_visible: true,
            show_on_minify_form: true,
            type: 'select_box',
            display_name_en: 'How long did it take you to develop the Case Action Plan with the survivor for this case?',
            'option_strings_source' => 'lookup lookup-assessment-duration'),
  Field.new(name: 'action_follow_up_header',
            show_on_minify_form: true,
            mobile_visible: true,
            type: 'separator',
            display_name_en: 'Follow Ups'),
  Field.new(name: 'gbv_follow_up_subform_section',
            show_on_minify_form: true,
            mobile_visible: true,
            type: 'subform', 'editable' => true,
            'subform_section' => gbv_follow_up_subform_section,
            display_name_en: 'Follow Up')
]

action_plan_form = FormSection.create_or_update!(
  unique_id: 'action_plan_form',
  parent_form: 'case',
  visible: true,
  order_form_group: 60,
  order: 0,
  form_group_id: 'action_plan',
  fields: action_plan_form_fields,
  is_first_tab: false,
  editable: true,
  mobile_form: true,
  name_en: 'Action Plan',
  description_en: 'Action Plan'
)
