# frozen_string_literal: true

case_plan_fields_subform = [
  Field.new(name: 'intervention_service_to_be_provided',
            type: 'text_field',
            display_name_en: 'Name of intervention / service to be provided',
            visible: false),
  Field.new(name: 'intervention_service_to_be_provided_lookup',
            type: 'select_box',
            display_name_en: 'Name of intervention / service to be provided',
            option_strings_source:"lookup lookup-interventions-type"),
  Field.new(name: 'case_plan_provider_and_contact_details',
            type: 'textarea',
            display_name_en: 'Person / agency providing the service or implementing the intervention / services and contact details'),
  Field.new(name: 'intervention_service_goal',
            type: 'textarea',
            display_name_en: 'Tasks associated with the intervention / service'),
  Field.new(name: 'case_plan_timeframe',
            type: 'date_field',
            display_name_en: 'Expected timeframe (end date)'),
  Field.new(name: 'case_plan_monitoring_schedule',
            type: 'select_box',
            display_name_en: 'Follow up / monitoring schedule',
            option_strings_text_en: [
              { id: 'one_time', display_text: 'One time' },
              { id: 'daily', display_text: 'Daily' },
              { id: 'weekly', display_text: 'Weekly' },
              { id: 'monthly', display_text: 'Monthly' },
              { id: 'other', display_text: 'Other' }
            ].map(&:with_indifferent_access)),
  Field.new(name: 'intervention_service_success',
            type: 'radio_button',
            display_name_en: 'Successfully implemented?',
            option_strings_source: 'lookup lookup-yes-no',
            visible: false)
]

case_plan_section = FormSection.create_or_update!(
  visible: false,
  is_nested: true,
  order_form_group: 999,
  order: 999,
  order_subform: 1,
  unique_id: 'cp_case_plan_subform_case_plan_interventions',
  parent_form: 'case',
  editable: true,
  fields: case_plan_fields_subform,
  initial_subforms: 0,
  name_en: 'List of Interventions and Services',
  description_en: 'List of Interventions and Services',
  collapsed_field_names: ['case_plan_timeframe', 'intervention_service_to_be_provided_lookup']
)

care_plan_fields_subform = [
  Field.new(name: 'care_plan_domain',
            type: 'select_box',
            display_name_en: 'Care Plan Domain',
            option_strings_source: 'lookup lookup-care-plan-domains',
            help_text_en: "All domains must be completed.",
            guiding_questions_en: [
              "Health and Physical Development:  include dental, hearing, eyesight, and general physical and mental health. Note that for clients entering alternative care, a complete health assessment is a compulsory part of the care plan.",
              "Educational and Life Skills Development: include activities outside schooling, such as tutoring and evening classes. Note that this domain must be fully completed for a client who is 16 years or older, and/or two years before leaving care to live independently (or semi-independently).",
              "Pyschosocial Development: include impact of any abuse/neglect.",
              "Integration into the Family: include siblings, extended family and other significant relationships.",
              "Integration into the Community: include level of active participation in social/community life.",
            ].join("\n")),
  Field.new(name: 'care_plan_action',
            type: 'select_box',
            display_name_en: 'Has any action been planned for this domain?',
            option_strings_source: 'lookup lookup-care-plan-actions',
            guiding_questions_en: "Issues or concerns and strengths can still be noted in the following fields, as well as measures already in place, even if no current action is planned."),
  Field.new(name: 'care_plan_issues',
            type: 'textarea',
            display_name_en: 'Issue or concern about the client',
            help_text_en: "Enter up to five issues for this domain.",
            guiding_questions_en: "Issue or concern related to this domain for the child or young person named on the plan, e.g. child has several unplanned placement changes and needs stability (placement and permanency) or young person has not attended school this year (education or vocation)."),
  Field.new(name: 'care_plan_strength',
            type: 'textarea',
            display_name_en: 'Strength',
            guiding_questions_en: "Strength related to this domain for the child or young person named on the plan, e.g. child is in good health (health and medical) or young person has a good relationship with maternal aunt (family relationships)."),
  Field.new(name: 'care_plan_objectives',
            type: 'textarea',
            display_name_en: 'Objectives',
            help_text_en: "Enter up to five objectives for this domain."),
  Field.new(name: 'care_plan_tasks',
            type: 'textarea',
            display_name_en: 'Actions & tasks',
            help_text_en: "Clearly state actions and tasks required to meet the objective. "),
  Field.new(name: 'care_plan_responsibility',
            type: 'textarea',
            display_name_en: 'Responsibility',
            help_text_en: "Name the person or organisation responsible for doing the action or task."),
  Field.new(name: 'care_plan_domain_timeframe',
            type: 'date_field',
            display_name_en: 'Time frame',
            guiding_questions_en: [
              "For the placement and permanency domain, the time frames for reintegration or another permanency arrangement must be within the shortest time possible.",
              "For other domains, the time frame section should give the due date by which this action is expected to be done (the estimated time frame), even if there is no foreseeable end date at the time of planning."
            ].join("\n")),
]
care_plan_section = FormSection.create_or_update!(
  visible: false,
  is_nested: true,
  order_form_group: 999,
  order: 999,
  order_subform: 1,
  unique_id: 'cp_case_plan_subform_care_plan',
  parent_form: 'case',
  editable: true,
  fields: care_plan_fields_subform,
  initial_subforms: 0,
  name_en: 'Care Plan Domain',
  description_en: 'Care Plan Domain',
  collapsed_field_names: ['care_plan_domain', 'care_plan_action']
)

case_plan_fields = [
  Field.new(name: 'case_plan_approval_type',
            type: 'select_box',
            display_name_en: 'Approval Type',
            editable: false,
            disabled: true,
            option_strings_source: 'lookup lookup-approval-type'),
  Field.new(name: 'case_plan_approved',
            type: 'tick_box',
            tick_box_label_en: 'Yes',
            editable: false,
            disabled: true,
            display_name_en: 'Approved by Manager'),
  Field.new(name: 'case_plan_approved_date',
            type: 'date_field',
            editable: false,
            disabled: true,
            display_name_en: 'Date'),
  Field.new(name: 'case_plan_approved_comments',
            type: 'textarea',
            editable: false,
            disabled: true,
            display_name_en: 'Manager Comments'),
  Field.new(name: 'approval_status_case_plan',
            type: 'select_box',
            display_name_en: 'Approval Status',
            editable: false,
            disabled: true,
            option_strings_source: 'lookup lookup-approval-status'),
  Field.new(name: 'case_plan_section_header',
            type: 'separator',
            display_name_en: 'Case Plan Developed and Participants Involved'),
  Field.new(name: 'date_case_plan',
            type: 'date_field',
            display_name_en: 'Date Case Plan Initiated',
            editable: true,
            disabled: false,
            help_text_en: 'This field is used for the Workflow status'),
  Field.new(name: 'case_plan_target_review_date',
            type: 'date_field',
            display_name_en: 'Target Review Date'),
  Field.new(name: 'protection_concerns',
            type: 'select_box',
            display_name_en: 'Protection Concerns',
            multi_select: true,
            option_strings_source: 'lookup lookup-protection-concerns',
            visible: false),
  Field.new(name: 'interventions_child_involved',
            type: 'radio_button',
            display_name_en: 'Was the client involved in developing the case plan?',
            option_strings_source: 'lookup lookup-yes-no'),
  Field.new(name: 'interventions_child_involved_explanation',
            type: 'textarea',
            display_name_en: 'If No, explain why not.'),
  Field.new(name: 'interventions_child_agrees',
            type: 'radio_button',
            display_name_en: 'Does the client understand and agree to the Case Plan?',
            option_strings_source: 'lookup lookup-yes-no'),
  Field.new(name: 'interventions_child_agrees_explanation',
            type: 'textarea',
            display_name_en: 'If No, explain why not.'),
  Field.new(name: 'interventions_names_involved',
            type: 'textarea',
            display_name_en: 'Names and relation to client of persons involved in making the plan'),
  Field.new(name: 'case_plan_separator',
            type: 'separator',
            display_name_en: 'Overall goal of the case plan'),
  Field.new(name: 'case_plan_goal',
            type: 'select_box',
            display_name_en: 'Case Plan Goal',
            option_strings_text_en: [
              { id: 'reunification_with_parents_or_family', display_text: 'Reunification with parents or family' },
              { id: 'long_term_foster_care', display_text: 'Long-term foster care' },
              { id: 'adoption', display_text: 'Adoption' },
              { id: 'parent_compelled_to_maintain_the_child', display_text: 'Parent compelled to maintain the child' },
              { id: 'client_assisted_with_pwd_common_fund', display_text: 'Client assisted with PWD Common Fund' },
              { id: 'other', display_text: 'Other' },
            ].map(&:with_indifferent_access),
            help_text_en: 'There must be only one goal.'),
  Field.new(name: 'case_plan_goal_other',
            type: 'text_field',
            display_name_en: 'If Other, please specify'),
  Field.new(name: 'case_plan_goal_changes_met',
            type: 'textarea',
            display_name_en: 'What needs to change for this goal to be met?',
            visible: false),
  Field.new(name: 'case_plan_goal_due_date',
            type: 'date_field',
            display_name_en: 'Target date for achieving the goal'),
  Field.new(name: 'intervention_service_to_be_provided_case',
            type: 'select_box',
            display_name_en: 'What interventions need to be taken to achieve this case goal?',
            multi_select: true,
            option_strings_source:"lookup lookup-interventions-type",
            help_text_en: ["A case plan needs to be put in place to implement each of the interventions identified.",
                           "Some of the interventions may already have been identified through the rapid assessment and safety plan."
                          ].join(" "),
            guiding_questions_en: [
                                   "(1) Direct service interventions are intended to strengthen family functioning and address protection concerns so that the child remains in the home or is able to be reintegrated with family once concerns have been addressed.",
                                   "(2) Interventions include the use of community based organisations or services to address family strengthening needs and protection concerns, e.g. counselling, economic opportunities, substance abuse or psychiatric treatment for parent/caregiver.",
                                   "(3) This requires matching the child with a licensed foster parent. The child could be placed in foster care from the RHC (if already in temporary custody) or from their home."
                                  ].join("\n")),
  Field.new(name: 'case_plan_header',
            type: 'separator',
            display_name_en: 'Intervention Plans and Services to be Provided',
            guiding_questions_en: [
                                   "A case plan needs to be put in place to implement each of the interventions identified above.",
                                   "If there are urgent/serious unmet health or medical needs these must also be included in the safety plan."
                                  ].join("\n")),
  # #Subform##
  Field.new(name: 'cp_case_plan_subform_case_plan_interventions',
            type: 'subform',
            editable: true,
            subform_section: case_plan_section,
            subform_sort_by: 'case_plan_timeframe',
            display_name_en: 'Intervention plans and services details'),
  # #Subform##
  Field.new(name: 'care_plan_header',
            type: 'separator',
            display_name_en: 'Care Plan',
            help_text_en: "The Care Plan should be informed by the full assessment of the child and should be focused on achieving the Care Plan goal, which should be directly linked to the overall Case Plan goal.",
            ),
  Field.new(name: 'care_plan_date',
            type: 'date_field',
            display_name_en: 'Date Care Plan Initiated'),
  Field.new(name: 'care_plan_target_date',
            type: 'date_field',
            display_name_en: 'Target Review Date'),
  Field.new(name: 'care_plan_goal',
            type: 'textarea',
            display_name_en: 'Care Plan goal'),
  Field.new(name: 'care_plan_goal_timeframe',
            type: 'date_field',
            display_name_en: 'Time frame for achieving the goal'),
  ##Subform##
  Field.new(name: 'cp_case_plan_subform_care_plan',
  type: 'subform',
  editable: true,
  subform_section: care_plan_section,
  display_name_en: 'Care Plan Domain'),
  ##Subform##

]

FormSection.create_or_update!(
  unique_id: 'cp_case_plan',
  parent_form: 'case',
  visible: true,
  order_form_group: 80,
  order: 999,
  order_subform: 0,
  form_group_id: 'case_plan',
  editable: true,
  fields: case_plan_fields,
  name_en: 'Case Plan',
  description_en: 'Case Plan'
)
