FormSection.create_or_update!(
  {
    unique_id: "client_feedback",
    name_i18n: {
      ar: "ملاحظات العميل",
      en: "Client Feedback"
    },
    description_i18n: {
      ar: "ملاحظات العميل",
      en: "Client Feedback"
    },
    parent_form: "case",
    visible: true,
    order: 10,
    order_form_group: 130,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "client_feedback",
    editable: true,
    core_form: false,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    subform_append_only: false,
    subform_header_links: [],
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    fields_attributes: [
      {
        name: "client_feedback_header",
        type: "separator",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "ملاحظات العميل",
          en: "Client Feedback"
        },
        help_text_i18n: {
          ar: "يعتبر استطلاع رأي العملاء بمثابة فرصة للعملاء لتقديم ملاحظاتهم وآرائهم بشأن الخدمات التي حصلوا عليها، وتوفر معلومات أساسية تساعد مؤسستك في تحديد الممارسات والآليات الناجحة، والتحديات المحتملة والتحسينات الواجب إجراؤها في تقديم الخدمات.\n\nعند إغلاق ملف الحالة يتم إعطاء استطلاع رأي العملاء للناجية إذا:\n\n- تمت تلبية احتياجات الناجية على النحو المحدد في خطة عمل الحالة\n\n- تمت تلبية احتياجات الناجية قدر الإمكان\n\n- طلبت الناجية إغلاق ملف الحالة\n\nيتم استكمال استطلاع الرأي طوعًا ودون ذكر اسم العميل، ويعتبر الاستطلاع وسيلة للحصول على ملاحظات وتعقيبات من العملاء بشأن الخدمات بهدف تحسين البرنامج وفي البيئات التي لا يمكن للناجيات فيها الحصول على الخدمات إلا مرة واحدة، يمكن أن تقرر مؤسستك استخدام نموذج استطلاع رأي العميل في نهاية الجلسة الأولى إذا أمكن.\n\nأما في البيئات التي تتلقى فيها الناجيات خدمات لفترات زمنية أطول، يمكن التفكير في إعطائهن استطلاعات آراء العملاء على نحو أكثر تكرارًا (مثلاً على أساس شهري أو ربع سنوي).\n\nخطوات عملية استخدام استطلاع رأي العملاء مع الناجيات:\n\n(1) اشرح للناجية أهمية ملاحظاتها وآرائها وأن الغرض من جمعها هو تحسين الخدمات التي تقدمها المؤسسة.\n\n(2) وضح للناجية بأن المعلومات ستبقى مجهولة الهوية (بدون اسم) ولن تؤثر على الخدمات التي تتلقاها أو قد تحتاجها في المستقبل. وفي النهاية يبقى اختيارها ما إذا كانت ستملأ الاستبيان أم لا.\n\n(3) لا ينبغي للموظف المختص بالحالة أن يقوم بنفسه بإعطاء الاستبيان للناجية واستلامه منها بعد استكماله بل يجب أن يفعل ذلك شخص آخر كالمشرف أو أحد الموظفين المعنيين الآخرين. ﺑﺎﻟﻨﺴﺒﺔ ﻟﻠﻌﻤﻼء اﻟﻤﺘﻌﻠﻤﻴﻦ، ﻳﻤﻜﻦ اﻟﻘﻴﺎم ﺑﺬﻟﻚ ﺑﺸﻜﻞ ﻣﺴﺘﻘﻞ ﻣﻦ ﺧﻼل ﻧﻤﻮذج ورﻗﻲ أو ﻧﻤﻮذج إﻟﻜﺘﺮوﻧﻲ (ﺟﻬﺎز ﻳﺪوي) وبحيث ﻻ تضطر الناجية إﻟﻰ ذكر اسمها بل تكتفي باﺳﻢ الموظف المختص بحالتها.",
          en: "Client feedback surveys provide an opportunity for clients to give feedback on the services they received and key information to help your organization identify what is working well, possible challenges, and what needs to be improved in terms of service delivery.\nThe Client Feedback Survey can be given at case closure, when \n- Survivor’s needs have been met as described in the Case Action Plan\n- Survivor’s needs have been met to the extent possible\n- Survivor requests to close the case\n\nThe completion of a Client Feedback Survey should be voluntary and is anonymous. It is a means to elicit feedback on services to improve programming. In contexts where survivors may only seek services once, your organization may decide to use the Client Feedback form at the end of the first session, if it is feasible to do so.\n\nIn contexts where survivors receive services for longer periods of time, you can also consider administering client feedback surveys more frequently (e.g. on a monthly or quarterly basis).\nThe process for using them with a survivor should be as follows:\n\n(1) Explain to the person that the purpose is for you and your organization to improve your services, and that their feedback is valued. \n(2) Inform the person that the information will remain anonymous and that it will not impact the services they currently receive or may need in the future. And ultimately, it is their choice as to whether they complete the survey. \n(3) A different caseworker, supervisor or other relevant staff member should be the one who gives the survey to the person and collects it from them at the end. For literate clients, this can be done independently through a paper form or an electronic form (handheld device) in which the person does not have to provide their name, just the name of the caseworker with whom they worked. "
        },
        order: 0,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_feedback_date",
        type: "date_field",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "تاريخ تسليم الناجية استبيان آراء العملاء",
          en: "Date when feedback was provided by survivor"
        },
        order: 1,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_feedback_administered_by",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "تم إجراء الاستطلاع من قبل",
          en: "Questionnaire administered by"
        },
        help_text_i18n: {
          ar: "توجيهات للموظفين:\n- حدد عضو الفريق الذي سيتولى إدارة استبيان آراء العملاء. حدد ما إذا كانت ستتم كتابة الاستبيان وإعطائه للعميل حتى يكمله بنفسه أو ما إذا كان الموظف سيطرح الأسئلة ويسجل إجابات العميل. أخبر العميل أنك ستطرح عليه بعض الأسئلة ولكنك لن تكتب اسمه في الاستبيان وأن المقابلة ستبقى بدون اسم.\n- اشرح للعميل الغرض من الاستبيان. قل إن \"هذا الاستبيان طوعي وسري والغرض منه جمع معلومات عن الخدمات المقدمة للعميل للمساعدة في تحسين جودة الرعاية التي تتلقاها الناجيات من العنف الجنساني في هذا المجتمع\".\n- أكد للعميل أنك ﻟﻦ تسأله أي أﺳﺌﻠﺔ ﺣﻮل حالته اﻟﻔﻌﻠﻴﺔ، وأنك  تهتم ﻓﻘﻂ ﺑﺎﻟﺨﺪﻣﺎت اﻟﺘﻲ يتلقاها ﺧﻼل ﻋﻤﻠﻴﺔ إدارة اﻟﺤﺎﻟﺔ.\n- اطلب موافقة العميل للمضي قدمًا في الاستبيان وإذا رفض العميل استكمال الاستبيان أخبره بعدم وجود مشكلة في ذلك، وفي حال غير رأيه، فيمكنه الاتصال بك لاحقاً.",
          en: "Instructions for staff:\n-Identify who on your team is going to administer the feedback form. Identify whether it will be done in writing (giving the person the questionnaire to complete themselves) or whether a staff member will ask the questions and record the person’s answers.\n-Inform the person that you will ask them some questions but will not write their name on the form and that the interview will remain anonymous.\n-Explain the purpose. Say: 'This questionnaire is voluntary and confidential. Its purpose is to collect information about the services that have been provided to you and to help make improvements in the quality of care that GBV survivors receive in this community.'\n-Remind the person that you will not ask them any questions about their actual case, but are just interested in the services they received throughout the case management process. \n-Get consent to proceed or if the person declines, tell the person that it is ok and if they change their minds they can contact you."
        },
        option_strings_source: "User",
        order: 2,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "survivor_age_group",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "إذا كان العميل قاصراً وكان مقدم الرعاية له يجيب على أسئلة استبيان آراء العملاء، فما هي الفئة العمرية لهذه الناجية الطفلة؟",
          en: "If the client is minor and the caregiver is providing the answers for the feedback form, what is the age group of the child survivor?"
        },
        option_strings_source: "lookup lookup-child-minor-age-group",
        order: 3,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_discovery_method",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "كيف عرف العميل / مقدم الرعاية عن خدماتنا؟",
          en: "How did the client/caregiver found out about our service(s)?"
        },
        option_strings_source: "lookup lookup-discovery-method",
        order: 4,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_feedback_service_delivery_header",
        type: "separator",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "تقديم خدمات ترتكز على احتياجات الناجية",
          en: "Survivor-centered service delivery"
        },
        order: 5,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "opening_hours_when_client_could_attend",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل كانت ساعات العمل مناسبة لوقت العميل بحيث استطاع الحضور لتلقي الخدمة؟",
          en: "Were opening hours at times the client could attend?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 6,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_comfortable_with_case_worker",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل شعر العميل بالارتياح تجاه الموظف المعني بحالته؟",
          en: "Did the client feel comfortable with the case worker?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 7,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "same_case_worker_each_visit",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل تمكن العميل من لقاء نفس الموظف في جميع زيارات المراجعة التي قام بها؟",
          en: "Could the client see the same person at each return visit?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 8,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "could_client_choose_support_person",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل توفرت للناجية إمكانية اختيار شخص مساعد معها؟",
          en: "Could the client choose to have a support person with her?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 9,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_informed_of_options",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل قُدّمت للناجية معلومات كاملة عن خياراتها؟",
          en: "Was the client given full information about what her options were?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 10,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_decided_what_next",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل قرر العميل بنفسه الخطوات اللاحقة التي أراد متابعتها؟",
          en: "Did the client decide for herself what she wanted to happen next?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 11,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_referred_elsewhere",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل تمت إحالة العميل إلى مكان آخر إذا تعذر تقديم الخدمة؟",
          en: "Was the client referred to another place if a service could not be provided?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 12,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_feedback_confidentiality_header",
        type: "separator",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "السرية",
          en: "Confidentiality"
        },
        order: 13,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "survivor_discreet_access",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل تمكنت الناجية من الحصول على الخدمات دون لفت الانتباه إلى نفسها ودون أن يراها أفراد المجتمع الآخرون؟",
          en: "Could the survivor access services without drawing attention to herself or being seen by other community members?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 14,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "staff_respect_confidentiality",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل احترمت الموظفة خصوصية الناجية وسرية معلوماتها؟ هل شاركت الموظفة أي معلومات عن الناجية أو عن حالتها دون أن تكون مخولة بذلك؟",
          en: "Did the staff respect her confidentiality? Did she share any information about the client or her case that she was not entitled to do?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 15,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_private_meeting",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل قابلت الناجية الموظف المختص بحالتها أو غيره من الموظفين على انفراد دون أن يسمعهم أحد غريب؟",
          en: "Did the client meet with a caseworker or other staff in private without being overheard?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 16,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_feedback_staff_header",
        type: "separator",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "فريق العمل / الموظفون",
          en: "The Staff"
        },
        order: 17,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "staff_friendly",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل كان فريق العمل ودوداً؟",
          en: "Were the staff friendly?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 18,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "staff_open_minded",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل كان الموظفون منفتحين ولم يطلقوا الأحكام على الناجية؟",
          en: "Were the staff open-minded, not judging the client?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 19,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "staff_answered_all_questions",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل تمكن الموظفون من الإجابة على جميع أسئلة الناجية بحيث شعرت بالارتياح؟",
          en: "Were the staff able to answer all the client's questions to her satisfaction?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 20,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "staff_client_could_understand",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل استخدم الموظفون لغة تفهمها الناجية؟",
          en: "Did the staff use language the client could understand?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 21,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "staff_allowed_enough_time",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل أتاح الموظفون الفرصة والوقت للناجية حتى تعبر عن مشاكلها بكلماتها الخاصة؟",
          en: "Did the staff allow time to let the client express her problems in her own words?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 22,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "staff_helpful",
        type: "select_box",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل شعرت الناجية بأن فريق العمل ساعدها في حل مشكلتها؟",
          en: "Did the client feel like the staff helped her with her problem?"
        },
        option_strings_source: "lookup lookup-yes-no-not-applicable",
        order: 23,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "staff_helpful_explain",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "يرجى الشرح",
          en: "Please explain"
        },
        order: 24,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_feedback_wellbeing_header",
        type: "separator",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "تحسّن أحوال الناجية",
          en: "The Cleint's Wellbeing"
        },
        order: 25,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_feel_better",
        type: "radio_button",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل شعرت الناجية بتحسن بعد لقائها الموظف المعني بحالتها؟",
          en: "Did the client feel better after meeting with the caseworker?"
        },
        option_strings_source: "lookup lookup-yes-no",
        order: 26,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_feel_better_explain",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "يرجى الشرح",
          en: "Please explain"
        },
        order: 27,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "would_client_recommend_friend",
        type: "radio_button",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "هل تنصح الناجية صديقة لها عانت من العنف القائم على اساس النوع الاجتماعي بالقدوم إلى هنا للحصول على المساعدة؟",
          en: "Would the client recommend a friend who has experienced GBV to come here for help?"
        },
        option_strings_source: "lookup lookup-yes-no",
        order: 28,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "would_client_recommend_friend_explain",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "يرجى الشرح",
          en: "Please explain"
        },
        order: 29,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      },
      {
        name: "client_comments_suggestions",
        type: "textarea",
        multi_select: false,
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        editable: true,
        disabled: false,
        display_name_i18n: {
          ar: "ما التحسينات التي ترغب الناجية في اقتراحها أو التعليقات التي ترغب في طرحها، إن وجدت؟",
          en: "If any, what other improvements would the client like to suggest or other comments she would like to make?"
        },
        order: 30,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        link_to_path_external: true,
        field_tags: [],
        expose_unique_id: false,
        required: false,
        date_validation: "default_date_validation",
        date_include_time: false,
        matchable: false,
        mandatory_for_completion: false
      }
    ],
    module_ids: [
      "primeromodule-gbv"
    ]
  }
)

