FormSection.create_or_update!(
  {
    name_en: "Survivor Assessment",
    description_en: "Survivor Assessment",
    name_ar: "تقييم الناجية / الناجي",
    description_ar: "تقييم الناجية / الناجي",
    unique_id: "survivor_assessment_form",
    parent_form: "case",
    visible: true,
    order: 40,
    order_form_group: 50,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "survivor_assessment",
    editable: true,
    core_form: false,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "assessment_emotional_state_start",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Survivor Profile",
        help_text_en: "Provide basic demographic information on the survivor, including sex, age and displacement status and any other relevant information.",
        guiding_questions_en: "Is the survivor a woman, man, girl or boy or other gender identity?\n\nHow old is the survivor?  Is she a child or adult?\n\nIs she a resident, a refugee or internally displaced person?",
        display_name_ar: "معلومات أساسية عن الناجية / الناجي",
        help_text_ar: "سجل المعلومات الديموغرافية الأساسية عن الناجية / الناجي بما في ذلك الجنس والعمر وحالة النزوح وأي معلومات أخرى ذات صلة.",
        guiding_questions_ar: "هل الناجي امرأة أم رجل، فتاة أم ولد أم له هوية جنسانية أخرى؟\n\nكم عمر الناجية / الناجي؟ هل هي طفل أم بالغ؟\n\nهل هي مقيمة أو لاجئة أو نازحة؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_survivor_background",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Survivor Context (or Background Information)",
        guiding_questions_en: "Provide basic contextual information on the survivor, including her family situation, current living situation, occupation or role, and any other relevant information.",
        display_name_ar: "معلومات سياقية (أو خلفية) عن الناجية / الناجي",
        guiding_questions_ar: "سجل المعلومات السياقية عن الناجية بما في ذلك وضعها العائلي والمعيشي الراهن ومهنتها أو دورها في المجتمع وأي معلومات أخرى ذات صلة.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_family_situation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Survivor's family situation (for adults)",
        guiding_questions_en: "Adult survivor's family situation:\n\nIs she married and/or living with an intimate partner?  (If her husband/intimate partner is not the perpetrator, does he know about what happened to her)?\n\nDoes she have children? If so, how many and how old are they? Do her children live with her?\n\nWho are the other family members present in the client’s life on a daily basis?  Does the survivor have other relatives that are present in her life?",
        display_name_ar: "الوضع العائلي للناجية (للبالغين)",
        guiding_questions_ar: "الوضع العائلي للناجية (للبالغين):\n\nهل هي متزوجة أم تعيش مع شريك حميم؟ (إذا لم يكن زوجها / شريكها الحميم هو الجاني، فهل يعرف بشأن ما حدث لها)؟\n\nهل لدى الناجية أطفال؟ إذا كان الأمر كذلك، فكم عددهم وما أعمارهم؟ هل يعيش أطفالها معها؟\n\nمن هم أفراد الأسرة الآخرون الموجودون في حياة الناجية على أساس يومي؟ هل لدى الناجية أقارب آخرون متواجدون في حياتها؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_current_living_situation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Survivor's current living situation",
        guiding_questions_en: "Does the survivor have a place to live? Where? Who lives in the house with her? Does she live with her husband/intimate partner? Are there relatives living nearby?",
        display_name_ar: "الوضع المعيشي الحالي للناجية",
        guiding_questions_ar: "هل للناجية مكان تعيش فيه؟ أين؟ من يعيش في المنزل معها؟ هل تعيش مع زوجها / شريكها الحميم؟ هل هناك أقارب يعيشون في الجوار؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assssment_survivor_occupation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Survivor's occupation or role",
        guiding_questions_en: "Does survivor work? Is her work at home? Have paid employment? Part-time or full-time? Does survivor have a special role in the community where s/he lives?",
        display_name_ar: "مهنة الناجية أو دورها",
        guiding_questions_ar: "هل تعمل الناجية؟ هل عملها في المنزل؟ هل لديها عمل مدفوع الأجر؟ بدوام جزئي أم كامل؟ هل للناجية دور خاص في المجتمع الذي تعيش فيه؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_child_considerations",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Specific considerations for child survivors",
        guiding_questions_en: "Does she live with her parents? (If her parents or guardians are not the perpetrators, do they know about what happened to her)? Who are the other family members present in the client’s life on a daily basis? Does the survivor have other relatives that are present in her life?",
        display_name_ar: "اعتبارات خاصة للناجيات من الأطفال",
        guiding_questions_ar: "هل تعيش الناجية مع والديها؟ (إذا لم يكن والداها أو الأوصياء عليها هم الجناة، فهل يعرفون ما حدث لها)؟ من هم أفراد الأسرة الآخرون الموجودون في حياة الناجية على أساس يومي؟ هل لدى الناجية أقارب آخرون متواجدون في حياتها؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_presenting_problem",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Presenting Problem",
        guiding_questions_en: "Describe what happened to the survivor in the survivor's own words. Identify what problem(s)/concern(s)/issue(s) the survivor is requesting assistance/support for.\n\nList survivor's main concerns in her own words (do not suggest). These might include: immediate safety, children's safety, access to economic resources, medical assistance, perception of others, etc.",
        display_name_ar: "عرض المشكلة",
        guiding_questions_ar: "صف ما حدث للناجية بكلمات الناجية. حدد المشكلة / المشكلات / الاهتمامات / القضايا التي تطلب الناجية المساعدة / الدعم بشأنها.\n\nسجل قائمة الشواغل الرئيسية للناجية بكلماتها الخاصة (لا تقترح عليها). قد تشمل هذه الشواغل: أمانها الفوري، سلامة أطفالها، الحصول على موارد اقتصادية أو مساعدة طبية، تصورها عن الآخرين أو تصور الآخرين لها، إلخ.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_emotional_state_end",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Describe what happened to the survivor in the survivor's own words",
        guiding_questions_en: "What happened to the survivor? What is the nature of the violence? When did it occur? What prompted her to seek services? What are her main concerns? What does she want help with?",
        display_name_ar: "صف ما حدث للناجية بكلماتها الخاصة",
        guiding_questions_ar: "ماذا حدث للناجية؟ ما هي طبيعة العنف؟ متى حدث؟ ما الذي دفعها للبحث عن الخدمات؟ ما هي مخاوفها الرئيسية؟ في أي مجال تطلب المساعدة؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_main_concerns",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Key Assessment Points",
        guiding_questions_en: "Summarize key assessment points with respect to the nature, timing, frequency and severity of the violence reported, who the perpetrator/s is/are in relation to the survivor and whether he/they have easy access to the survivor, in order to determine risk. Gauge emotional well-being, ability to keep up with day-today tasks, overall sense of safety in the world, and ability to trust others. Identify the survivor's needs (safety, health, psychosocial, legal/justice, practical/material, other) as well as her strengths and coping strategies to determine need for psychosocial support and/or appropriate and timely referrals.",
        display_name_ar: "نقاط التقييم الرئيسية",
        guiding_questions_ar: "لخص نقاط التقييم الرئيسية فيما يتعلق بطبيعة العنف المبلغ عنه ووقت حدوثه وتكراره وشدته، ومن هو الجاني (الجناة) وما علاقته / علاقتهم بالناجية وما إذا كان وصوله وصولهم إليها سهلا، وذلك من أجل تحديد المخاطر. قم بتقييم السلامة العاطفية للناجية وقدرتها على مواكبة المهام اليومية، وشعورها العام بالأمان في العالم وقدرتها على الثقة بالآخرين. حدّد احتياجات الناجية (احتياجات السلامة والاحتياجات الصحية والنفسية الاجتماعية والقانونية / العدالة، العملية / المادية، وغيرها)، فضلا عن نقاط قوتها واستراتيجياتها للتأقلم من أجل تقييم حاجتها إلى دعم نفسي واجتماعي و / أو إحالتها إلى الخدمة المناسبة في الوقت المناسب.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_current_situation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Current situation and imminent risks",
        guiding_questions_en: "Identify situations, circumstances and people that are continuing to harm the survivor or put her at risk of harm. \n\nDoes/do the perpetrator/s know where the survivor is right now? If yes, does the survivor think that the perpetrator/s may come try to find her here?\n\nWhen did the incident take place (date/time)? Is survivor bleeding or have an acute injury or in any severe pain (especially head injuries)? Was there forced vaginal/anal penetration? Was physical force and/or weapons used? How frequently has survivor experienced violence like this incident?\n\nWhat is the relationship between the survivor and the perpetrator? Does the perpetrator have access to a weapon? Does the perpetrator have easy access the survivor (ex. lives in the same household, neighbourhood, etc.)? Does the perpetrator have a history of using violence against others, abusing drugs or alcohol, and/or a history of depression or other mental health issues?\n\nHas survivor sought help previously and/or already received care and treatment? Does survivor express any current or past suicidal thoughts? (If so, follow the Suicide Risk Assessment Protocol)",
        display_name_ar: "الوضع الحالي والمخاطر الوشيكة",
        guiding_questions_ar: "حدد المواقف والظروف والأشخاص الذين يستمرون في إيذاء الناجية أو يعرضونها لخطر الأذى.\n\nهل يعرف الجاني / الجناة مكان الناجية الحالي؟ إذا كانت الإجابة نعم، فهل تعتقد الناجية أن الجاني / الجناة قد يأتي / يأتون لمحاولة العثور عليها في مكانها هنا؟\n\nمتى وقعت الحادثة (التاريخ / الوقت)؟ هل تعاني الناجية من نزيف أو إصابة حادة أو أي ألم شديد (خاصة إصابات الرأس)؟ هل كان هناك اختراق قسري للمهبل / للشرج؟ هل تم استخدام القوة البدنية و / أو الأسلحة؟ كم عدد المرات التي عانت فيها الناجية من عنف مماثل؟\n\nما هي العلاقة بين الناجية والجاني؟ هل يمكن للجاني الحصول على سلاح؟ هل يسهل على الجاني الوصول إلى الناجية (مثلا يعيشان في نفس المنزل أو الحي، إلخ)؟ هل لدى الجاني سوابق في استخدام العنف ضد الآخرين، أو تعاطي المخدرات أو الكحول، و / أو تاريخ من الاكتئاب أو مشاكل نفسية أخرى؟\n\nهل طلبت الناجية المساعدة و / أو تلقت الرعاية والعلاج من قبل؟ هل تعبر الناجية عن أي أفكار حالية أو سابقة بالانتحار؟ (إذا كان الأمر كذلك، اتبع بروتوكول تقييم مخاطر الانتحار)",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_safety_needs",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Safety needs",
        guiding_questions_en: "Will the survivor be in immediate danger when she leaves here? How safe does the survivor feel at home? (Note: caseworker can use tools such as safety scale to help determine this). Has the survivor ever tried to get help from anyone else? Has the survivor ever tried to leave? Are aspects about the perpetrator’s profile or the type of violence that place the survivor in immediate danger?",
        display_name_ar: "احتياجات السلامة",
        guiding_questions_ar: "هل ستكون الناجية في خطر مباشر عندما تغادر من هنا؟ ما مدى شعور الناجية بالأمان في المنزل؟ (ملاحظة: يمكن أن يستخدم الموظف المختص بالحالة أدوات مثل مقياس الأمان للمساعدة في تحديد ذلك). هل حاولت الناجية فيما مضى الحصول على مساعدة من أي شخص آخر؟ هل حاولت الناجية المغادرة؟ هل هناك جوانب في ملف الجاني أو نوع العنف تضع الناجية في خطر مباشر؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_health_needs",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Health needs",
        guiding_questions_en: "Does the client require and/or want medical attention? Did the last incident occur within the past 120 hours? Would the survivor like to know more about medication and exam options? Is the survivor complaining of physical pain and injury, or bleeding or discharge?",
        display_name_ar: "الاحتياجات الصحية",
        guiding_questions_ar: "هل تحتاج الناجية و / أو تريد رعاية طبية؟ هل حدثت آخر حادثة خلال الـ 120 ساعة الماضية؟ هل ترغب الناجية في معرفة المزيد عن خيارات الفحص والعلاج؟ هل تشكو الناجية من ألم جسدي أو إصابة أو نزيف؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_psychosocial_needs",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Psychosocial needs",
        guiding_questions_en: "How does the survivor describe her emotional state?\n\nBased on your observations, how would you describe the survivor's appearance and behavior? Is there anything strange or unusual about the survivor's appearance or behavior right now? What is your sense of the client’s level of functioning? (Listen for indications that the survivor stopped leaving the house, conducting her daily activities, talking with or seeing family and friends, or her sleep aptterns and eating habits are disturbed).\n\nDoes the survivor feel sad most of the time, hopeless about her situation or life? Does the survivor complain of physical aches? Are there other major changes or difficulties the survivor shares?\n\nWhat kinds of social supports does the survivor have? Who does the survivor like to talk to or spend time with outside of her house? Does she have friendships? People whom she can trust? Who are the survivor’s sources of emotional support? Has she been able to access these social supports since the incident? How have they helped her? Who/what are the people, elements, ideas, or experiences in the survivor’s life that she identifies as giving her hope and strength? \n\nWhat are her existing assets (ex. people, knowledge, skills, income, housing)? Does she have positive coping mechanisms? What are they? Does religion and/or faith play a part in the survivor’s life? Has she been able to draw upon her faith and/or religious practice since the incident? How has doing so helped her?",
        display_name_ar: "الاحتياجات النفسية والاجتماعية",
        guiding_questions_ar: "كيف تصف الناجية حالتها العاطفية؟\n\nاستنادًا إلى ملاحظاتك، كيف تصف مظهر وسلوك الناجية؟ هل هناك أي شيء غريب أو غير عادي في مظهر أو سلوك الناجية في الوقت الحالي؟ ما هو إحساسك بمستوى أداء الناجية؟ (راقب مؤشرات تتعلق مثلا بامتناع الناجية عن مغادرة المنزل، أو توقفها عن ممارسة أنشطتها اليومية، أو عن التحدث مع العائلة أو الأصدقاء أو رؤيتهم، أو حدوث اضطرابات في نومها وعاداتها الغذائية).\n\nهل تشعر الناجية بالحزن في معظم الأحيان، أو باليأس من حالتها أو حياتها؟ هل تشتكي الناجية من آلام جسدية؟ هل هناك تغييرات أو صعوبات رئيسية أخرى تعبر عنها الناجية؟\n\nما أنواع الدعم الاجتماعي التي تحصل عليها الناجية؟ مع من تريد الناجية التحدث أو قضاء بعض الوقت خارج منزلها؟ هل لديها صداقات؟ أو أشخاص يمكن أن تثق بهم؟ من يقدم لها الدعم العاطفي؟ هل تمكنت من الوصول إلى هذا الدعم الاجتماعي منذ وقوع الحادثة؟ كيف تمت مساعدتها؟ حدد الأشخاص أو العناصر أو الأفكار أو الخبرات في حياة الناجية التي تمنحها الأمل والقوة؟\n\nما هي الموارد الحالية المتوفرة للناجية (مثلا الأشخاص والمعارف والمهارات والدخل والإسكان)؟ هل لديها آليات مواجهة إيجابية؟ ما هي؟ هل يلعب الدين و / أو الإيمان دورًا في حياة الناجية؟ هل تمكنت من الاعتماد على إيمانها و / أو ممارستها الدينية منذ وقوع الحادثة؟ كيف ساعدها ذلك؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_legal_needs",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Legal/justice needs",
        guiding_questions_en: "Does the survivor wish to report to formal authorities and/or take legal action.\n\nWhat are the risks, benefits, time and costs the survivor should factor in her decision to take legal action? Is legal recourse an immediate priority for the survivor? What information does the client need to make a decision about justice?\n\nDoes the survivor want more information about how her legal rights and/or options for taking her case through the formal justice system, or the traditional /informal justice system? Does the survivor understand the differences between how a case would be handled through traditional vs. formal justice mechanisms?",
        display_name_ar: "الاحتياجات القانونية / العدالة",
        guiding_questions_ar: "هل ترغب الناجية في إبلاغ السلطات الرسمية و / أو اتخاذ إجراء قانوني.\n\nما هي المخاطر والفوائد والوقت والتكاليف التي يجب على الناجية مراعاتها في قرارها باتخاذ إجراء قانوني؟ هل الطعن القانوني أولوية فورية للناجية؟ ما المعلومات التي تحتاج إليها لاتخاذ قرار بشأن العدالة؟\n\nهل تريد الناجية الحصول على مزيد من المعلومات حول حقوقها القانونية و / أو خياراتها لمتابعة قضيتها عبر نظام العدالة الرسمي، أو نظام العدالة التقليدي / غير الرسمي؟ هل تفهم الناجية الاختلافات بين آليات العدالة التقليدية وآليات العدالة الرسمية في التعامل مع قضيتها؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_material_needs",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Practical/material needs",
        guiding_questions_en: "Does the survivor have access to income? Does the survivor have access to food, clothes, phone credit, transportation, etc.? What are the survivor's sources of support, including family and community? Is the survivor's lack of income impacting her ability to be safe? Is the survivor's lack of (or access to) income putting her at risk for violence?",
        display_name_ar: "الاحتياجات العملية / المادية",
        guiding_questions_ar: "هل لدى الناجية مصدر دخل؟ هل تستطيع تدبير الطعام والملابس ورسوم الهاتف والنقل وما إلى ذلك؟ ما هي مصادر الدعم المتوفرة للناجية، بما في ذلك أسرتها والمجتمع؟ هل تؤثر قلة دخل الناجية على قدرتها على البقاء بأمان؟ هل يزيد ضعف وصولها إلى مصادر الدخل من تعرضها لخطر العنف؟",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_completion_timing",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "How long did it take you to complete the assessment for this case?",
        display_name_ar: "كم من الوقت استغرقت عملية إغلاق ملف الحالة مع هذه الناجية؟",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-assessment-duration",
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

