# Automatically generated script to migrate locations from v1.7 to v2.0+

Location.destroy_all

locations = [
  Location.new(placename_i18n: { "en": "DR Congo" }, location_code:"DRC", admin_level: 5, type: "country", hierarchy_path: 'DRC'),
  Location.new(placename_i18n: { "en": "Burundi" }, location_code:"BI", admin_level: 5, type: "country", hierarchy_path: 'BI'),
  Location.new(placename_i18n: { "en": "Tanzania" }, location_code:"TZQ", admin_level: 5, type: "country", hierarchy_path: 'TZQ'),
  Location.new(placename_i18n: { "en": "Tangara" }, location_code:"TNG", admin_level: 100, type: "city", hierarchy_path: 'BI.NGZ.TNG'),
  Location.new(placename_i18n: { "en": "Ruhororo" }, location_code:"RHR", admin_level: 100, type: "city", hierarchy_path: 'BI.NGZ.RHR'),
  Location.new(placename_i18n: { "en": "Nyamurenza" }, location_code:"NYM", admin_level: 100, type: "city", hierarchy_path: 'BI.NGZ.NYM'),
  Location.new(placename_i18n: { "en": "Mwumba" }, location_code:"MWB", admin_level: 100, type: "city", hierarchy_path: 'BI.NGZ.MWB'),
  Location.new(placename_i18n: { "en": "Muhuta" }, location_code:"MHT", admin_level: 100, type: "city", hierarchy_path: 'BI.RMG.MHT'),
  Location.new(placename_i18n: { "en": "Marangara" }, location_code:"MRA", admin_level: 100, type: "city", hierarchy_path: 'BI.NGZ.MRA'),
  Location.new(placename_i18n: { "en": "Kiremba" }, location_code:"KBA", admin_level: 100, type: "city", hierarchy_path: 'BI.NGZ.KBA'),
  Location.new(placename_i18n: { "en": "Buyengero" }, location_code:"BYGR", admin_level: 100, type: "city", hierarchy_path: 'BI.RMG.BYGR'),
  Location.new(placename_i18n: { "en": "Gashikanwa" }, location_code:"GKW", admin_level: 100, type: "city", hierarchy_path: 'BI.NGZ.GKW'),
  Location.new(placename_i18n: { "en": "Burambi" }, location_code:"BRB", admin_level: 100, type: "city", hierarchy_path: 'BI.RMG.BRB'),
  Location.new(placename_i18n: { "en": "Bugarama" }, location_code:"BGR", admin_level: 100, type: "city", hierarchy_path: 'BI.RMG.BGR'),
  Location.new(placename_i18n: { "en": "Busiga" }, location_code:"BG", admin_level: 100, type: "city", hierarchy_path: 'BI.NGZ.BG'),
  Location.new(placename_i18n: { "en": "Rumonge" }, location_code:"RMG", admin_level: 100, type: "province", hierarchy_path: 'BI.RMG'),
  Location.new(placename_i18n: { "en": "Ngozi" }, location_code:"NGZ", admin_level: 100, type: "province", hierarchy_path: 'BI.NGZ'),
  Location.new(placename_i18n: { "en": "Musongati" }, location_code:"MSG", admin_level: 100, type: "city", hierarchy_path: 'BI.RTN.MSG'),
  Location.new(placename_i18n: { "en": "Rusaka" }, location_code:"RSK", admin_level: 100, type: "city", hierarchy_path: 'BI.MW.RSK'),
  Location.new(placename_i18n: { "en": "Mpinga-Kayove" }, location_code:"MKY", admin_level: 100, type: "city", hierarchy_path: 'BI.RTN.MKY'),
  Location.new(placename_i18n: { "en": "Nyabihanga" }, location_code:"NBG", admin_level: 100, type: "city", hierarchy_path: 'BI.MW.NBG'),
  Location.new(placename_i18n: { "en": "Gitanga" }, location_code:"GTG", admin_level: 100, type: "city", hierarchy_path: 'BI.RTN.GTG'),
  Location.new(placename_i18n: { "en": "Ndava" }, location_code:"ND", admin_level: 100, type: "city", hierarchy_path: 'BI.MW.ND'),
  Location.new(placename_i18n: { "en": "Giharo" }, location_code:"GHR", admin_level: 100, type: "city", hierarchy_path: 'BI.RTN.GHR'),
  Location.new(placename_i18n: { "en": "Kayokwe" }, location_code:"KYK", admin_level: 100, type: "city", hierarchy_path: 'BI.MW.KYK'),
  Location.new(placename_i18n: { "en": "Bukemba" }, location_code:"BKB", admin_level: 100, type: "city", hierarchy_path: 'BI.RTN.BKB'),
  Location.new(placename_i18n: { "en": "Gisozi" }, location_code:"GSZ", admin_level: 100, type: "city", hierarchy_path: 'BI.MW.GSZ'),
  Location.new(placename_i18n: { "en": "Bisoro" }, location_code:"BIS", admin_level: 100, type: "city", hierarchy_path: 'BI.MW.BIS'),
  Location.new(placename_i18n: { "en": "Rutana" }, location_code:"RTN", admin_level: 100, type: "province", hierarchy_path: 'BI.RTN'),
  Location.new(placename_i18n: { "en": "Mwaro" }, location_code:"MW", admin_level: 100, type: "province", hierarchy_path: 'BI.MW'),
  Location.new(placename_i18n: { "en": "Mwakiro" }, location_code:"MWK", admin_level: 100, type: "city", hierarchy_path: 'BI.MYG.MWK'),
  Location.new(placename_i18n: { "en": "Nyabitsinda" }, location_code:"NBS", admin_level: 100, type: "city", hierarchy_path: 'BI.RYG.NBS'),
  Location.new(placename_i18n: { "en": "Giteranyi" }, location_code:"GTY", admin_level: 100, type: "city", hierarchy_path: 'BI.MYG.GTY'),
  Location.new(placename_i18n: { "en": "Kinyinya" }, location_code:"KYN", admin_level: 100, type: "city", hierarchy_path: 'BI.RYG.KYN'),
  Location.new(placename_i18n: { "en": "Gasorwe" }, location_code:"GSW", admin_level: 100, type: "city", hierarchy_path: 'BI.MYG.GSW'),
  Location.new(placename_i18n: { "en": "Gashoho" }, location_code:"GSH", admin_level: 100, type: "city", hierarchy_path: 'BI.MYG.GSH'),
  Location.new(placename_i18n: { "en": "Gisuru" }, location_code:"GSR", admin_level: 100, type: "city", hierarchy_path: 'BI.RYG.GSR'),
  Location.new(placename_i18n: { "en": "Butihinda" }, location_code:"BTD", admin_level: 100, type: "city", hierarchy_path: 'BI.MYG.BTD'),
  Location.new(placename_i18n: { "en": "Buhinyuza" }, location_code:"BYA", admin_level: 100, type: "city", hierarchy_path: 'BI.MYG.BYA'),
  Location.new(placename_i18n: { "en": "Muyinga" }, location_code:"MYG", admin_level: 100, type: "province", hierarchy_path: 'BI.MYG'),
  Location.new(placename_i18n: { "en": "Bweru" }, location_code:"BWR", admin_level: 100, type: "city", hierarchy_path: 'BI.RYG.BWR'),
  Location.new(placename_i18n: { "en": "Rutegama" }, location_code:"RTG", admin_level: 100, type: "city", hierarchy_path: 'BI.MRV.RTG'),
  Location.new(placename_i18n: { "en": "Butezi" }, location_code:"BTZ", admin_level: 100, type: "city", hierarchy_path: 'BI.RYG.BTZ'),
  Location.new(placename_i18n: { "en": "Butaganzwa" }, location_code:"BZW", admin_level: 100, type: "city", hierarchy_path: 'BI.RYG.BZW'),
  Location.new(placename_i18n: { "en": "Mbuye" }, location_code:"MBY", admin_level: 100, type: "city", hierarchy_path: 'BI.MRV.MBY'),
  Location.new(placename_i18n: { "en": "Kiganda" }, location_code:"KGD", admin_level: 100, type: "city", hierarchy_path: 'BI.MRV.KGD'),
  Location.new(placename_i18n: { "en": "Ruyigi" }, location_code:"RYG", admin_level: 100, type: "province", hierarchy_path: 'BI.RYG'),
  Location.new(placename_i18n: { "en": "Bukeye" }, location_code:"BKY", admin_level: 100, type: "city", hierarchy_path: 'BI.MRV.BKY'),
  Location.new(placename_i18n: { "en": "Muramvya" }, location_code:"MRV", admin_level: 100, type: "province", hierarchy_path: 'BI.MRV'),
  Location.new(placename_i18n: { "en": "Vugizo" }, location_code:"VGZ", admin_level: 100, type: "city", hierarchy_path: 'BI.MKB.VGZ'),
  Location.new(placename_i18n: { "en": "Nyanzalac" }, location_code:"NYZ", admin_level: 100, type: "city", hierarchy_path: 'BI.MKB.NYZ'),
  Location.new(placename_i18n: { "en": "Mabanda" }, location_code:"MBD", admin_level: 100, type: "city", hierarchy_path: 'BI.MKB.MBD'),
  Location.new(placename_i18n: { "en": "Kibago" }, location_code:"KIO", admin_level: 100, type: "city", hierarchy_path: 'BI.MKB.KIO'),
  Location.new(placename_i18n: { "en": "Kayogoro" }, location_code:"KYG", admin_level: 100, type: "city", hierarchy_path: 'BI.MKB.KYG'),
  Location.new(placename_i18n: { "en": "Makamba" }, location_code:"MKB", admin_level: 100, type: "province", hierarchy_path: 'BI.MKB'),
  Location.new(placename_i18n: { "en": "Vumbi" }, location_code:"VMB", admin_level: 100, type: "city", hierarchy_path: 'BI.KRD.VMB'),
  Location.new(placename_i18n: { "en": "Ntega" }, location_code:"NTG", admin_level: 100, type: "city", hierarchy_path: 'BI.KRD.NTG'),
  Location.new(placename_i18n: { "en": "Gitobe" }, location_code:"GTB", admin_level: 100, type: "city", hierarchy_path: 'BI.KRD.GTB'),
  Location.new(placename_i18n: { "en": "Bwambarangwe" }, location_code:"BWB", admin_level: 100, type: "city", hierarchy_path: 'BI.KRD.BWB'),
  Location.new(placename_i18n: { "en": "Busoni" }, location_code:"BSN", admin_level: 100, type: "city", hierarchy_path: 'BI.KRD.BSN'),
  Location.new(placename_i18n: { "en": "Bugabira" }, location_code:"BGB", admin_level: 100, type: "city", hierarchy_path: 'BI.KRD.BGB'),
  Location.new(placename_i18n: { "en": "Kirundo" }, location_code:"KRD", admin_level: 100, type: "province", hierarchy_path: 'BI.KRD'),
  Location.new(placename_i18n: { "en": "Rango" }, location_code:"RAN", admin_level: 100, type: "city", hierarchy_path: 'BI.KYZ.RAN'),
  Location.new(placename_i18n: { "en": "Muruta" }, location_code:"MRT", admin_level: 100, type: "city", hierarchy_path: 'BI.KYZ.MRT'),
  Location.new(placename_i18n: { "en": "Muhanga" }, location_code:"MUN", admin_level: 100, type: "city", hierarchy_path: 'BI.KYZ.MUN'),
  Location.new(placename_i18n: { "en": "Matongo" }, location_code:"MTG", admin_level: 100, type: "city", hierarchy_path: 'BI.KYZ.MTG'),
  Location.new(placename_i18n: { "en": "Kabarore" }, location_code:"KRB", admin_level: 100, type: "city", hierarchy_path: 'BI.KYZ.KRB'),
  Location.new(placename_i18n: { "en": "Gatara" }, location_code:"GTR", admin_level: 100, type: "city", hierarchy_path: 'BI.KYZ.GTR'),
  Location.new(placename_i18n: { "en": "Gahombo" }, location_code:"GAH", admin_level: 100, type: "city", hierarchy_path: 'BI.KYZ.GAH'),
  Location.new(placename_i18n: { "en": "Butaganzwa" }, location_code:"BTG", admin_level: 100, type: "city", hierarchy_path: 'BI.KYZ.BTG'),
  Location.new(placename_i18n: { "en": "Kayanza" }, location_code:"KYZ", admin_level: 100, type: "province", hierarchy_path: 'BI.KYZ'),
  Location.new(placename_i18n: { "en": "Shombo" }, location_code:"SHB", admin_level: 100, type: "city", hierarchy_path: 'BI.KUR.SHB'),
  Location.new(placename_i18n: { "en": "Nyabikere" }, location_code:"NYK", admin_level: 100, type: "city", hierarchy_path: 'BI.KUR.NYK'),
  Location.new(placename_i18n: { "en": "Mutumba" }, location_code:"MTB", admin_level: 100, type: "city", hierarchy_path: 'BI.KUR.MTB'),
  Location.new(placename_i18n: { "en": "Gitaramuka" }, location_code:"GTM", admin_level: 100, type: "city", hierarchy_path: 'BI.KUR.GTM'),
  Location.new(placename_i18n: { "en": "Gihogazi" }, location_code:"GHG", admin_level: 100, type: "city", hierarchy_path: 'BI.KUR.GHG'),
  Location.new(placename_i18n: { "en": "Buhiga" }, location_code:"BHG", admin_level: 100, type: "city", hierarchy_path: 'BI.KUR.BHG'),
  Location.new(placename_i18n: { "en": "Bugenyuzi" }, location_code:"BGZ", admin_level: 100, type: "city", hierarchy_path: 'BI.KUR.BGZ'),
  Location.new(placename_i18n: { "en": "Karuzi`" }, location_code:"KUR", admin_level: 100, type: "province", hierarchy_path: 'BI.KUR'),
  Location.new(placename_i18n: { "en": "Kambarare" }, location_code:"KBR", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNM.KBR'),
  Location.new(placename_i18n: { "en": "Kairo" }, location_code:"KR", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNM.KR'),
  Location.new(placename_i18n: { "en": "Kasongo" }, location_code:"KSG", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNM.KSG'),
  Location.new(placename_i18n: { "en": "Kibombo" }, location_code:"KMB", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNM.KMB'),
  Location.new(placename_i18n: { "en": "Lubuta" }, location_code:"LBT", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNM.LBT'),
  Location.new(placename_i18n: { "en": "Pangi" }, location_code:"PNG", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNM.PNG'),
  Location.new(placename_i18n: { "en": "Punia" }, location_code:"PNA", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNM.PNA'),
  Location.new(placename_i18n: { "en": "Mikelenge" }, location_code:"MLG", admin_level: 100, type: "city", hierarchy_path: 'DRC.MNM.KND.MLG'),
  Location.new(placename_i18n: { "en": "Kasuku" }, location_code:"KSK", admin_level: 100, type: "city", hierarchy_path: 'DRC.MNM.KND.KSK'),
  Location.new(placename_i18n: { "en": "Lusambo" }, location_code:"LSB", admin_level: 100, type: "district", hierarchy_path: 'DRC.SAN.LSB'),
  Location.new(placename_i18n: { "en": "Alunguli" }, location_code:"ALGL", admin_level: 100, type: "city", hierarchy_path: 'DRC.MNM.KND.ALGL'),
  Location.new(placename_i18n: { "en": "Lubefu" }, location_code:"LBF", admin_level: 100, type: "district", hierarchy_path: 'DRC.SAN.LBF'),
  Location.new(placename_i18n: { "en": "Lomela" }, location_code:"LML", admin_level: 100, type: "district", hierarchy_path: 'DRC.SAN.LML'),
  Location.new(placename_i18n: { "en": "Ryansoro" }, location_code:"RYA", admin_level: 100, type: "city", hierarchy_path: 'BI.GIT.RYA'),
  Location.new(placename_i18n: { "en": "Kindu" }, location_code:"KND", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNM.KND'),
  Location.new(placename_i18n: { "en": "Nyanrusange" }, location_code:"NYAN", admin_level: 100, type: "city", hierarchy_path: 'BI.GIT.NYAN'),
  Location.new(placename_i18n: { "en": "Mutaho" }, location_code:"MTH", admin_level: 100, type: "city", hierarchy_path: 'BI.GIT.MTH'),
  Location.new(placename_i18n: { "en": "Makebuko" }, location_code:"MKE", admin_level: 100, type: "city", hierarchy_path: 'BI.GIT.MKE'),
  Location.new(placename_i18n: { "en": "Itaba" }, location_code:"ITA", admin_level: 100, type: "city", hierarchy_path: 'BI.GIT.ITA'),
  Location.new(placename_i18n: { "en": "Maniema" }, location_code:"MNM", admin_level: 100, type: "province", hierarchy_path: 'DRC.MNM'),
  Location.new(placename_i18n: { "en": "Lodja" }, location_code:"LOD", admin_level: 100, type: "district", hierarchy_path: 'DRC.SAN.LOD'),
  Location.new(placename_i18n: { "en": "North Kivu" }, location_code:"NKV", admin_level: 100, type: "district", hierarchy_path: 'DRC.KV.NKV'),
  Location.new(placename_i18n: { "en": "Kole" }, location_code:"KO", admin_level: 100, type: "district", hierarchy_path: 'DRC.SAN.KO'),
  Location.new(placename_i18n: { "en": "Gishubi" }, location_code:"GIS", admin_level: 100, type: "city", hierarchy_path: 'BI.GIT.GIS'),
  Location.new(placename_i18n: { "en": "South Kivu" }, location_code:"SKV", admin_level: 100, type: "district", hierarchy_path: 'DRC.KV.SKV'),
  Location.new(placename_i18n: { "en": "Katako Kombe" }, location_code:"KTK", admin_level: 100, type: "district", hierarchy_path: 'DRC.SAN.KTK'),
  Location.new(placename_i18n: { "en": "Giheta" }, location_code:"GHE", admin_level: 100, type: "city", hierarchy_path: 'BI.CIB.GHE'),
  Location.new(placename_i18n: { "en": "Kivu" }, location_code:"KV", admin_level: 100, type: "province", hierarchy_path: 'DRC.KV'),
  Location.new(placename_i18n: { "en": "Buraza" }, location_code:"BRZ", admin_level: 100, type: "city", hierarchy_path: 'BI.GIT.BRZ'),
  Location.new(placename_i18n: { "en": "Sankuru" }, location_code:"SAN", admin_level: 100, type: "province", hierarchy_path: 'DRC.SAN'),
  Location.new(placename_i18n: { "en": "Mambasa" }, location_code:"MBS", admin_level: 100, type: "district", hierarchy_path: 'DRC.ITR.MBS'),
  Location.new(placename_i18n: { "en": "Bukirasazi" }, location_code:"BKI", admin_level: 100, type: "city", hierarchy_path: 'BI.GIT.BKI'),
  Location.new(placename_i18n: { "en": "Mahagi" }, location_code:"MHG", admin_level: 100, type: "district", hierarchy_path: 'DRC.ITR.MHG'),
  Location.new(placename_i18n: { "en": "Irumu" }, location_code:"IRM", admin_level: 100, type: "district", hierarchy_path: 'DRC.ITR.IRM'),
  Location.new(placename_i18n: { "en": "Kabinda" }, location_code:"KBD", admin_level: 100, type: "district", hierarchy_path: 'DRC.LOM.KBD'),
  Location.new(placename_i18n: { "en": "Djugu" }, location_code:"DJG", admin_level: 100, type: "district", hierarchy_path: 'DRC.ITR.DJG'),
  Location.new(placename_i18n: { "en": "Lomami" }, location_code:"LOM", admin_level: 100, type: "province", hierarchy_path: 'DRC.LOM'),
  Location.new(placename_i18n: { "en": "Aru" }, location_code:"AR", admin_level: 100, type: "district", hierarchy_path: 'DRC.ITR.AR'),
  Location.new(placename_i18n: { "en": "Tshilenge" }, location_code:"TSG", admin_level: 100, type: "district", hierarchy_path: 'DRC.KSIO.TSG'),
  Location.new(placename_i18n: { "en": "Miabi" }, location_code:"MIL", admin_level: 100, type: "district", hierarchy_path: 'DRC.KSIO.MIL'),
  Location.new(placename_i18n: { "en": "Ituri" }, location_code:"ITR", admin_level: 100, type: "province", hierarchy_path: 'DRC.ITR'),
  Location.new(placename_i18n: { "en": "Lupatapata" }, location_code:"LPT", admin_level: 100, type: "district", hierarchy_path: 'DRC.KSIO.LPT'),
  Location.new(placename_i18n: { "en": "Watsa" }, location_code:"WTS", admin_level: 100, type: "district", hierarchy_path: 'DRC.HTUL.WTS'),
  Location.new(placename_i18n: { "en": "Katanda" }, location_code:"KAT", admin_level: 100, type: "district", hierarchy_path: 'DRC.KSIO.KAT'),
  Location.new(placename_i18n: { "en": "Wamba" }, location_code:"WMB", admin_level: 100, type: "district", hierarchy_path: 'DRC.HTUL.WMB'),
  Location.new(placename_i18n: { "en": "Kabeya-Kamwanga" }, location_code:"KBK", admin_level: 100, type: "district", hierarchy_path: 'DRC.KSIO.KBK'),
  Location.new(placename_i18n: { "en": "Rungu" }, location_code:"RNG", admin_level: 100, type: "district", hierarchy_path: 'DRC.HTUL.RNG'),
  Location.new(placename_i18n: { "en": "Niangara" }, location_code:"NGR", admin_level: 100, type: "district", hierarchy_path: 'DRC.HTUL.NGR'),
  Location.new(placename_i18n: { "en": "Faradje" }, location_code:"FRD", admin_level: 100, type: "district", hierarchy_path: 'DRC.HTUL.FRD'),
  Location.new(placename_i18n: { "en": "Kasai Oriental" }, location_code:"KSIO", admin_level: 100, type: "province", hierarchy_path: 'DRC.KSIO'),
  Location.new(placename_i18n: { "en": "Dungu" }, location_code:"DNG", admin_level: 100, type: "district", hierarchy_path: 'DRC.HTUL.DNG'),
  Location.new(placename_i18n: { "en": "Kananga" }, location_code:"KNA", admin_level: 100, type: "district", hierarchy_path: 'DRC.KSA.KNA'),
  Location.new(placename_i18n: { "en": "Bugendana" }, location_code:"BGE", admin_level: 100, type: "city", hierarchy_path: 'BI.GIT.BGE'),
  Location.new(placename_i18n: { "en": "Hauti Uele" }, location_code:"HTUL", admin_level: 100, type: "province", hierarchy_path: 'DRC.HTUL'),
  Location.new(placename_i18n: { "en": "Gitega" }, location_code:"GIT", admin_level: 100, type: "province", hierarchy_path: 'BI.GIT'),
  Location.new(placename_i18n: { "en": "Kasai Central" }, location_code:"KSA", admin_level: 100, type: "province", hierarchy_path: 'DRC.KSA'),
  Location.new(placename_i18n: { "en": "Yahumu" }, location_code:"YHM", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSHP.YHM'),
  Location.new(placename_i18n: { "en": "Tshikapa" }, location_code:"TSI", admin_level: 100, type: "district", hierarchy_path: 'DRC.KSI.TSI'),
  Location.new(placename_i18n: { "en": "Kasai" }, location_code:"KSI", admin_level: 100, type: "province", hierarchy_path: 'DRC.KSI'),
  Location.new(placename_i18n: { "en": "Ubundu" }, location_code:"UBD", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSHP.UBD'),
  Location.new(placename_i18n: { "en": "Opala" }, location_code:"OPL", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSHP.OPL'),
  Location.new(placename_i18n: { "en": "Rugombo" }, location_code:"RUG", admin_level: 100, type: "city", hierarchy_path: 'BI.CIB.RUG'),
  Location.new(placename_i18n: { "en": "Isangi" }, location_code:"ISG", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSHP.ISG'),
  Location.new(placename_i18n: { "en": "Murwi" }, location_code:"MR", admin_level: 100, type: "city", hierarchy_path: 'BI.CIB.MR'),
  Location.new(placename_i18n: { "en": "Basoko" }, location_code:"BSK", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSHP.BSK'),
  Location.new(placename_i18n: { "en": "Mugina" }, location_code:"MG", admin_level: 100, type: "city", hierarchy_path: 'BI.CIB.MG'),
  Location.new(placename_i18n: { "en": "Plateaux" }, location_code:"PLA", admin_level: 100, type: "district", hierarchy_path: 'DRC.MAI.PLA'),
  Location.new(placename_i18n: { "en": "Mabayi" }, location_code:"MB", admin_level: 100, type: "city", hierarchy_path: 'BI.CIB.MB'),
  Location.new(placename_i18n: { "en": "Banalia" }, location_code:"BNL", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSHP.BNL'),
  Location.new(placename_i18n: { "en": "Bukinanyana" }, location_code:"BUK", admin_level: 100, type: "city", hierarchy_path: 'BI.CIB.BUK'),
  Location.new(placename_i18n: { "en": "Bafwasende" }, location_code:"BFWD", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSHP.BFWD'),
  Location.new(placename_i18n: { "en": "Buganda" }, location_code:"BUG", admin_level: 100, type: "city", hierarchy_path: 'BI.CIB.BUG'),
  Location.new(placename_i18n: { "en": "Inongo" }, location_code:"INo", admin_level: 100, type: "district", hierarchy_path: 'DRC.MAI.INo'),
  Location.new(placename_i18n: { "en": "Cibitoke" }, location_code:"CIB", admin_level: 100, type: "province", hierarchy_path: 'BI.CIB'),
  Location.new(placename_i18n: { "en": "Kisangani" }, location_code:"KSGN", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSHP.KSGN'),
  Location.new(placename_i18n: { "en": "Mai Ndombe" }, location_code:"MAI", admin_level: 100, type: "province", hierarchy_path: 'DRC.MAI'),
  Location.new(placename_i18n: { "en": "Vyanda" }, location_code:"VY", admin_level: 100, type: "city", hierarchy_path: 'BI.BRU.VY'),
  Location.new(placename_i18n: { "en": "Songa" }, location_code:"SNG", admin_level: 100, type: "city", hierarchy_path: 'BI.BRU.SNG'),
  Location.new(placename_i18n: { "en": "Masi-Manimba" }, location_code:"MAS", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWI.MAS'),
  Location.new(placename_i18n: { "en": "Tshopo" }, location_code:"TSHP", admin_level: 100, type: "province", hierarchy_path: 'DRC.TSHP'),
  Location.new(placename_i18n: { "en": "Mangai" }, location_code:"MAN", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWI.MAN'),
  Location.new(placename_i18n: { "en": "Idiofa" }, location_code:"IDI", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWI.IDI'),
  Location.new(placename_i18n: { "en": "Rutovu" }, location_code:"RUT", admin_level: 100, type: "city", hierarchy_path: 'BI.BRU.RUT'),
  Location.new(placename_i18n: { "en": "Gungu" }, location_code:"GUN", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWI.GUN'),
  Location.new(placename_i18n: { "en": "Mugamba" }, location_code:"MGU", admin_level: 100, type: "city", hierarchy_path: 'BI.BRU.MGU'),
  Location.new(placename_i18n: { "en": "Bagata" }, location_code:"BAG", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWI.BAG'),
  Location.new(placename_i18n: { "en": "Kikwit" }, location_code:"KIK", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWI.KIK'),
  Location.new(placename_i18n: { "en": "Matana" }, location_code:"MTA", admin_level: 100, type: "city", hierarchy_path: 'BI.BRU.MTA'),
  Location.new(placename_i18n: { "en": "Poko" }, location_code:"PK", admin_level: 100, type: "district", hierarchy_path: 'DRC.BUL.PK'),
  Location.new(placename_i18n: { "en": "Kwilu" }, location_code:"KWI", admin_level: 100, type: "province", hierarchy_path: 'DRC.KWI'),
  Location.new(placename_i18n: { "en": "Bururi" }, location_code:"BRU", admin_level: 100, type: "province", hierarchy_path: 'BI.BRU'),
  Location.new(placename_i18n: { "en": "Buta" }, location_code:"BUT", admin_level: 100, type: "district", hierarchy_path: 'DRC.BUL.BUT'),
  Location.new(placename_i18n: { "en": "Popokabaka" }, location_code:"POP", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWA.POP'),
  Location.new(placename_i18n: { "en": "Bondo" }, location_code:"BNDO", admin_level: 100, type: "district", hierarchy_path: 'DRC.BUL.BNDO'),
  Location.new(placename_i18n: { "en": "Kasongo Lunda" }, location_code:"KASO", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWA.KASO'),
  Location.new(placename_i18n: { "en": "Bambensa" }, location_code:"BMBS", admin_level: 100, type: "district", hierarchy_path: 'DRC.BUL.BMBS'),
  Location.new(placename_i18n: { "en": "Kahemba" }, location_code:"KAH", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWA.KAH'),
  Location.new(placename_i18n: { "en": "Ango" }, location_code:"ANG", admin_level: 100, type: "district", hierarchy_path: 'DRC.BUL.ANG'),
  Location.new(placename_i18n: { "en": "Feshi" }, location_code:"FES", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWA.FES'),
  Location.new(placename_i18n: { "en": "Aketi" }, location_code:"AKT", admin_level: 100, type: "district", hierarchy_path: 'DRC.BUL.AKT'),
  Location.new(placename_i18n: { "en": "Kenge" }, location_code:"KEN", admin_level: 100, type: "district", hierarchy_path: 'DRC.KWA.KEN'),
  Location.new(placename_i18n: { "en": "Bas Uele" }, location_code:"BUL", admin_level: 100, type: "province", hierarchy_path: 'DRC.BUL'),
  Location.new(placename_i18n: { "en": "Yakoma" }, location_code:"YKM", admin_level: 100, type: "district", hierarchy_path: 'DRC.NUBG.YKM'),
  Location.new(placename_i18n: { "en": "Mobayi-Mbongo" }, location_code:"MMG", admin_level: 100, type: "district", hierarchy_path: 'DRC.NUBG.MMG'),
  Location.new(placename_i18n: { "en": "Kwango" }, location_code:"KWA", admin_level: 100, type: "province", hierarchy_path: 'DRC.KWA'),
  Location.new(placename_i18n: { "en": "Businga" }, location_code:"BSG", admin_level: 100, type: "district", hierarchy_path: 'DRC.NUBG.BSG'),
  Location.new(placename_i18n: { "en": "Bosobolo" }, location_code:"BBL", admin_level: 100, type: "district", hierarchy_path: 'DRC.NUBG.BBL'),
  Location.new(placename_i18n: { "en": "Tshela" }, location_code:"TSHE", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.BAS.TSHE'),
  Location.new(placename_i18n: { "en": "Nord Ubangi" }, location_code:"NUBG", admin_level: 100, type: "province", hierarchy_path: 'DRC.NUBG'),
  Location.new(placename_i18n: { "en": "Seke-Banza" }, location_code:"SEKE", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.BAS.SEKE'),
  Location.new(placename_i18n: { "en": "Yambuku" }, location_code:"YBK", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNGL.YBK'),
  Location.new(placename_i18n: { "en": "Lisala" }, location_code:"LSL", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNGL.LSL'),
  Location.new(placename_i18n: { "en": "Bumba" }, location_code:"BMB", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNGL.BMB'),
  Location.new(placename_i18n: { "en": "Lukula" }, location_code:"LUKU", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.BAS.LUKU'),
  Location.new(placename_i18n: { "en": "Bongandanga" }, location_code:"BGDG", admin_level: 100, type: "district", hierarchy_path: 'DRC.MNGL.BGDG'),
  Location.new(placename_i18n: { "en": "Kinzu-Mvuete" }, location_code:"KINZ", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.BAS.KINZ'),
  Location.new(placename_i18n: { "en": "Mongala" }, location_code:"MNGL", admin_level: 100, type: "province", hierarchy_path: 'DRC.MNGL'),
  Location.new(placename_i18n: { "en": "Libenge" }, location_code:"LBG", admin_level: 100, type: "district", hierarchy_path: 'DRC.SUBG.LBG'),
  Location.new(placename_i18n: { "en": "Inga" }, location_code:"ING", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.BAS.ING'),
  Location.new(placename_i18n: { "en": "Kungu" }, location_code:"KNG", admin_level: 100, type: "district", hierarchy_path: 'DRC.SUBG.KNG'),
  Location.new(placename_i18n: { "en": "Gemena" }, location_code:"GMN", admin_level: 100, type: "district", hierarchy_path: 'DRC.SUBG.GMN'),
  Location.new(placename_i18n: { "en": "Budjala" }, location_code:"BDJ", admin_level: 100, type: "district", hierarchy_path: 'DRC.SUBG.BDJ'),
  Location.new(placename_i18n: { "en": "Sud-Ubangi" }, location_code:"SUBG", admin_level: 100, type: "province", hierarchy_path: 'DRC.SUBG'),
  Location.new(placename_i18n: { "en": "Bas-Fleuve" }, location_code:"BAS", admin_level: 100, type: "district", hierarchy_path: 'DRC.KON.BAS'),
  Location.new(placename_i18n: { "en": "Ingende" }, location_code:"IGD", admin_level: 100, type: "district", hierarchy_path: 'DRC.EQTR.IGD'),
  Location.new(placename_i18n: { "en": "Bomongo" }, location_code:"BMG", admin_level: 100, type: "district", hierarchy_path: 'DRC.EQTR.BMG'),
  Location.new(placename_i18n: { "en": "Bolomba" }, location_code:"BLMB", admin_level: 100, type: "district", hierarchy_path: 'DRC.EQTR.BLMB'),
  Location.new(placename_i18n: { "en": "Songololo" }, location_code:"SON", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.CAT.SON'),
  Location.new(placename_i18n: { "en": "Makanza" }, location_code:"MKNZ", admin_level: 100, type: "district", hierarchy_path: 'DRC.EQTR.MKNZ'),
  Location.new(placename_i18n: { "en": "Mbanza-Ngungu" }, location_code:"MBA", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.CAT.MBA'),
  Location.new(placename_i18n: { "en": "Kimpese" }, location_code:"KIMP", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.CAT.KIMP'),
  Location.new(placename_i18n: { "en": "Basankusu" }, location_code:"BSNK", admin_level: 100, type: "district", hierarchy_path: 'DRC.EQTR.BSNK'),
  Location.new(placename_i18n: { "en": "Cataractes" }, location_code:"CAT", admin_level: 100, type: "district", hierarchy_path: 'DRC.KON.CAT'),
  Location.new(placename_i18n: { "en": "Lukolela" }, location_code:"LKLL", admin_level: 100, type: "district", hierarchy_path: 'DRC.EQTR.LKLL'),
  Location.new(placename_i18n: { "en": "Madimba" }, location_code:"MAD", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.RUK.MAD'),
  Location.new(placename_i18n: { "en": "Bikoro" }, location_code:"BKR", admin_level: 100, type: "district", hierarchy_path: 'DRC.EQTR.BKR'),
  Location.new(placename_i18n: { "en": "Kimvula" }, location_code:"KIMV", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.RUK.KIMV'),
  Location.new(placename_i18n: { "en": "Equateur" }, location_code:"EQTR", admin_level: 100, type: "province", hierarchy_path: 'DRC.EQTR'),
  Location.new(placename_i18n: { "en": "Kasanguru" }, location_code:"KASA", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.RUK.KASA'),
  Location.new(placename_i18n: { "en": "Inkisi" }, location_code:"INK", admin_level: 100, type: "city", hierarchy_path: 'DRC.KON.RUK.INK'),
  Location.new(placename_i18n: { "en": "Monkoto" }, location_code:"MKT", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSP.MKT'),
  Location.new(placename_i18n: { "en": "Ikela" }, location_code:"LKL", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSP.LKL'),
  Location.new(placename_i18n: { "en": "Rukaya" }, location_code:"RUK", admin_level: 100, type: "district", hierarchy_path: 'DRC.KON.RUK'),
  Location.new(placename_i18n: { "en": "Nyabiraba" }, location_code:"NYB", admin_level: 100, type: "city", hierarchy_path: 'BI.BUR.NYB'),
  Location.new(placename_i18n: { "en": "Djolu" }, location_code:"DJL", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSP.DJL'),
  Location.new(placename_i18n: { "en": "Mutimbuzi" }, location_code:"MTI", admin_level: 100, type: "city", hierarchy_path: 'BI.BUR.MTI'),
  Location.new(placename_i18n: { "en": "Bokungu" }, location_code:"BKG", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSP.BKG'),
  Location.new(placename_i18n: { "en": "Boma" }, location_code:"BOM", admin_level: 100, type: "district", hierarchy_path: 'DRC.KON.BOM'),
  Location.new(placename_i18n: { "en": "Mutambu" }, location_code:"MUT", admin_level: 100, type: "city", hierarchy_path: 'BI.BUR.MUT'),
  Location.new(placename_i18n: { "en": "Mukike" }, location_code:"MKI", admin_level: 100, type: "city", hierarchy_path: 'BI.BUR.MKI'),
  Location.new(placename_i18n: { "en": "Boende" }, location_code:"BND", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSP.BND'),
  Location.new(placename_i18n: { "en": "Matadi" }, location_code:"MATA", admin_level: 100, type: "district", hierarchy_path: 'DRC.KON.MATA'),
  Location.new(placename_i18n: { "en": "Befale" }, location_code:"BFL", admin_level: 100, type: "district", hierarchy_path: 'DRC.TSP.BFL'),
  Location.new(placename_i18n: { "en": "Mugongomanga" }, location_code:"MUG", admin_level: 100, type: "city", hierarchy_path: 'BI.BUR.MUG'),
  Location.new(placename_i18n: { "en": "Kongo Central" }, location_code:"KON", admin_level: 100, type: "province", hierarchy_path: 'DRC.KON'),
  Location.new(placename_i18n: { "en": "Tshuapa" }, location_code:"TSP", admin_level: 100, type: "province", hierarchy_path: 'DRC.TSP'),
  Location.new(placename_i18n: { "en": "Nsele" }, location_code:"NSE", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.TSH.NSE'),
  Location.new(placename_i18n: { "en": "Nyunzu" }, location_code:"NNZ", admin_level: 100, type: "district", hierarchy_path: 'DRC.TGK.NNZ'),
  Location.new(placename_i18n: { "en": "Ndjili" }, location_code:"NDJ", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.TSH.NDJ'),
  Location.new(placename_i18n: { "en": "Masina" }, location_code:"MASI", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.TSH.MASI'),
  Location.new(placename_i18n: { "en": "Moba" }, location_code:"MOB", admin_level: 100, type: "district", hierarchy_path: 'DRC.TGK.MOB'),
  Location.new(placename_i18n: { "en": "Manono" }, location_code:"MNN", admin_level: 100, type: "district", hierarchy_path: 'DRC.TGK.MNN'),
  Location.new(placename_i18n: { "en": "Kongolo" }, location_code:"KGL", admin_level: 100, type: "district", hierarchy_path: 'DRC.TGK.KGL'),
  Location.new(placename_i18n: { "en": "Maluku" }, location_code:"Mal", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.TSH.Mal'),
  Location.new(placename_i18n: { "en": "Kalemie" }, location_code:"KLM", admin_level: 100, type: "district", hierarchy_path: 'DRC.TGK.KLM'),
  Location.new(placename_i18n: { "en": "Kimbanseke" }, location_code:"KIM", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.TSH.KIM'),
  Location.new(placename_i18n: { "en": "Kabalo" }, location_code:"KBL", admin_level: 100, type: "district", hierarchy_path: 'DRC.TGK.KBL'),
  Location.new(placename_i18n: { "en": "Mubimbi" }, location_code:"MUB", admin_level: 100, type: "city", hierarchy_path: 'BI.BUR.MUB'),
  Location.new(placename_i18n: { "en": "Tshangu" }, location_code:"TSH", admin_level: 100, type: "district", hierarchy_path: 'DRC.KIN.TSH'),
  Location.new(placename_i18n: { "en": "Tanganyika" }, location_code:"TGK", admin_level: 100, type: "province", hierarchy_path: 'DRC.TGK'),
  Location.new(placename_i18n: { "en": "Kanyosha" }, location_code:"KNY", admin_level: 100, type: "city", hierarchy_path: 'BI.BUR.KNY'),
  Location.new(placename_i18n: { "en": "Kabezi" }, location_code:"KAB", admin_level: 100, type: "city", hierarchy_path: 'BI.BUR.KAB'),
  Location.new(placename_i18n: { "en": "Ngaba" }, location_code:"NGAB", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.MONT.NGAB'),
  Location.new(placename_i18n: { "en": "Isale" }, location_code:"IS", admin_level: 100, type: "city", hierarchy_path: 'BI.BUR.IS'),
  Location.new(placename_i18n: { "en": "Malemba-Nkulu" }, location_code:"MLBNKL", admin_level: 100, type: "district", hierarchy_path: 'DRC.HLMM.MLBNKL'),
  Location.new(placename_i18n: { "en": "Bujumbura Rural" }, location_code:"BUR", admin_level: 100, type: "province", hierarchy_path: 'BI.BUR'),
  Location.new(placename_i18n: { "en": "Matete" }, location_code:"MAT", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.MONT.MAT'),
  Location.new(placename_i18n: { "en": "Kaniama" }, location_code:"KNM", admin_level: 100, type: "district", hierarchy_path: 'DRC.HLMM.KNM'),
  Location.new(placename_i18n: { "en": "Limete" }, location_code:"LIM", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.MONT.LIM'),
  Location.new(placename_i18n: { "en": "Lemba" }, location_code:"LEM", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.MONT.LEM'),
  Location.new(placename_i18n: { "en": "Kamina" }, location_code:"KMN", admin_level: 100, type: "district", hierarchy_path: 'DRC.HLMM.KMN'),
  Location.new(placename_i18n: { "en": "Kisenso" }, location_code:"KIS", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.MONT.KIS'),
  Location.new(placename_i18n: { "en": "Kabongo" }, location_code:"KBG", admin_level: 100, type: "district", hierarchy_path: 'DRC.HLMM.KBG'),
  Location.new(placename_i18n: { "en": "Bukama" }, location_code:"BKM", admin_level: 100, type: "district", hierarchy_path: 'DRC.HLMM.BKM'),
  Location.new(placename_i18n: { "en": "Mont Amba" }, location_code:"MONT", admin_level: 100, type: "district", hierarchy_path: 'DRC.KIN.MONT'),
  Location.new(placename_i18n: { "en": "Hauti-Lomami" }, location_code:"HLMM", admin_level: 100, type: "province", hierarchy_path: 'DRC.HLMM'),
  Location.new(placename_i18n: { "en": "Ngaliema" }, location_code:"NGA", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.LUK.NGA'),
  Location.new(placename_i18n: { "en": "Mont Ngafula" }, location_code:"MON", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.LUK.MON'),
  Location.new(placename_i18n: { "en": "Lingwala" }, location_code:"LIN", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.LUK.LIN'),
  Location.new(placename_i18n: { "en": "Kintambo" }, location_code:"KINT", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.LUK.KINT'),
  Location.new(placename_i18n: { "en": "Kinshasa" }, location_code:"KINS", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.LUK.KINS'),
  Location.new(placename_i18n: { "en": "Gombe" }, location_code:"GOM", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.LUK.GOM'),
  Location.new(placename_i18n: { "en": "Ntahangwa-Ngagara" }, location_code:"NTNG", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.NTNG'),
  Location.new(placename_i18n: { "en": "Kalwezi" }, location_code:"KLWZ", admin_level: 100, type: "district", hierarchy_path: 'DRC.LLB.KLWZ'),
  Location.new(placename_i18n: { "en": "Barumbu" }, location_code:"BAR", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.LUK.BAR'),
  Location.new(placename_i18n: { "en": "Ntahangwa-Kinama" }, location_code:"NTKIN", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.NTKIN'),
  Location.new(placename_i18n: { "en": "Ntahangwa-Kigobe" }, location_code:"NTKI", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.NTKI'),
  Location.new(placename_i18n: { "en": "Lukunga" }, location_code:"LUK", admin_level: 100, type: "district", hierarchy_path: 'DRC.KIN.LUK'),
  Location.new(placename_i18n: { "en": "Lualaba" }, location_code:"LLB", admin_level: 100, type: "province", hierarchy_path: 'DRC.LLB'),
  Location.new(placename_i18n: { "en": "Ntahangwa-Kamenge" }, location_code:"NTKA", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.NTKA'),
  Location.new(placename_i18n: { "en": "Ntahangwa-Gihosha" }, location_code:"NTGI", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.NTGI'),
  Location.new(placename_i18n: { "en": "Selembao" }, location_code:"SEL", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.FU.SEL'),
  Location.new(placename_i18n: { "en": "Ntahangwa-Cibitoke" }, location_code:"NTCI", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.NTCI'),
  Location.new(placename_i18n: { "en": "Likasi" }, location_code:"LKS", admin_level: 100, type: "district", hierarchy_path: 'DRC.HAU.LKS'),
  Location.new(placename_i18n: { "en": "Ngiri-Ngiri" }, location_code:"NGI", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.FU.NGI'),
  Location.new(placename_i18n: { "en": "Ntahangwa-Buterere" }, location_code:"NTBU", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.NTBU'),
  Location.new(placename_i18n: { "en": "Mukaza-Rohero" }, location_code:"MURO", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.MURO'),
  Location.new(placename_i18n: { "en": "Makala" }, location_code:"MAK", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.FU.MAK'),
  Location.new(placename_i18n: { "en": "Mukaza-Nyakabiga" }, location_code:"MUNY", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.MUNY'),
  Location.new(placename_i18n: { "en": "Kasa-Vubu" }, location_code:"KA", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.FU.KA'),
  Location.new(placename_i18n: { "en": "Lubumbashi" }, location_code:"LUB", admin_level: 100, type: "district", hierarchy_path: 'DRC.HAU.LUB'),
  Location.new(placename_i18n: { "en": "Mukaza-Bwiza" }, location_code:"MUBW", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.MUBW'),
  Location.new(placename_i18n: { "en": "Mukaza-Bunyezi" }, location_code:"MUBU", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.MUBU'),
  Location.new(placename_i18n: { "en": "Muha-Musaga" }, location_code:"MUMU", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.MUMU'),
  Location.new(placename_i18n: { "en": "Haut-Katanga" }, location_code:"HAU", admin_level: 100, type: "province", hierarchy_path: 'DRC.HAU'),
  Location.new(placename_i18n: { "en": "Muha-Kinindo" }, location_code:"MUKI", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.MUKI'),
  Location.new(placename_i18n: { "en": "Kalamu" }, location_code:"KAL", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.FU.KAL'),
  Location.new(placename_i18n: { "en": "Muha-Kanyosha" }, location_code:"MUK", admin_level: 100, type: "city", hierarchy_path: 'BI.BM.MUK'),
  Location.new(placename_i18n: { "en": "Bumbu" }, location_code:"BUM", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.FU.BUM'),
  Location.new(placename_i18n: { "en": "Bujumbura Mairie" }, location_code:"BM", admin_level: 100, type: "province", hierarchy_path: 'BI.BM'),
  Location.new(placename_i18n: { "en": "Bandalungwa" }, location_code:"BAN", admin_level: 100, type: "city", hierarchy_path: 'DRC.KIN.FU.BAN'),
  Location.new(placename_i18n: { "en": "Rugazi" }, location_code:"RU", admin_level: 100, type: "city", hierarchy_path: 'BI.BU.RU'),
  Location.new(placename_i18n: { "en": "Mpanda" }, location_code:"MP", admin_level: 100, type: "city", hierarchy_path: 'BI.BU.MP'),
  Location.new(placename_i18n: { "en": "Funa" }, location_code:"FU", admin_level: 100, type: "district", hierarchy_path: 'DRC.KIN.FU'),
  Location.new(placename_i18n: { "en": "Kinshasha" }, location_code:"KIN", admin_level: 100, type: "province", hierarchy_path: 'DRC.KIN'),
  Location.new(placename_i18n: { "en": "Musigati" }, location_code:"MU", admin_level: 100, type: "city", hierarchy_path: 'BI.BU.MU'),
  Location.new(placename_i18n: { "en": "Gihanga" }, location_code:"GIH", admin_level: 100, type: "city", hierarchy_path: 'BI.BU.GIH'),
  Location.new(placename_i18n: { "en": "Bubanza" }, location_code:"BU", admin_level: 100, type: "province", hierarchy_path: 'BI.BU'),
  Location.new(placename_i18n: { "en": "Mishiha" }, location_code:"MI", admin_level: 100, type: "city", hierarchy_path: 'BI.CA.MI'),
  Location.new(placename_i18n: { "en": "Kigamba" }, location_code:"KI", admin_level: 100, type: "city", hierarchy_path: 'BI.CA.KI'),
  Location.new(placename_i18n: { "en": "Gisagara" }, location_code:"GI", admin_level: 100, type: "city", hierarchy_path: 'BI.CA.GI'),
  Location.new(placename_i18n: { "en": "Cendajuru" }, location_code:"CE", admin_level: 100, type: "city", hierarchy_path: 'BI.CA.CE'),
  Location.new(placename_i18n: { "en": "Cankuzo" }, location_code:"CA", admin_level: 100, type: "province", hierarchy_path: 'BI.CA'),
  Location.new(placename_i18n: { "en": "Protection center" }, location_code:"Protectioncenter", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.Protectioncenter'),
  Location.new(placename_i18n: { "en": "NZone 14" }, location_code:"NZone14", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone14'),
  Location.new(placename_i18n: { "en": "NZone 13" }, location_code:"NZone13", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone13'),
  Location.new(placename_i18n: { "en": "NZone 12" }, location_code:"NZone12", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone12'),
  Location.new(placename_i18n: { "en": "NZone 11" }, location_code:"NZone11", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone11'),
  Location.new(placename_i18n: { "en": "NZone 10" }, location_code:"NZone10", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone10'),
  Location.new(placename_i18n: { "en": "NZone 9" }, location_code:"NZone9", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone9'),
  Location.new(placename_i18n: { "en": "NZone 8" }, location_code:"NZone8", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone8'),
  Location.new(placename_i18n: { "en": "NZone 7" }, location_code:"NZone7", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone7'),
  Location.new(placename_i18n: { "en": "NZone 6" }, location_code:"NZone6", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone6'),
  Location.new(placename_i18n: { "en": "NZone 5" }, location_code:"NZone5", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone5'),
  Location.new(placename_i18n: { "en": "NZone 4" }, location_code:"NZone4", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone4'),
  Location.new(placename_i18n: { "en": "NZone 3" }, location_code:"NZone3", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone3'),
  Location.new(placename_i18n: { "en": "NZone 2" }, location_code:"NZone2", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone2'),
  Location.new(placename_i18n: { "en": "NZone 1" }, location_code:"NZone1", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAS.NYA.NZone1'),
  Location.new(placename_i18n: { "en": "Nyarugusu" }, location_code:"NYA", admin_level: 100, type: "camp", hierarchy_path: 'TZQ.KIG.KAS.NYA'),
  Location.new(placename_i18n: { "en": "Kasulu" }, location_code:"KAS", admin_level: 100, type: "district", hierarchy_path: 'TZQ.KIG.KAS'),
  Location.new(placename_i18n: { "en": "Zone 14" }, location_code:"Zone14", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone14'),
  Location.new(placename_i18n: { "en": "Zone 13" }, location_code:"Zone13", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone13'),
  Location.new(placename_i18n: { "en": "Zone 12" }, location_code:"Zone12", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone12'),
  Location.new(placename_i18n: { "en": "Zone 22" }, location_code:"Zone22", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone22'),
  Location.new(placename_i18n: { "en": "Zone 21" }, location_code:"Zone21", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone21'),
  Location.new(placename_i18n: { "en": "Zone 20" }, location_code:"Zone20", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone20'),
  Location.new(placename_i18n: { "en": "Zone 19" }, location_code:"Zone19", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone19'),
  Location.new(placename_i18n: { "en": "Zone 18" }, location_code:"Zone18", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone18'),
  Location.new(placename_i18n: { "en": "Zone 17" }, location_code:"Zone17", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone17'),
  Location.new(placename_i18n: { "en": "Zone 16" }, location_code:"Zone16", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone16'),
  Location.new(placename_i18n: { "en": "Zone 15" }, location_code:"Zone15", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone15'),
  Location.new(placename_i18n: { "en": "Zone 11" }, location_code:"Zone11", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone11'),
  Location.new(placename_i18n: { "en": "Zone 10" }, location_code:"Zone10", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone10'),
  Location.new(placename_i18n: { "en": "Zone 9" }, location_code:"Zone9", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone9'),
  Location.new(placename_i18n: { "en": "Zone 8" }, location_code:"Zone8", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone8'),
  Location.new(placename_i18n: { "en": "Zone 7" }, location_code:"Zone7", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone7'),
  Location.new(placename_i18n: { "en": "Zone 6" }, location_code:"Zone6", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone6'),
  Location.new(placename_i18n: { "en": "Zone 5" }, location_code:"Zone5", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone5'),
  Location.new(placename_i18n: { "en": "Zone 4" }, location_code:"Zone4", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone4'),
  Location.new(placename_i18n: { "en": "Zone 3" }, location_code:"Zone3", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone3'),
  Location.new(placename_i18n: { "en": "Zone 2" }, location_code:"Zone2", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone2'),
  Location.new(placename_i18n: { "en": "Zone 1" }, location_code:"Zone1", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KIB.NDU.Zone1'),
  Location.new(placename_i18n: { "en": "Nduta" }, location_code:"NDU", admin_level: 100, type: "camp", hierarchy_path: 'TZQ.KIG.KIB.NDU'),
  Location.new(placename_i18n: { "en": "Kibondo" }, location_code:"KIB", admin_level: 100, type: "district", hierarchy_path: 'TZQ.KIG.KIB'),
  Location.new(placename_i18n: { "en": "Zone K" }, location_code:"ZoneK", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneK'),
  Location.new(placename_i18n: { "en": "Zone J" }, location_code:"ZoneJ", admin_level: 100, type: "state", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneJ'),
  Location.new(placename_i18n: { "en": "Zone I" }, location_code:"ZoneI", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneI'),
  Location.new(placename_i18n: { "en": "Zone H" }, location_code:"ZoneH", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneH'),
  Location.new(placename_i18n: { "en": "Zone G" }, location_code:"ZoneG", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneG'),
  Location.new(placename_i18n: { "en": "Zone F" }, location_code:"ZoneF", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneF'),
  Location.new(placename_i18n: { "en": "Zone E" }, location_code:"ZoneE", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneE'),
  Location.new(placename_i18n: { "en": "Zone D" }, location_code:"ZoneD", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneD'),
  Location.new(placename_i18n: { "en": "Zone C" }, location_code:"ZoneC", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneC'),
  Location.new(placename_i18n: { "en": "Zone B" }, location_code:"ZoneB", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneB'),
  Location.new(placename_i18n: { "en": " Zone A" }, location_code:"ZoneA", admin_level: 100, type: "site", hierarchy_path: 'TZQ.KIG.KAK.MTD.ZoneA'),
  Location.new(placename_i18n: { "en": "Mtendeli " }, location_code:"MTD", admin_level: 100, type: "camp", hierarchy_path: 'TZQ.KIG.KAK.MTD'),
  Location.new(placename_i18n: { "en": "Kakonko " }, location_code:"KAK", admin_level: 100, type: "district", hierarchy_path: 'TZQ.KIG.KAK'),
  Location.new(placename_i18n: { "en": "Kigoma" }, location_code:"KIG", admin_level: 100, type: "region", hierarchy_path: 'TZQ.KIG'),
  Location.new(placename_i18n: { "en": "Turana" }, location_code:"TRN", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.TRN'),
  Location.new(placename_i18n: { "en": "Rusohoko" }, location_code:"RSHK", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.RSHK'),
  Location.new(placename_i18n: { "en": "Rugongwe" }, location_code:"RGNGW", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.RGNGW'),
  Location.new(placename_i18n: { "en": "Nyaruyoba" }, location_code:"NYRYB", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.NYRYB'),
  Location.new(placename_i18n: { "en": "Murungu" }, location_code:"MRNG", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.MRNG'),
  Location.new(placename_i18n: { "en": "Misezero" }, location_code:"MSZR", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.MSZR'),
  Location.new(placename_i18n: { "en": "Kumwambu" }, location_code:"KMWB", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.KMWB'),
  Location.new(placename_i18n: { "en": "Kumsenga" }, location_code:"KMSNG", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.KMSNG'),
  Location.new(placename_i18n: { "en": "Kizazi" }, location_code:"KZZ", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.KZZ'),
  Location.new(placename_i18n: { "en": "Kitale" }, location_code:"KTL", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.KTL'),
  Location.new(placename_i18n: { "en": "Kitahana" }, location_code:"KTHN", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.KTHN'),
  Location.new(placename_i18n: { "en": "Kibondo Urban" }, location_code:"KBUR", admin_level: 100, type: "city", hierarchy_path: 'TZQ.KIG.KIB.KBUR'),
  Location.new(placename_i18n: { "en": "Itaba" }, location_code:"ITB", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.ITB'),
  Location.new(placename_i18n: { "en": "Busunzu" }, location_code:"BSNZ", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.BSNZ'),
  Location.new(placename_i18n: { "en": "Busagara" }, location_code:"BSGR", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.BSGR'),
  Location.new(placename_i18n: { "en": "Bunyambo" }, location_code:"BNYMB", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.BNYMB'),
  Location.new(placename_i18n: { "en": "Bukabuye" }, location_code:"BKBY", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KIB.BKBY'),
  Location.new(placename_i18n: { "en": "Titye" }, location_code:"TTY", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.TTY'),
  Location.new(placename_i18n: { "en": "Rusesa" }, location_code:"RSS", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.RSS'),
  Location.new(placename_i18n: { "en": "Rungwe" }, location_code:"RNGW", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.RNGW'),
  Location.new(placename_i18n: { "en": "Ruhita" }, location_code:"RHT", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.RHT'),
  Location.new(placename_i18n: { "en": "Nyamnyusi" }, location_code:"NYMNYS", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.NYMNYS'),
  Location.new(placename_i18n: { "en": "Nyamidaho" }, location_code:"NYMDH", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.NYMDH'),
  Location.new(placename_i18n: { "en": "Nyakitonto" }, location_code:"NYKTNT", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.NYKTNT'),
  Location.new(placename_i18n: { "en": "Muzye" }, location_code:"MZY", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.MZY'),
  Location.new(placename_i18n: { "en": "Murufiti" }, location_code:"MRFT", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.MRFT'),
  Location.new(placename_i18n: { "en": "Muhunga" }, location_code:"MHNGA", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.MHNGA'),
  Location.new(placename_i18n: { "en": "Msambara" }, location_code:"MSMBR", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.MSMBR'),
  Location.new(placename_i18n: { "en": "Kwaga" }, location_code:"KWG", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.KWG'),
  Location.new(placename_i18n: { "en": "Kitanga" }, location_code:"KTNG", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.KTNG'),
  Location.new(placename_i18n: { "en": "Kitagata" }, location_code:"KTGT", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.KTGT'),
  Location.new(placename_i18n: { "en": "Kilelema" }, location_code:"KLLMA", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.KLLMA'),
  Location.new(placename_i18n: { "en": "Kigondo" }, location_code:"KGNDO", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.KGNDO'),
  Location.new(placename_i18n: { "en": "Kagera Nkanda " }, location_code:"KGRNK", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.KGRNK'),
  Location.new(placename_i18n: { "en": "Janda" }, location_code:"JNDA", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.JNDA'),
  Location.new(placename_i18n: { "en": "Heru Ushingo" }, location_code:"HRUSHNG", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.HRUSHNG'),
  Location.new(placename_i18n: { "en": "Buhoro" }, location_code:"BHR", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAS.BHR'),
  Location.new(placename_i18n: { "en": "Rugenge" }, location_code:"RGNG", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.RGNG'),
  Location.new(placename_i18n: { "en": "Nyamtukuza" }, location_code:"NYMTZ", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.NYMTZ'),
  Location.new(placename_i18n: { "en": "Nyabibuye" }, location_code:"NYBBY", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.NYBBY'),
  Location.new(placename_i18n: { "en": "Kanyonza" }, location_code:"KNYNZ", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.KNYNZ'),
  Location.new(placename_i18n: { "en": "Muhange" }, location_code:"MHNG", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.MHNG'),
  Location.new(placename_i18n: { "en": "Mugunzu" }, location_code:"MGNZ", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.MGNZ'),
  Location.new(placename_i18n: { "en": "Kiziguzigu" }, location_code:"KZGZG", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.KZGZG'),
  Location.new(placename_i18n: { "en": "Katanga" }, location_code:"KTNGA", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.KTNGA'),
  Location.new(placename_i18n: { "en": "Kasuga" }, location_code:"KSGA", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.KSGA'),
  Location.new(placename_i18n: { "en": "Kasanda" }, location_code:"KSND", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.KSND'),
  Location.new(placename_i18n: { "en": "Gwanumpu" }, location_code:"GWNMP", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.GWNMP'),
  Location.new(placename_i18n: { "en": "Gwarama" }, location_code:"GRM", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.KAK.GRM'),
  Location.new(placename_i18n: { "en": "Rusaba" }, location_code:"RSBA", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.RSBA'),
  Location.new(placename_i18n: { "en": "Nyamugali" }, location_code:"NYMGL", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.NYMGL'),
  Location.new(placename_i18n: { "en": "Mwayaya" }, location_code:"MWYY", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.MWYY'),
  Location.new(placename_i18n: { "en": "Muyama" }, location_code:"MYM", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.MYM'),
  Location.new(placename_i18n: { "en": "Munzeze" }, location_code:"MNZZ", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.MNZZ'),
  Location.new(placename_i18n: { "en": "Munyegera" }, location_code:"MNGR", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.MNGR'),
  Location.new(placename_i18n: { "en": "Munanila" }, location_code:"MNNL", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.MNNL'),
  Location.new(placename_i18n: { "en": "Muhinda" }, location_code:"MHND", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.MHND'),
  Location.new(placename_i18n: { "en": "Mugera" }, location_code:"MGRA", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.MGRA'),
  Location.new(placename_i18n: { "en": "Kilelema" }, location_code:"KLLM", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.KLLM'),
  Location.new(placename_i18n: { "en": "Kibande" }, location_code:"KBND", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.KBND'),
  Location.new(placename_i18n: { "en": "Kajana" }, location_code:"KJN", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.KJN'),
  Location.new(placename_i18n: { "en": "Janda" }, location_code:"JAND", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.JAND'),
  Location.new(placename_i18n: { "en": "Biharu" }, location_code:"BHRU", admin_level: 100, type: "village", hierarchy_path: 'TZQ.KIG.BHGWE.BHRU'),
  Location.new(placename_i18n: { "en": "Uvinza" }, location_code:"UVNZ", admin_level: 100, type: "district", hierarchy_path: 'TZQ.KIG.UVNZ'),
  Location.new(placename_i18n: { "en": "Ujiji" }, location_code:"UJJ", admin_level: 100, type: "district", hierarchy_path: 'TZQ.KIG.UJJ'),
  Location.new(placename_i18n: { "en": "Buhigwe" }, location_code:"BHGWE", admin_level: 100, type: "district", hierarchy_path: 'TZQ.KIG.BHGWE'),
]

Location.locations_by_code = locations.map { |l| [l.location_code, l] }.to_h
locations.each(&:name_from_hierarchy)
locations.each do |loc|
  puts "Creating location #{loc.location_code}"
  loc.save!
rescue ActiveRecord::RecordNotUnique
  puts "Skipping. Location #{loc.location_code} already exists!"
rescue StandardError => e
  puts "Cannot create #{loc.location_code}. Error #{e.message}"
  raise e
end
