FormSection.create_or_update!(
  {
    name_en: "Child Under 5",
    description_en: "Child Under 5",
    name_fr: "Enfant de moins de 5 ans",
    description_fr: "",
    unique_id: "child_under_5",
    parent_form: "case",
    visible: true,
    order: 40,
    order_form_group: 40,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "identification_registration",
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "date_child_found",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date child was found",
        help_text_en: "",
        display_name_fr: "Date à laquelle l'enfant a été trouvé",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        date_validation: "default_date_validation"
      },
      {
        name: "location_child_found",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Location where child was found",
        help_text_en: "",
        display_name_fr: "Lieu où l'enfant a été retrouvé",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "address_child_found",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Found in Village/Area/Physical Address",
        help_text_en: "",
        display_name_fr: "Trouvé dans le village / la région / l'adresse physique",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "found_child_details",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Please describe in detail how the child was found or taken in the family/children's center",
        help_text_en: "",
        display_name_fr: "Veuillez décrire en détail comment l'enfant a été retrouvé ou emmené dans le centre pour enfants / famille",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "location_found_child_people_was_with",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Where are the people who were part of the group that was displaced at the same time?",
        help_text_en: "",
        display_name_fr: "Où sont les personnes qui faisaient partie du groupe qui a été déplacé au même moment?",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "address_found_child_people_was_with",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Village/Area/Physical Address",
        help_text_en: "",
        display_name_fr: "Village / Zone / Adresse physique",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_finder",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Name of person who gave the child to the family/children's center?",
        help_text_en: "",
        display_name_fr: "Nom de la personne qui a donné l'enfant au centre familial / pour enfants?",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relationship_child_finder",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "What is this person's relationship to the child?",
        help_text_en: "ok",
        display_name_fr: "Quelle est la relation de cette personne avec l'enfant?",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "location_child_finder",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Location of person who found the child",
        help_text_en: "",
        display_name_fr: "Lieu de la personne qui a trouvé l'enfant",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "address_child_finder",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Address of person who found the child",
        help_text_en: "",
        display_name_fr: "Adresse de la personne qui a trouvé l'enfant",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_finder_notes",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If that person's address is not known, how could we find him or her and/or provide name(s) and address(es) who may know the person who found the child?",
        help_text_en: "",
        display_name_fr: "Si l'adresse de cette personne n'est pas connue, comment pourrions-nous la trouver et / ou lui fournir un nom et une adresse susceptibles de connaître la personne qui a trouvé l'enfant?",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_belongings",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Are there any clothes and belongings the child was found with?",
        help_text_en: "",
        display_name_fr: "Y a-t-il des vêtements et des affaires avec lesquels l'enfant a été retrouvé?",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_belongings_details",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Please list and describe ",
        help_text_en: "including medals, bracelets, hair ties, etc.",
        display_name_fr: "Veuillez énumérer et décrire",
        help_text_fr: " y compris les médailles, bracelets, cravates, etc.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_stories_songs_words",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Please write down any stories, songs, words, most often repeated by the child",
        help_text_en: "",
        display_name_fr: "S'il vous plaît écrivez des histoires, des chansons, des mots, le plus souvent répété par l'enfant",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_accent_details",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If the child speaks with an accent and if the family separation has been short (few months), from what region do you think the child comes from?",
        help_text_en: "",
        display_name_fr: "Si l'enfant parle avec un accent et si la séparation de la famille a été courte (quelques mois), de quelle région pensez-vous que l'enfant vient?",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_specific_behavior",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Please write down any behavior specific to the child that may help a parent identify him/her later on such as child's games, and main interests or specific things he/she likes to do",
        help_text_en: "",
        display_name_fr: "Notez par écrit tout comportement spécifique à l'enfant qui pourrait aider un parent à l'identifier ultérieurement, tel que les jeux de l'enfant et les intérêts principaux ou des choses spécifiques qu'il aime pratiquer",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

