FormSection.create_or_update!(
  {
    name_en: "Partner/Spouse Details",
    description_en: "Partner/Spouse Details",
    name_fr: "Détails partenaire / conjoint",
    description_fr: "",
    unique_id: "partner_details",
    parent_form: "case",
    visible: false,
    order: 20,
    order_form_group: 140,
    order_subform: 0,
    form_group_keyed: false,
    form_group_id: "referrals_transfers",
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    subform_append_only: false,
    fields_attributes: [
      {
        name: "maritial_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Current Civil/Marital Status",
        help_text_en: "",
        display_name_fr: "État civil / matrimonial actuel",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-marital-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "partner_details",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Partner/Spouse Details",
        help_text_en: "",
        display_name_fr: "Détails partenaire / conjoint",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relationship_length",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Length of Marriage/Relationship",
        help_text_en: "",
        display_name_fr: "Durée du mariage / relation",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "number_of_children",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Number of Children",
        help_text_en: "",
        display_name_fr: "Nombre d'enfants",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "marital_status_during_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Marital Status During Separation",
        help_text_en: "",
        display_name_fr: "État matrimonial pendant la séparation",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-marital-status-with-spouse",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "partner_details_during_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Partner/Spouse Details During Separation",
        help_text_en: "",
        display_name_fr: "Détails sur le partenaire / conjoint pendant la séparation",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relationship_length_during_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Length of Marriage/Relationship During Separation",
        help_text_en: "",
        display_name_fr: "Durée du mariage / de la relation pendant la séparation",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "number_of_children_during_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Number of Children During Separation",
        help_text_en: "",
        display_name_fr: "Nombre d'enfants pendant la séparation",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "marital_status_pre_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Marital Status Prior to Separation",
        help_text_en: "",
        display_name_fr: "État matrimonial avant la séparation",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-marital-status-with-spouse",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "partner_details_pre_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Partner/Spouse Details Prior to Separation",
        help_text_en: "",
        display_name_fr: "Renseignements sur le partenaire / conjoint avant la séparation",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relationship_length_pre_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Length of Marriage/Relationship Prior to Separation",
        help_text_en: "",
        display_name_fr: "Durée du mariage / de la relation avant la séparation",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "number_of_children_pre_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Number of Children Prior to Separation",
        help_text_en: "",
        display_name_fr: "Nombre d'enfants avant la séparation",
        help_text_fr: "",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

