FormSection.create_or_update!(
  {
    name_en: "CP Incident",
    description_en: "CP Incident",
    name_fr: "CP Incident",
    description_fr: "CP Incident",
    name_ar: "CP Incident",
    description_ar: "CP Incident",
    'name_ar-LB': "CP Incident",
    'description_ar-LB': "CP Incident",
    name_es: "CP Incident",
    description_es: "CP Incident",
    unique_id: "cp_incident_form",
    parent_form: "incident",
    visible: true,
    order: 10,
    order_form_group: 10,
    order_subform: 0,
    form_group_keyed: false,
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: true,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    form_group_id: "cp_incident",
    fields_attributes: [
      {
        name: "cp_case_id",
        visible: false,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Long ID",
        display_name_fr: "Long ID",
        display_name_ar: "Long ID",
        'display_name_ar-LB': "Long ID",
        display_name_es: "Long ID",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "short_id",
        visible: true,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Short ID",
        display_name_fr: "Short ID",
        display_name_ar: "Short ID",
        'display_name_ar-LB': "Short ID",
        display_name_es: "Short ID",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Incident Status",
        display_name_fr: "Incident Status",
        display_name_ar: "Incident Status",
        'display_name_ar-LB': "Incident Status",
        display_name_es: "Incident Status",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-incident-status",
        autosum_total: false,
        autosum_group: "",
        selected_value: "open",
        required: false
      },
      {
        name: "cp_incident_identification_violence",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Identification of Violence Case",
        display_name_fr: "Identification of Violence Case",
        display_name_ar: "Identification of Violence Case",
        'display_name_ar-LB': "Identification of Violence Case",
        display_name_es: "Identification of Violence Case",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-incident-identification",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "incident_date",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of Incident",
        display_name_fr: "Date of Incident",
        display_name_ar: "Date of Incident",
        'display_name_ar-LB': "Date of Incident",
        display_name_es: "Date of Incident",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_location_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Area of the Incident",
        display_name_fr: "Area of the Incident",
        display_name_ar: "Area of the Incident",
        'display_name_ar-LB': "Area of the Incident",
        display_name_es: "Area of the Incident",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-incident-location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_location_type_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If 'Other', please specify",
        display_name_fr: "If 'Other', please specify",
        display_name_ar: "If 'Other', please specify",
        'display_name_ar-LB': "If 'Other', please specify",
        display_name_es: "If 'Other', please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "incident_location",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Location of the Incident",
        display_name_fr: "Location of the Incident",
        display_name_ar: "Location of the Incident",
        'display_name_ar-LB': "Location of the Incident",
        display_name_es: "Location of the Incident",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_timeofday",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Time of Incident",
        display_name_fr: "Time of Incident",
        display_name_ar: "Time of Incident",
        'display_name_ar-LB': "Time of Incident",
        display_name_es: "Time of Incident",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-time-of-day",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_timeofday_actual",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Please specify the actual time of the Incident",
        display_name_fr: "Please specify the actual time of the Incident",
        display_name_ar: "Please specify the actual time of the Incident",
        'display_name_ar-LB': "Please specify the actual time of the Incident",
        display_name_es: "Please specify the actual time of the Incident",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_violence_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Type of Violence",
        display_name_fr: "Type of Violence",
        display_name_ar: "Type of Violence",
        'display_name_ar-LB': "Type of Violence",
        display_name_es: "Type of Violence",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-cp-violence-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_previous_incidents",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Has the case been previously abused?",
        display_name_fr: "Has the case been previously abused?",
        display_name_ar: "Has the case been previously abused?",
        'display_name_ar-LB': "Has the case been previously abused?",
        display_name_es: "Has the case been previously abused?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_previous_incidents_description",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If yes please describe in brief",
        display_name_fr: "If yes please describe in brief",
        display_name_ar: "If yes please describe in brief",
        'display_name_ar-LB': "If yes please describe in brief",
        display_name_es: "If yes please describe in brief",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

