FormSection.create_or_update!(
  {
    name_en: "Perpetrator Details",
    description_en: "Perpetrator Details",
    name_fr: "Perpetrator Details",
    description_fr: "Perpetrator Details",
    name_ar: "Perpetrator Details",
    description_ar: "Perpetrator Details",
    'name_ar-LB': "Perpetrator Details",
    'description_ar-LB': "Perpetrator Details",
    name_es: "Perpetrator Details",
    description_es: "Perpetrator Details",
    unique_id: "cp_offender_details",
    parent_form: "incident",
    visible: true,
    order: 15,
    order_form_group: 20,
    order_subform: 0,
    form_group_keyed: false,
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    form_group_id: "perpetrator_details",
    fields_attributes: [
      {
        name: "cp_incident_abuser_name",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Name",
        display_name_fr: "Name",
        display_name_ar: "Name",
        'display_name_ar-LB': "Name",
        display_name_es: "Name",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_nationality",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Nationality",
        display_name_fr: "Nationality",
        display_name_ar: "Nationality",
        'display_name_ar-LB': "Nationality",
        display_name_es: "Nationality",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-country",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "perpetrator_sex",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Sex",
        display_name_fr: "Sex",
        display_name_ar: "Sex",
        'display_name_ar-LB': "Sex",
        display_name_es: "Sex",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-gender",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_age",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Age",
        display_name_fr: "Age",
        display_name_ar: "Age",
        'display_name_ar-LB': "Age",
        display_name_es: "Age",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_national_id_no",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "National ID Number",
        display_name_fr: "National ID Number",
        display_name_ar: "National ID Number",
        'display_name_ar-LB': "National ID Number",
        display_name_es: "National ID Number",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_other_id_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Type of Other ID Document",
        display_name_fr: "Type of Other ID Document",
        display_name_ar: "Type of Other ID Document",
        'display_name_ar-LB': "Type of Other ID Document",
        display_name_es: "Type of Other ID Document",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_other_id_no",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Number of Other ID Document",
        display_name_fr: "Number of Other ID Document",
        display_name_ar: "Number of Other ID Document",
        'display_name_ar-LB': "Number of Other ID Document",
        display_name_es: "Number of Other ID Document",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_marital_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Social Status",
        display_name_fr: "Social Status",
        display_name_ar: "Social Status",
        'display_name_ar-LB': "Social Status",
        display_name_es: "Social Status",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-marital-status",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_occupation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Occupation",
        display_name_fr: "Occupation",
        display_name_ar: "Occupation",
        'display_name_ar-LB': "Occupation",
        display_name_es: "Occupation",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "cp_incident_perpetrator_relationship",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Relationship with the abused",
        display_name_fr: "Relationship with the abused",
        display_name_ar: "Relationship with the abused",
        'display_name_ar-LB': "Relationship with the abused",
        display_name_es: "Relationship with the abused",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-perpetrator-relationship",
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

