FormSection.create_or_update!(
  {
    name_en: "Nested Care Arrangements",
    description_en: "Care Arrangements Subform",
    name_so: "Qorshaha Daryeelka Xidhan",
    description_so: "Foomka Qorshaha Daryeelka",
    unique_id: "care_arrangements_section",
    parent_form: "case",
    visible: false,
    order: 10,
    order_form_group: 110,
    order_subform: 1,
    form_group_keyed: false,
    editable: true,
    core_form: true,
    is_nested: true,
    is_first_tab: false,
    initial_subforms: 1,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    collapsed_field_names: [
      "care_arrangements_type",
      "name_caregiver"
    ],
    fields_attributes: [
      {
        name: "care_arrangements_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "What are the child's current care arrangements?",
        display_name_so: "Waa maxay qorshaha daryeelka Ilmaha ee hadda taagan?",
        option_strings_text_en: [
          {
            id: "headed_household",
            display_text: "Headed Household"
          },
          {
            id: "living_alone",
            display_text: "Living Alone"
          },
          {
            id: "interim_care_center",
            display_text: "Interim Care Center"
          },
          {
            id: "foster_family",
            display_text: "Foster Family"
          },
          {
            id: "other_relatives",
            display_text: "Other Relatives / Adults"
          },
          {
            id: "living_on_street",
            display_text: "Living on the Street"
          },
          {
            id: "kinship_care",
            display_text: "Kinship Care"
          },
          {
            id: "parent",
            display_text: "Parent(s)"
          },
          {
            id: "step_parent",
            display_text: "Step parent(s)"
          },
          {
            id: "customary_caregivers",
            display_text: "Customary caregivers"
          },
          {
            id: "residential_care",
            display_text: "Residential care"
          },
          {
            id: "kafala",
            display_text: "Kafala"
          },
          {
            id: "unrelated_adult",
            display_text: "Unrelated adult(s)"
          },
          {
            id: "other",
            display_text: "Other (specify)"
          }
        ],
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangements_if_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "name_caregiver",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Name of Current Caregiver",
        display_name_so: "Magaca Daryeelaha Hadda",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relationship_caregiver",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Relationship of the Caregiver to the Child",
        display_name_so: "Xidhiidhka Ka Dhexeeya Daryeelaha iyo Ilmaha",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-family-relationship",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relationship_caregiver_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "caregiver_id_type_and_no",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Caregiver's Identification - Type and Number",
        display_name_so: "Aqoonsiga Daryeelaha- Nooca iyo Lambarka",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "caregiver_age",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Caregiver's Age",
        display_name_so: "Da'da Daryeelaha",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "telephone_caregiver",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Caregiver's Telephone",
        display_name_so: "Tilifoonka Daryeelaha",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_caregiver_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Is this a same caregiver as was previously entered for the child?",
        display_name_so: "Daryeelahani ma kii hore ee ilmaha uun baa?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_caregiver_reason_change",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "If this is a new caregiver, give the reason for the change",
        display_name_so: "Haddii kani yahay daryeele cusub, sheeg sababta isbedelka keentay?",
        option_strings_text_en: [
          {
            id: "abuse_exploitation",
            display_text: "Abuse \u0026 Exploitation"
          },
          {
            id: "death_of_caregiver",
            display_text: "Death of Caregiver"
          },
          {
            id: "Education",
            display_text: "Education"
          },
          {
            id: "ill_health_of_caregiver",
            display_text: "Ill health of caregiver"
          },
          {
            id: "other",
            display_text: "Other"
          },
          {
            id: "poverty",
            display_text: "Poverty"
          },
          {
            id: "relationship_breakdown",
            display_text: "Relationship Breakdown"
          }
        ],
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "location_caregiver",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "What is the location of the care arrangement?",
        display_name_so: "Waa halkee goobta qorsheynta daryeelku?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "address_caregiver",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What is the address of the care arrangement?",
        display_name_so: "Waa halkee cinwaanka qorsheynta daryeelku?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_reason",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What is the reason for the care arrangement?",
        display_name_so: "Waa maxay sababta qorsheynta daryeelku?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_started_date",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "What date did the child enter the care arrangement?",
        display_name_so: "Taarikhdee ayuu ilmuhu soo galay qorsheynta daryeelka?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangements_type_notes",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Care Arrangement Notes",
        display_name_so: "Warbixin ku saabsan Qorsheynta Daryeelka",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "caregiver_location_status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Is the caregiver's current location temporary",
        display_name_so: "Goobta uu daryeeluhu joogaa ma ku-meel-gaadhbaa?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "address_caregiver_future",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If yes, what is the future address?",
        display_name_so: "Haddii ay jawaabtu tahay haa, waa halkee cinwaankaaga rasmiga ahi?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "location_caregiver_future",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "What is the future location?",
        display_name_so: "Waa halkee goobta rasmiga ahi?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "telephone_caregiver_future",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "What is the future telephone?",
        display_name_so: "Ii sheeg tilifoonkaaga rasmiga ah?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "caregiver_willing_to_continue",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Is caregiver willing to continue taking care of the child?",
        display_name_so: "Daryeeluhu ma rabaa inuu sii wado daryeelka ilmaha?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "caregiver_willing_to_continue_for_how_long",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If yes, for how long?",
        display_name_so: "Hadii ay jawaabtu tahay haa, muddo intee leeg?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_will_move",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child or family have plans to move to another location?",
        display_name_so: "Miyay ilmaha amma qoysku leeyihiin qorshe ay meel/goob kale ugu guurayaan?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_stay_with_family",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "If so, will child remain with the family?",
        display_name_so: "Haddii ay meel/goob kale u guurayaan, ilmuhu qoyska ma la sii joogayaa?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_will_move_location",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "If so, where?",
        display_name_so: "Haddii ay sidaas tahay, halkee/goobtee/meeshee?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_will_move_address",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If so, what is the future address?",
        display_name_so: "Haddii ay sidaas tahay, waa halkee cinwaanka rasmiga ahi?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_alternative_care",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Is it necessary to seek alternative care/living arrangements for the child?",
        display_name_so: "Miyay lagama-maarmaan tahay in ilmaha loo raadiyo daryeel kale/qorsheyn nololeed?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_alternative_care_support",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What support would be needed to make this possible and appropriate?",
        display_name_so: "Taageero noocee ah ayaa loo baahan yahay si arrintan loo hirgaliyo loogana dhigo mid ku haboon?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "caregiver_know_family",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the caregiver know the family of the child?",
        display_name_so: "Daryeeluhu miyuu garanayaa qoyska ilmaha?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "other_information_from_caregiver",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Other information from the caregiver about the child and his/her family",
        display_name_so: "Xog kale oo laga heli karo daryeelaha oo ku saabsan ilmaha qoyskiisa/qoyskeeda?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_siblings",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child have siblings in the same care arrangement?",
        display_name_so: "Miyuu ilmuhu leeyahay walaalo kula jira qorshaha daryeelka?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_children",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "If the child has children, are they in the same care arrangement?",
        display_name_so: "Haddii uu ilmuhu carruur leeyahay, miyay kuwada jiraan qorshaha daryeelka?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_screening",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Was a thorough screening done of child and family before the child was admitted into care?",
        display_name_so: "Miyaa ilmaha iyo qoyska lagu sameeyay baadhitaan qoto-dheer intaan ilmaha loo ogolaan daryeelka?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_screening_findings",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If yes, what were the key findings?",
        display_name_so: "Haddii ay jawaabtu tahay haa, maxay ahaayeen natiijooyinka muhiimka ahi?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_review",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Has there been a formal review of the care placement before 12 weeks?",
        display_name_so: "Miyaa lagu sameeyay dib u eegis rasmi ah meelaynta daryeelka 12 wiig/usbuuc ka hor?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_review_findings",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If yes, what were the key recommendations?",
        display_name_so: "Haddii ay jawaabtu tahay haa, maxay ahaayeen talooyinkii ugu muhiimsanaa?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_case_plan",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child have an individual case plan?",
        help_text_en: "For details on the case plan, see the Case Plan form.",
        display_name_so: "Ilmuhu miyuu leeyahay qorshe kiiseed keli ah?",
        help_text_so: "Wixii faahfaahin ah ee la xidhiidha qorshaha kiiska, eeg foomka qorshaha kiiska?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangement_case_plan_participation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "If yes, did the child participate in the development of the plan?",
        display_name_so: "Hadii ay jawaabtu tahay haa, miyuu ilmuhu ka qayb-qaatay samaynta qorshaha?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangements_institutional_header",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Questions Related to Institutional Care",
        display_name_so: "Su'aalaha la xidhiidha daryeelka hay'adaha?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_name",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Name of institution",
        display_name_so: "Magaca hay'ada?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_registered",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Is the institution registered?",
        display_name_so: "Miyay hay'adu diiwaan gashan tahay?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_inspected",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Is the institution regularly inspected?",
        display_name_so: "Miyaa hay'ada si joogto ah loo kormeeraa?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_inspected_whom",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If yes, who by?",
        display_name_so: "Haddii ay jawaabtu tahay haa, yaa kormeera?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_comply_standards",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the institution comply with national/international minimum standards?",
        display_name_so: "Hay'adu miyay raacdaa standardka/heerka ugu yar ee qaranka/caalamiga ah?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_standards_action",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If no, outline main concerns and any urgent action required to address these.",
        display_name_so: "Haddii ay jawaabtu tahay maya, sheeg dhibaatooyinka ugu waawen iyo ficilka degdega ah ee loo baahan yahay si arrintan wax looga qabto.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_children_tally",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "How many children are living in the institution?",
        display_name_so: "Imisa carruur ah ayaa ku nool hay'adan?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_children_tally_boys",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Boys",
        display_name_so: "Innamo",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_children_tally_girls",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Girls",
        display_name_so: "Hablo",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_age_range",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "What is the age range?",
        display_name_so: "Intay da'doodu u dhaxaysaa?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_staff_children",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "How many staff are assigned specifically for the care of children?",
        display_name_so: "Imisa shaqaale ah ayaa si gaara loogu qoondeeyay daryeelka carruurta?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_child_caregiver_ratio",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "What is the child/caregiver ratio?",
        display_name_so: "Waa imisa saamiga u dhexeeya ilmaha iyo daryeelaha? Yacni imisa carruura ayuu daryeelihiiba masuul ka yahay?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_sleep_arrangements",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Are there separate sleeping arrangements for adolescent girls and boys?",
        display_name_so: "Ma kala duwan yihiin meelaha ay hablaha iyo innamada dhalinyarada ahi seexdaan?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_agency_schooling",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Is the child attending school in the institution or in the community?",
        display_name_so: "Ilmuhu ma wuxuu dhigtaa dugsiga hay'ada mise ka bulshada?",
        option_strings_text_en: [
          {
            id: "institution",
            display_text: "Institution"
          },
          {
            id: "community",
            display_text: "Community"
          }
        ],
        option_strings_text_so: [
          {
            id: "institution",
            display_text: "Hay'ad"
          },
          {
            id: "community",
            display_text: "Bulsho"
          }
        ],
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "For children in detention facilities",
        display_name_so: "Ku saabsan carruurta lagu hayo xabsiyada",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_name",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Name of detention facility",
        display_name_so: "Magaca xarunta xabsiga",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_capacity",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "What is the capacity of the detention facility?",
        display_name_so: "Awooda ay leedahay xarunta xabsigu",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_child_care",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What facilities for age appropriate child care exist in the place of detention? (mother / infant health, nursery, recreation, education, etc)",
        help_text_en: "If detained with adults",
        display_name_so: "Xarunta ilmaha lagu hayo ma tahay meel ku haboon da'da ku jirta? (hooyada/caafimaadka ilmaha, xannaanada carruurta, madadaalada, waxbarashada, iwm)",
        help_text_so: "Haddii lala xidhay dadka waaweyn",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_population",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "How many people are currently held in the detention facility?  ",
        display_name_so: "Imisa qof ayaa hadda ku jira xarunta xabsiga?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_privacy",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What opportunities does the child have for privacy in detention?  (is child able to bath and use toilet alone, does child have sleeping space, is child able to keep their belongings safely?)",
        display_name_so: "Fursado intee leeg ayuu ilmuhu u haystaa inuu arrimihiisa qarsan karo intuu ku jiro  xabsiga? Ilmuhu ma maydhan karaa, suuliga keligii ma isticimaali karaa, meel uu ilmuhu seexdo ma haystaa, ilmuhu alaabtiisa ma ilaashan karaa?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_needs_met",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What does the child say about his / her treatment in detention? (is child receiving basic needs, does child report physical or verbal abuse from other detainees or guards, is solitary confinement used.",
        display_name_so: "Muxuu ka yidhi ilmuhu sida loola dhaqmo xabsiga uu ku jiro? (Ilmuhu ma helaa baahiyaha aasaasiga ah, ilmuhu ma soo sheegaa haddii loo geysto tacadi jidheed/afeed oo ka soo gaadha kuwa kale ee uu la xidhan yahay amma ilaalada xabsiga, miyaa la isticimaalaa xabsi keliyeed).",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_age_facilities",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Are there separate facilities for adults / children?",
        help_text_en: "If detained with adults",
        display_name_so: "Miyay jiraan xarumo kala duwan oo loogu talo galay dadka waaweyn iyo carruurta?",
        help_text_so: "Haddii lala xidhay dad waaweyn",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_gender_toilet_facilities",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Are there separate toilet and bathing facilities for girls and boys?",
        display_name_so: "Xarumaha suuliyada iyo baadadka ee hablaha iyo innamadu ma kala soocan yihiin?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_age_toilet_facilities",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Are there separate toilet and bathing facilities for adults / children?",
        help_text_en: "If detained with adults",
        display_name_so: "Xarumaha suuliyada iyo baadadka ee dadka waaweyn iyo carruurtu ma kala soocan yihiin?",
        help_text_so: "Haddii lala xidhay dad waaweyn",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_child_risks",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Does the form of detention expose the child to any particular risks such as abuse, physical or sexual violence?",
        display_name_so: "Habka loo xidhay ilmuhu miyay u bandhigi kartaa inuu ilmuhu la kulmo khataro gaara sida tacadi, dagaal jidheed amma dagaal jinsi ahaaneed?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_education_opportunities",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What type of education / skills training opportunities are available?",
        display_name_so: "Fursado waxbarasho/xirfado noocee ah ayaa yaala?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_social_facilities",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What opportunities and facilities are there for social interaction and recreation?",
        display_name_so: "Fursado iyo xarumo ay dadku isku dhex-gelaan amma ku ciyaaraan ma jiraan?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_discipline",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What disciplinary measures are used?",
        display_name_so: "Tallaabooyin edbin oo noocee ah ayaa la isticimaalaa?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_health_facilities",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "What health facilities / referral systems are in place?",
        display_name_so: "Xarumo caafimaad/nidaamka gudbintu ma jiraan?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "detention_complaints_procedures",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Are there safe/formal/effective complaints procedures in place and does the child know how to access these?",
        display_name_so: "Ma jiraan hab ammaan ah, rasmi ah, oo si fiican u shaqeeya oo cabashada loo soo gudbisan karaa, ilmuhu se ma garanayaa sida uu u raaci lahaa habkaa?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

FormSection.create_or_update!(
  {
    name_en: "Care Arrangements",
    description_en: "Care Arrangements",
    name_so: "Qorsheynta daryeelka",
    description_so: "Qorsheynta daryeelka",
    unique_id: "care_arrangements",
    parent_form: "case",
    visible: true,
    order: 10,
    order_form_group: 70,
    order_subform: 0,
    form_group_keyed: false,
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: false,
    header_message_link: "",
    form_group_id: "assessment",
    fields_attributes: [
      {
        name: "care_arrangements_section",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "subform",
        editable: true,
        disabled: false,
        display_name_en: "Care Arrangements",
        display_name_so: "Qorsheynta daryeelka",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        subform_unique_id: "care_arrangements_section"
      }
    ]
  }
)

