# frozen_string_literal: true

basic_identity_fields = [
  Field.new('name' => 'case_id',
            'type' => 'text_field',
            'editable' => false,
            'disabled' => true,
            'display_name_en' => 'Long ID',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'short_id',
            'type' => 'text_field',
            'editable' => false,
            'disabled' => true,
            'display_name_en' => 'Short ID',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'case_id_display',
            'type' => 'text_field',
            'editable' => false,
            'disabled' => true,
            'display_name_en' => 'Case ID'),
  Field.new('name' => 'cpims_id',
            'type' => 'text_field',
            'display_name_en' => 'Previous Case Code',
            'help_text_en' => 'Legacy CPIMS (or other system) ID'),
  Field.new('name' => 'marked_for_mobile',
            'type' => 'tick_box',
            'tick_box_label_en' => 'Yes',
            'display_name_en' => 'Marked for mobile?',
            'editable' => false,
            'disabled' => true),
  Field.new('name' => 'status',
            'type' => 'select_box',
            'selected_value' => Record::STATUS_OPEN,
            'display_name_en' => 'Case Status',
            'disabled' => true,
            'option_strings_source' => 'lookup lookup-case-status'),
  Field.new('name' => 'case_status_reopened',
            'type' => 'tick_box',
            'tick_box_label_en' => 'Yes',
            'display_name_en' => 'Case Reopened?',
            'editable' => false,
            'disabled' => true),
  Field.new('name' => 'case_status_reopened_reasons',
            'type' => 'select_box',
            'multi_select' => true,
            'display_name_en' => 'Reason for Reopening',
            'option_strings_text_en' => [
              { id: 'break_down_of_reunification_placement', display_text: 'Break-down of reunification/placement' },
              { id: 'death_of_caregiver_s', display_text: 'Death of caregiver(s)' },
              { id: 'physical_abuse_violence', display_text: 'Physical abuse / violence' },
              { id: 'sexual_abuse_violence', display_text: 'Sexual abuse / violence' },
              { id: 'emotional_or_psychological_abuse_violence', display_text: 'Emotional or psychological abuse / violence' },
              { id: 'physical_neglect', display_text: 'Physical neglect' },
              { id: 'emotional_neglect', display_text: 'Emotional neglect' },
              { id: 'medical_neglect', display_text: 'Medical neglect' },
              { id: 'educational_neglect', display_text: 'Educational neglect' },
              { id: 'supervisory_neglect', display_text: 'Supervisory neglect' },
              { id: 'abandonment', display_text: 'Abandonment' },
              { id: 'child_labour', display_text: 'Child labour' },
              { id: 'hazardous_work', display_text: 'Hazardous work' },
              { id: 'sexual_exploitation', display_text: 'Sexual exploitation' },
              { id: 'slavery_sale_trafficking_forced_labour', display_text: 'Slavery / sale / trafficking / forced labour' },
              { id: 'in_conflict_with_the_law', display_text: 'In conflict with the law' },
              { id: 'associated_with_armed_forces_or_groups', display_text: 'Associated with Armed Forces or Groups' },
              { id: 'unaccompanied', display_text: 'Unaccompanied' },
              { id: 'separated', display_text: 'Separated' },
              { id: 'orphan', display_text: 'Orphan' },
              { id: 'functional_difficulties', display_text: 'Functional difficulties (e.g. seeing, hearing, walking, communicating, remembering/concentrating, self-care)' },
              { id: 'psychosocial_distress', display_text: 'Psychosocial distress' },
              { id: 'substance_abuse_and_addiction_child', display_text: 'Substance abuse and addiction (child)' },
              { id: 'belongs_to_marginalised_discriminated_group', display_text: 'Belongs to marginalised / discriminated group' },
              { id: 'lack_of_documentation_birth_registration', display_text: 'Lack of documentation / birth registration' },
              { id: 'child_marriage', display_text: 'Child marriage' },
              { id: 'fgm', display_text: 'FGM' },
              { id: 'pregnancy_child_parent', display_text: 'Pregnancy / child parent' },
              { id: 'inappropriate_care_arrangement', display_text: 'Inappropriate care arrangement (e.g. >8 children in household, caregiver’s substance abuse, single vulnerable caregiver)' },
              { id: 'other', display_text: 'Other' }
            ].map(&:with_indifferent_access)),
  Field.new('name' => 'name',
            'type' => 'text_field',
            'display_name_en' => 'Full Name',
            'required' => false,
            'show_on_minify_form' => true,
            'hidden_text_field' => true,
            'matchable' => true,
            'disabled' => true),
  Field.new('name' => 'name_first',
            'type' => 'text_field',
            'display_name_en' => 'First Name',
            'show_on_minify_form' => true,
            'required' => true,
            'hide_on_view_page' => true),
  Field.new('name' => 'name_middle',
            'type' => 'text_field',
            'display_name_en' => 'Middle Name',
            'show_on_minify_form' => true,
            'hide_on_view_page' => true),
  Field.new('name' => 'name_last',
            'type' => 'text_field',
            'display_name_en' => 'Last Name',
            'show_on_minify_form' => true,
            'required' => true,
            'hide_on_view_page' => true),
  Field.new('name' => 'name_nickname',
            'type' => 'text_field',
            'display_name_en' => 'Nickname',
            'show_on_minify_form' => true,
            'matchable' => true),
  Field.new('name' => 'name_other',
            'type' => 'text_field',
            'display_name_en' => 'Other Name',
            'matchable' => true),
  Field.new('name' => 'name_given_post_separation',
            'type' => 'radio_button',
            'display_name_en' => 'Name(s) given to child after separation?',
            'option_strings_source' => 'lookup lookup-yes-no',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'registration_date',
            'type' => 'date_field',
            'selected_value' => 'today',
            'required' => false,
            'display_name_en' => 'Date of Registration',
            'date_validation' => 'not_future_date'),
  Field.new('name' => 'identification_date',
            'type' => 'date_field',
            'selected_value' => 'today',
            'display_name_en' => 'Date Case Identified / Reported',
            'date_validation' => 'not_future_date'),
  Field.new('name' => 'assessment_due_date',
            'type' => 'date_field',
            'required' => false,
            'editable' => false,
            'display_name_en' => 'Date Assessment Due'),
  Field.new('name' => 'sex',
            'type' => 'select_box',
            'show_on_minify_form' => true,
            'required' => true,
            'display_name_en' => 'Sex',
            'option_strings_source' => 'lookup lookup-gender',
            'matchable' => true),
  Field.new('name' => 'age',
            'type' => 'numeric_field',
            'display_name_en' => 'Age',
            'show_on_minify_form' => true,
            'required' => true,
            'matchable' => true),
  Field.new('name' => 'date_of_birth',
            'type' => 'date_field',
            'display_name_en' => 'Date of Birth',
            'show_on_minify_form' => true,
            'matchable' => true),
  Field.new('name' => 'estimated',
            'type' => 'tick_box',
            'tick_box_label_en' => 'Yes',
            'show_on_minify_form' => true,
            'display_name_en' => 'Is the age estimated?'),
  Field.new('name' => 'physical_characteristics',
            'type' => 'textarea',
            'display_name_en' => 'Distinguishing Physical Characteristics',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'ration_card_no',
            'type' => 'text_field',
            'display_name_en' => 'Ration Card Number',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'icrc_ref_no',
            'type' => 'text_field',
            'display_name_en' => 'ICRC Ref No.',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'rc_id_no',
            'type' => 'text_field',
            'display_name_en' => 'RC ID No.',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'biometrics_id',
            'type' => 'text_field',
            'display_name_en' => 'Biometrics',
            'show_on_minify_form' => true,
            'help_text_en' => 'For the Biometric ID number, if used.',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'un_no',
            'type' => 'text_field',
            'display_name_en' => 'UN Number',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'national_id_no',
            'type' => 'text_field',
            'display_name_en' => 'National ID Number'),
  Field.new('name' => 'unhcr_id_no',
            'type' => 'text_field',
            'display_name_en' => 'UNHCR Registration Group Number',
            'mobile_visible' => true,
            'visible' => true),
  Field.new('name' => 'unhcr_individual_no',
            'type' => 'text_field',
            'display_name_en' => 'UNHCR Individual ID'),
  Field.new('name' => 'other_id_type',
            'type' => 'text_field',
            'display_name_en' => 'Type of other relevant ID document'),
  Field.new('name' => 'other_id_no',
            'type' => 'text_field',
            'display_name_en' => 'Number of other relevant ID'),
  Field.new('name' => 'other_agency_id',
            'type' => 'text_field',
            'display_name_en' => 'Other Agency ID',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'other_agency_name',
            'type' => 'text_field',
            'display_name_en' => 'Other Agency Name',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'documents_carried',
            'type' => 'textarea',
            'display_name_en' => 'List of documents carried by the child',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'nationality',
            'type' => 'select_box',
            'multi_select' => true,
            'display_name_en' => 'Nationality',
            'option_strings_source' => 'lookup lookup-country',
            'matchable' => true),
  Field.new('name' => 'maritial_status',
            'type' => 'select_box',
            'display_name_en' => 'Current Civil/Marital Status',
            'show_on_minify_form' => true,
            'option_strings_source' => 'lookup lookup-marital-status',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'occupation',
            'type' => 'text_field',
            'display_name_en' => 'Occupation',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'ethnicity',
            'type' => 'select_box',
            'multi_select' => true,
            'display_name_en' => 'Ethnicity/Clan/Tribe',
            'option_strings_source' => 'lookup lookup-ethnicity',
            'matchable' => true),
  Field.new('name' => 'sub_ethnicity_1',
            'type' => 'select_box',
            'multi_select' => true,
            'display_name_en' => 'Sub Ethnicity 1',
            'option_strings_source' => 'lookup lookup-ethnicity'),
  Field.new('name' => 'sub_ethnicity_2',
            'type' => 'select_box',
            'multi_select' => true,
            'display_name_en' => 'Sub Ethnicity 2',
            'option_strings_source' => 'lookup lookup-ethnicity'),
  Field.new('name' => 'language',
            'type' => 'select_box',
            'multi_select' => true,
            'display_name_en' => 'Languages spoken by child',
            'option_strings_source' => 'lookup lookup-language'),
  Field.new('name' => 'religion',
            'type' => 'select_box',
            'multi_select' => true,
            'display_name_en' => 'Religion',
            'option_strings_source' => 'lookup lookup-religion'),
  Field.new('name' => 'displacement_status',
            'type' => 'select_box',
            'display_name_en' => 'Population Group',
            'option_strings_source' => 'lookup lookup-displacement-status'),
  Field.new('name' => 'displacement_status_other',
            'type' => 'text_field',
            'display_name_en' => 'If Other, please specify'),
  Field.new('name' => 'disability_type_communications',
            'type' => 'text_field',
            'display_name_en' => 'Special communication needs'),
  Field.new('name' => 'address_current',
            'type' => 'textarea',
            'required' => false,
            'display_name_en' => 'Current Address',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'landmark_current',
            'type' => 'text_field',
            'display_name_en' => 'Landmark',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'location_current',
            'type' => 'select_box',
            'display_name_en' => 'Current Location',
            'option_strings_source' => 'Location',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'address_is_permanent',
            'type' => 'tick_box',
            'display_name_en' => 'Is this address permanent?',
            'mobile_visible' => false,
            'visible' => false),
  Field.new('name' => 'telephone_current',
            'type' => 'text_field',
            'display_name_en' => "Child's telephone / other contact details")
]

FormSection.create_or_update!(
  :unique_id => 'basic_identity',
  :parent_form => 'case',
  'visible' => true,
  :order_form_group => 30,
  :order => 10,
  :order_subform => 0,
  :form_group_id => 'identification_registration',
  'editable' => true,
  :fields => basic_identity_fields,
  :is_first_tab => true,
  'name_en' => "Child's Details",
  'description_en' => 'Basic identity information about a separated or unaccompanied child.',
  :mobile_form => true,
  :header_message_link => 'workflow_status'
)
