# Automatically generated script to migrate locations from v1.7 to v2.0+

Location.destroy_all

locations = [
  Location.new(placename_i18n: { "en": "Guatemala" }, location_code:"GT", admin_level: 0, type: "country", hierarchy_path: 'GT'),
  Location.new(placename_i18n: { "en": "Zacapa" }, location_code:"GT19", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT19'),
  Location.new(placename_i18n: { "en": "Totonicapán" }, location_code:"GT08", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT08'),
  Location.new(placename_i18n: { "en": "Suchitepéquez" }, location_code:"GT10", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT10'),
  Location.new(placename_i18n: { "en": "Sololá" }, location_code:"GT07", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT07'),
  Location.new(placename_i18n: { "en": "Santa Rosa" }, location_code:"GT06", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT06'),
  Location.new(placename_i18n: { "en": "San Marcos" }, location_code:"GT12", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT12'),
  Location.new(placename_i18n: { "en": "Sacatepéquez" }, location_code:"GT03", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT03'),
  Location.new(placename_i18n: { "en": "Retalhuleu" }, location_code:"GT11", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT11'),
  Location.new(placename_i18n: { "en": "Quiché" }, location_code:"GT14", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT14'),
  Location.new(placename_i18n: { "en": "Quetzaltenango" }, location_code:"GT09", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT09'),
  Location.new(placename_i18n: { "en": "Petén" }, location_code:"GT17", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT17'),
  Location.new(placename_i18n: { "en": "Jutiapa" }, location_code:"GT22", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT22'),
  Location.new(placename_i18n: { "en": "Jalapa" }, location_code:"GT21", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT21'),
  Location.new(placename_i18n: { "en": "Izabal" }, location_code:"GT18", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT18'),
  Location.new(placename_i18n: { "en": "Huehuetenango" }, location_code:"GT13", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT13'),
  Location.new(placename_i18n: { "en": "Guatemala" }, location_code:"GT01", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT01'),
  Location.new(placename_i18n: { "en": "Escuintla" }, location_code:"GT05", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT05'),
  Location.new(placename_i18n: { "en": "El Progreso" }, location_code:"GT02", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT02'),
  Location.new(placename_i18n: { "en": "Chiquimula" }, location_code:"GT20", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT20'),
  Location.new(placename_i18n: { "en": "Chimaltenango" }, location_code:"GT04", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT04'),
  Location.new(placename_i18n: { "en": "Baja Verapaz" }, location_code:"GT15", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT15'),
  Location.new(placename_i18n: { "en": "Alta Verapaz" }, location_code:"GT16", admin_level: 1, type: "departamento_84510", hierarchy_path: 'GT.GT16'),
  Location.new(placename_i18n: { "en": "Chahal" }, location_code:"GT1614", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1614'),
  Location.new(placename_i18n: { "en": "Cahabón" }, location_code:"GT1612", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1612'),
  Location.new(placename_i18n: { "en": "Tucurú" }, location_code:"GT1606", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1606'),
  Location.new(placename_i18n: { "en": "Tamahú" }, location_code:"GT1605", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1605'),
  Location.new(placename_i18n: { "en": "Tactic" }, location_code:"GT1604", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1604'),
  Location.new(placename_i18n: { "en": "Senahú" }, location_code:"GT1608", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1608'),
  Location.new(placename_i18n: { "en": "Santa Cruz Verapaz" }, location_code:"GT1602", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1602'),
  Location.new(placename_i18n: { "en": "Santa Catalina La Tinta" }, location_code:"GT1616", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1616'),
  Location.new(placename_i18n: { "en": "San Pedro Carchá" }, location_code:"GT1609", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1609'),
  Location.new(placename_i18n: { "en": "San Juan Chamelco" }, location_code:"GT1610", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1610'),
  Location.new(placename_i18n: { "en": "San Cristóbal Verapaz" }, location_code:"GT1603", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1603'),
  Location.new(placename_i18n: { "en": "Raxruhá" }, location_code:"GT1617", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1617'),
  Location.new(placename_i18n: { "en": "Panzós" }, location_code:"GT1607", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1607'),
  Location.new(placename_i18n: { "en": "Lanquín" }, location_code:"GT1611", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1611'),
  Location.new(placename_i18n: { "en": "Fray Bartolomé de Las Casas" }, location_code:"GT1615", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1615'),
  Location.new(placename_i18n: { "en": "Cobán" }, location_code:"GT1601", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1601'),
  Location.new(placename_i18n: { "en": "Chisec" }, location_code:"GT1613", admin_level: 2, type: "province", hierarchy_path: 'GT.GT16.GT1613'),
  Location.new(placename_i18n: { "en": "Zaragoza" }, location_code:"GT0415", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0415'),
  Location.new(placename_i18n: { "en": "Yepocapa" }, location_code:"GT0412", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0412'),
  Location.new(placename_i18n: { "en": "Tecpán Guatemala" }, location_code:"GT0406", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0406'),
  Location.new(placename_i18n: { "en": "Santa Cruz Balanyá" }, location_code:"GT0410", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0410'),
  Location.new(placename_i18n: { "en": "Santa Apolonia" }, location_code:"GT0405", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0405'),
  Location.new(placename_i18n: { "en": "San Martín Jilotepeque" }, location_code:"GT0403", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0403'),
  Location.new(placename_i18n: { "en": "San José Poaquil" }, location_code:"GT0402", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0402'),
  Location.new(placename_i18n: { "en": "San Andrés Itzapa" }, location_code:"GT0413", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0413'),
  Location.new(placename_i18n: { "en": "Pochuta" }, location_code:"GT0408", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0408'),
  Location.new(placename_i18n: { "en": "Patzún" }, location_code:"GT0407", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0407'),
  Location.new(placename_i18n: { "en": "Patzicía" }, location_code:"GT0409", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0409'),
  Location.new(placename_i18n: { "en": "Parramos" }, location_code:"GT0414", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0414'),
  Location.new(placename_i18n: { "en": "El Tejar" }, location_code:"GT0416", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0416'),
  Location.new(placename_i18n: { "en": "Comalapa" }, location_code:"GT0404", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0404'),
  Location.new(placename_i18n: { "en": "Chimaltenango" }, location_code:"GT0401", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0401'),
  Location.new(placename_i18n: { "en": "Acatenango" }, location_code:"GT0411", admin_level: 2, type: "province", hierarchy_path: 'GT.GT04.GT0411'),
  Location.new(placename_i18n: { "en": "San Miguel Chicaj" }, location_code:"GT1502", admin_level: 2, type: "province", hierarchy_path: 'GT.GT15.GT1502'),
  Location.new(placename_i18n: { "en": "San Jerónimo" }, location_code:"GT1507", admin_level: 2, type: "province", hierarchy_path: 'GT.GT15.GT1507'),
  Location.new(placename_i18n: { "en": "Salamá" }, location_code:"GT1501", admin_level: 2, type: "province", hierarchy_path: 'GT.GT15.GT1501'),
  Location.new(placename_i18n: { "en": "Rabinal" }, location_code:"GT1503", admin_level: 2, type: "province", hierarchy_path: 'GT.GT15.GT1503'),
  Location.new(placename_i18n: { "en": "Purulhá" }, location_code:"GT1508", admin_level: 2, type: "province", hierarchy_path: 'GT.GT15.GT1508'),
  Location.new(placename_i18n: { "en": "Granados" }, location_code:"GT1505", admin_level: 2, type: "province", hierarchy_path: 'GT.GT15.GT1505'),
  Location.new(placename_i18n: { "en": "El Chol" }, location_code:"GT1506", admin_level: 2, type: "province", hierarchy_path: 'GT.GT15.GT1506'),
  Location.new(placename_i18n: { "en": "Cubulco" }, location_code:"GT1504", admin_level: 2, type: "province", hierarchy_path: 'GT.GT15.GT1504'),
  Location.new(placename_i18n: { "en": "La Reforma" }, location_code:"GT1221", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1221'),
  Location.new(placename_i18n: { "en": "La Blanca" }, location_code:"GT1230", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1230'),
  Location.new(placename_i18n: { "en": "Ixchiguán" }, location_code:"GT1223", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1223'),
  Location.new(placename_i18n: { "en": "Esquipulas Palo Gordo" }, location_code:"GT1227", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1227'),
  Location.new(placename_i18n: { "en": "El Tumbador" }, location_code:"GT1213", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1213'),
  Location.new(placename_i18n: { "en": "El Rodeo" }, location_code:"GT1214", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1214'),
  Location.new(placename_i18n: { "en": "El Quetzal" }, location_code:"GT1220", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1220'),
  Location.new(placename_i18n: { "en": "Concepción Tutuapa" }, location_code:"GT1206", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1206'),
  Location.new(placename_i18n: { "en": "Comitancillo" }, location_code:"GT1204", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1204'),
  Location.new(placename_i18n: { "en": "Catarina" }, location_code:"GT1216", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1216'),
  Location.new(placename_i18n: { "en": "Ayutla" }, location_code:"GT1217", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1217'),
  Location.new(placename_i18n: { "en": "Sumpango" }, location_code:"GT0304", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0304'),
  Location.new(placename_i18n: { "en": "Santo Domingo Xenacoj" }, location_code:"GT0305", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0305'),
  Location.new(placename_i18n: { "en": "Santiago Sacatepéquez" }, location_code:"GT0306", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0306'),
  Location.new(placename_i18n: { "en": "Santa María de Jesús" }, location_code:"GT0311", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0311'),
  Location.new(placename_i18n: { "en": "Santa Lucía Milpas Altas" }, location_code:"GT0309", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0309'),
  Location.new(placename_i18n: { "en": "Santa Catarina Barahona" }, location_code:"GT0316", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0316'),
  Location.new(placename_i18n: { "en": "San Miguel Dueñas" }, location_code:"GT0313", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0313'),
  Location.new(placename_i18n: { "en": "San Lucas Sacatepéquez" }, location_code:"GT0308", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0308'),
  Location.new(placename_i18n: { "en": "San Bartolomé Milpas Altas" }, location_code:"GT0307", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0307'),
  Location.new(placename_i18n: { "en": "San Antonio Aguas Calientes" }, location_code:"GT0315", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0315'),
  Location.new(placename_i18n: { "en": "Pastores" }, location_code:"GT0303", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0303'),
  Location.new(placename_i18n: { "en": "Magdalena Milpas Altas" }, location_code:"GT0310", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0310'),
  Location.new(placename_i18n: { "en": "Jocotenango" }, location_code:"GT0302", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0302'),
  Location.new(placename_i18n: { "en": "Ciudad Vieja" }, location_code:"GT0312", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0312'),
  Location.new(placename_i18n: { "en": "Antigua Guatemala" }, location_code:"GT0301", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0301'),
  Location.new(placename_i18n: { "en": "Alotenango" }, location_code:"GT0314", admin_level: 2, type: "province", hierarchy_path: 'GT.GT03.GT0314'),
  Location.new(placename_i18n: { "en": "Santa Cruz Muluá" }, location_code:"GT1103", admin_level: 2, type: "province", hierarchy_path: 'GT.GT11.GT1103'),
  Location.new(placename_i18n: { "en": "San Sebastián" }, location_code:"GT1102", admin_level: 2, type: "province", hierarchy_path: 'GT.GT11.GT1102'),
  Location.new(placename_i18n: { "en": "San Martín Zapotitlán" }, location_code:"GT1104", admin_level: 2, type: "province", hierarchy_path: 'GT.GT11.GT1104'),
  Location.new(placename_i18n: { "en": "San Felipe" }, location_code:"GT1105", admin_level: 2, type: "province", hierarchy_path: 'GT.GT11.GT1105'),
  Location.new(placename_i18n: { "en": "San Andrés Villa Seca" }, location_code:"GT1106", admin_level: 2, type: "province", hierarchy_path: 'GT.GT11.GT1106'),
  Location.new(placename_i18n: { "en": "Retalhuleu" }, location_code:"GT1101", admin_level: 2, type: "province", hierarchy_path: 'GT.GT11.GT1101'),
  Location.new(placename_i18n: { "en": "Nuevo San Carlos" }, location_code:"GT1108", admin_level: 2, type: "province", hierarchy_path: 'GT.GT11.GT1108'),
  Location.new(placename_i18n: { "en": "El Asintal" }, location_code:"GT1109", admin_level: 2, type: "province", hierarchy_path: 'GT.GT11.GT1109'),
  Location.new(placename_i18n: { "en": "Champerico" }, location_code:"GT1107", admin_level: 2, type: "province", hierarchy_path: 'GT.GT11.GT1107'),
  Location.new(placename_i18n: { "en": "Zacualpa" }, location_code:"GT1404", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1404'),
  Location.new(placename_i18n: { "en": "Uspantán" }, location_code:"GT1415", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1415'),
  Location.new(placename_i18n: { "en": "Santa Cruz del Quiché" }, location_code:"GT1401", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1401'),
  Location.new(placename_i18n: { "en": "San Pedro Jocopilas" }, location_code:"GT1409", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1409'),
  Location.new(placename_i18n: { "en": "San Juan Cotzal" }, location_code:"GT1411", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1411'),
  Location.new(placename_i18n: { "en": "San Bartolomé Jocotenango" }, location_code:"GT1417", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1417'),
  Location.new(placename_i18n: { "en": "San Antonio Ilotenango" }, location_code:"GT1408", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1408'),
  Location.new(placename_i18n: { "en": "San Andrés Sajcabajá" }, location_code:"GT1414", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1414'),
  Location.new(placename_i18n: { "en": "Sacapulas" }, location_code:"GT1416", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1416'),
  Location.new(placename_i18n: { "en": "Patzité" }, location_code:"GT1407", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1407'),
  Location.new(placename_i18n: { "en": "Pachalum" }, location_code:"GT1421", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1421'),
  Location.new(placename_i18n: { "en": "Nebaj" }, location_code:"GT1413", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1413'),
  Location.new(placename_i18n: { "en": "Joyabaj" }, location_code:"GT1412", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1412'),
  Location.new(placename_i18n: { "en": "Ixcán" }, location_code:"GT1420", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1420'),
  Location.new(placename_i18n: { "en": "Cunén" }, location_code:"GT1410", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1410'),
  Location.new(placename_i18n: { "en": "Chinique" }, location_code:"GT1403", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1403'),
  Location.new(placename_i18n: { "en": "Chichicastenango" }, location_code:"GT1406", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1406'),
  Location.new(placename_i18n: { "en": "Chiché" }, location_code:"GT1402", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1402'),
  Location.new(placename_i18n: { "en": "Chicamán" }, location_code:"GT1419", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1419'),
  Location.new(placename_i18n: { "en": "Chajul" }, location_code:"GT1405", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1405'),
  Location.new(placename_i18n: { "en": "Canillá" }, location_code:"GT1418", admin_level: 2, type: "province", hierarchy_path: 'GT.GT14.GT1418'),
  Location.new(placename_i18n: { "en": "Zunil" }, location_code:"GT0916", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0916'),
  Location.new(placename_i18n: { "en": "Sibilia" }, location_code:"GT0905", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0905'),
  Location.new(placename_i18n: { "en": "San Miguel Sigüila" }, location_code:"GT0908", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0908'),
  Location.new(placename_i18n: { "en": "San Mateo" }, location_code:"GT0910", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0910'),
  Location.new(placename_i18n: { "en": "San Martín Sacatepéquez" }, location_code:"GT0912", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0912'),
  Location.new(placename_i18n: { "en": "San Francisco La Unión" }, location_code:"GT0918", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0918'),
  Location.new(placename_i18n: { "en": "San Carlos Sija" }, location_code:"GT0904", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0904'),
  Location.new(placename_i18n: { "en": "Salcajá" }, location_code:"GT0902", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0902'),
  Location.new(placename_i18n: { "en": "Quetzaltenango" }, location_code:"GT0901", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0901'),
  Location.new(placename_i18n: { "en": "Palestina de Los Altos" }, location_code:"GT0924", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0924'),
  Location.new(placename_i18n: { "en": "Ostuncalco" }, location_code:"GT0909", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0909'),
  Location.new(placename_i18n: { "en": "Olintepeque" }, location_code:"GT0903", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0903'),
  Location.new(placename_i18n: { "en": "La Esperanza" }, location_code:"GT0923", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0923'),
  Location.new(placename_i18n: { "en": "Huitán" }, location_code:"GT0915", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0915'),
  Location.new(placename_i18n: { "en": "Génova" }, location_code:"GT0921", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0921'),
  Location.new(placename_i18n: { "en": "Flores Costa Cuca" }, location_code:"GT0922", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0922'),
  Location.new(placename_i18n: { "en": "El Palmar" }, location_code:"GT0919", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0919'),
  Location.new(placename_i18n: { "en": "Concepción Chiquirichapa" }, location_code:"GT0911", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0911'),
  Location.new(placename_i18n: { "en": "Colomba" }, location_code:"GT0917", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0917'),
  Location.new(placename_i18n: { "en": "Coatepeque" }, location_code:"GT0920", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0920'),
  Location.new(placename_i18n: { "en": "Cantel" }, location_code:"GT0914", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0914'),
  Location.new(placename_i18n: { "en": "Cajolá" }, location_code:"GT0907", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0907'),
  Location.new(placename_i18n: { "en": "Cabricán" }, location_code:"GT0906", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0906'),
  Location.new(placename_i18n: { "en": "Almolonga" }, location_code:"GT0913", admin_level: 2, type: "province", hierarchy_path: 'GT.GT09.GT0913'),
  Location.new(placename_i18n: { "en": "Sayaxché" }, location_code:"GT1710", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1710'),
  Location.new(placename_i18n: { "en": "Santa Ana" }, location_code:"GT1707", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1707'),
  Location.new(placename_i18n: { "en": "San Luis" }, location_code:"GT1709", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1709'),
  Location.new(placename_i18n: { "en": "San José" }, location_code:"GT1702", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1702'),
  Location.new(placename_i18n: { "en": "San Francisco" }, location_code:"GT1706", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1706'),
  Location.new(placename_i18n: { "en": "San Benito" }, location_code:"GT1703", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1703'),
  Location.new(placename_i18n: { "en": "San Andrés" }, location_code:"GT1704", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1704'),
  Location.new(placename_i18n: { "en": "Poptún" }, location_code:"GT1712", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1712'),
  Location.new(placename_i18n: { "en": "Melchor de Mencos" }, location_code:"GT1711", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1711'),
  Location.new(placename_i18n: { "en": "Las Cruces" }, location_code:"GT1713", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1713'),
  Location.new(placename_i18n: { "en": "La Libertad" }, location_code:"GT1705", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1705'),
  Location.new(placename_i18n: { "en": "Flores" }, location_code:"GT1701", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1701'),
  Location.new(placename_i18n: { "en": "El Chal" }, location_code:"GT1714", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1714'),
  Location.new(placename_i18n: { "en": "Dolores" }, location_code:"GT1708", admin_level: 2, type: "province", hierarchy_path: 'GT.GT17.GT1708'),
  Location.new(placename_i18n: { "en": "Zapotitlán" }, location_code:"GT2210", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2210'),
  Location.new(placename_i18n: { "en": "Yupiltepeque" }, location_code:"GT2206", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2206'),
  Location.new(placename_i18n: { "en": "Santa Catarina Mita" }, location_code:"GT2203", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2203'),
  Location.new(placename_i18n: { "en": "San José Acatempa" }, location_code:"GT2216", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2216'),
  Location.new(placename_i18n: { "en": "Quesada" }, location_code:"GT2217", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2217'),
  Location.new(placename_i18n: { "en": "Pasaco" }, location_code:"GT2215", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2215'),
  Location.new(placename_i18n: { "en": "Moyuta" }, location_code:"GT2214", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2214'),
  Location.new(placename_i18n: { "en": "Jutiapa" }, location_code:"GT2201", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2201'),
  Location.new(placename_i18n: { "en": "Jerez" }, location_code:"GT2208", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2208'),
  Location.new(placename_i18n: { "en": "Jalpatagua" }, location_code:"GT2212", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2212'),
  Location.new(placename_i18n: { "en": "El Progreso" }, location_code:"GT2202", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2202'),
  Location.new(placename_i18n: { "en": "El Adelanto" }, location_code:"GT2209", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2209'),
  Location.new(placename_i18n: { "en": "Conguaco" }, location_code:"GT2213", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2213'),
  Location.new(placename_i18n: { "en": "Comapa" }, location_code:"GT2211", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2211'),
  Location.new(placename_i18n: { "en": "Atescatempa" }, location_code:"GT2207", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2207'),
  Location.new(placename_i18n: { "en": "Asunción Mita" }, location_code:"GT2205", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2205'),
  Location.new(placename_i18n: { "en": "Agua Blanca" }, location_code:"GT2204", admin_level: 2, type: "province", hierarchy_path: 'GT.GT22.GT2204'),
  Location.new(placename_i18n: { "en": "San Pedro Pinula" }, location_code:"GT2102", admin_level: 2, type: "province", hierarchy_path: 'GT.GT21.GT2102'),
  Location.new(placename_i18n: { "en": "San Manuel Chaparrón" }, location_code:"GT2104", admin_level: 2, type: "province", hierarchy_path: 'GT.GT21.GT2104'),
  Location.new(placename_i18n: { "en": "San Luis Jilotepeque" }, location_code:"GT2103", admin_level: 2, type: "province", hierarchy_path: 'GT.GT21.GT2103'),
  Location.new(placename_i18n: { "en": "San Carlos Alzatate" }, location_code:"GT2105", admin_level: 2, type: "province", hierarchy_path: 'GT.GT21.GT2105'),
  Location.new(placename_i18n: { "en": "Monjas" }, location_code:"GT2106", admin_level: 2, type: "province", hierarchy_path: 'GT.GT21.GT2106'),
  Location.new(placename_i18n: { "en": "Mataquescuintla" }, location_code:"GT2107", admin_level: 2, type: "province", hierarchy_path: 'GT.GT21.GT2107'),
  Location.new(placename_i18n: { "en": "Jalapa" }, location_code:"GT2101", admin_level: 2, type: "province", hierarchy_path: 'GT.GT21.GT2101'),
  Location.new(placename_i18n: { "en": "Puerto Barrios" }, location_code:"GT1801", admin_level: 2, type: "province", hierarchy_path: 'GT.GT18.GT1801'),
  Location.new(placename_i18n: { "en": "Morales" }, location_code:"GT1804", admin_level: 2, type: "province", hierarchy_path: 'GT.GT18.GT1804'),
  Location.new(placename_i18n: { "en": "Los Amates" }, location_code:"GT1805", admin_level: 2, type: "province", hierarchy_path: 'GT.GT18.GT1805'),
  Location.new(placename_i18n: { "en": "Lívingston" }, location_code:"GT1802", admin_level: 2, type: "province", hierarchy_path: 'GT.GT18.GT1802'),
  Location.new(placename_i18n: { "en": "El Estor" }, location_code:"GT1803", admin_level: 2, type: "province", hierarchy_path: 'GT.GT18.GT1803'),
  Location.new(placename_i18n: { "en": "Unión Cantinil" }, location_code:"GT1332", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1332'),
  Location.new(placename_i18n: { "en": "Todos Santos Cuchumatán" }, location_code:"GT1315", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1315'),
  Location.new(placename_i18n: { "en": "Tectitán" }, location_code:"GT1321", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1321'),
  Location.new(placename_i18n: { "en": "Soloma" }, location_code:"GT1308", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1308'),
  Location.new(placename_i18n: { "en": "Santiago Chimaltenango" }, location_code:"GT1330", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1330'),
  Location.new(placename_i18n: { "en": "Santa Eulalia" }, location_code:"GT1317", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1317'),
  Location.new(placename_i18n: { "en": "Santa Bárbara" }, location_code:"GT1310", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1310'),
  Location.new(placename_i18n: { "en": "Santa Ana Huista" }, location_code:"GT1331", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1331'),
  Location.new(placename_i18n: { "en": "San Sebastián Huehuetenango" }, location_code:"GT1320", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1320'),
  Location.new(placename_i18n: { "en": "San Sebastián Coatán" }, location_code:"GT1325", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1325'),
  Location.new(placename_i18n: { "en": "San Rafael Petzal" }, location_code:"GT1328", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1328'),
  Location.new(placename_i18n: { "en": "San Rafael La Independencia" }, location_code:"GT1314", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1314'),
  Location.new(placename_i18n: { "en": "San Pedro Necta" }, location_code:"GT1306", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1306'),
  Location.new(placename_i18n: { "en": "San Miguel Acatán" }, location_code:"GT1313", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1313'),
  Location.new(placename_i18n: { "en": "San Mateo Ixtatán" }, location_code:"GT1318", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1318'),
  Location.new(placename_i18n: { "en": "San Juan Ixcoy" }, location_code:"GT1323", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1323'),
  Location.new(placename_i18n: { "en": "San Juan Atitán" }, location_code:"GT1316", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1316'),
  Location.new(placename_i18n: { "en": "San Gaspar Ixchil" }, location_code:"GT1329", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1329'),
  Location.new(placename_i18n: { "en": "San Antonio Huista" }, location_code:"GT1324", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1324'),
  Location.new(placename_i18n: { "en": "Petatán" }, location_code:"GT1333", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1333'),
  Location.new(placename_i18n: { "en": "Nentón" }, location_code:"GT1305", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1305'),
  Location.new(placename_i18n: { "en": "Malacatancito" }, location_code:"GT1303", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1303'),
  Location.new(placename_i18n: { "en": "La Libertad" }, location_code:"GT1311", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1311'),
  Location.new(placename_i18n: { "en": "La Democracia" }, location_code:"GT1312", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1312'),
  Location.new(placename_i18n: { "en": "Jacaltenango" }, location_code:"GT1307", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1307'),
  Location.new(placename_i18n: { "en": "Ixtahuacán" }, location_code:"GT1309", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1309'),
  Location.new(placename_i18n: { "en": "Huehuetenango" }, location_code:"GT1301", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1301'),
  Location.new(placename_i18n: { "en": "Cuilco" }, location_code:"GT1304", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1304'),
  Location.new(placename_i18n: { "en": "Concepción Huista" }, location_code:"GT1322", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1322'),
  Location.new(placename_i18n: { "en": "Colotenango" }, location_code:"GT1319", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1319'),
  Location.new(placename_i18n: { "en": "Chiantla" }, location_code:"GT1302", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1302'),
  Location.new(placename_i18n: { "en": "Barillas" }, location_code:"GT1326", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1326'),
  Location.new(placename_i18n: { "en": "Aguacatán" }, location_code:"GT1327", admin_level: 2, type: "province", hierarchy_path: 'GT.GT13.GT1327'),
  Location.new(placename_i18n: { "en": "Villa Nueva" }, location_code:"GT0115", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0115'),
  Location.new(placename_i18n: { "en": "Villa Canales" }, location_code:"GT0116", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0116'),
  Location.new(placename_i18n: { "en": "Santa Catarina Pinula" }, location_code:"GT0102", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0102'),
  Location.new(placename_i18n: { "en": "San Raimundo" }, location_code:"GT0111", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0111'),
  Location.new(placename_i18n: { "en": "San Pedro Sacatepéquez" }, location_code:"GT0109", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0109'),
  Location.new(placename_i18n: { "en": "San Pedro Ayampuc" }, location_code:"GT0107", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0107'),
  Location.new(placename_i18n: { "en": "San Juan Sacatepéquez" }, location_code:"GT0110", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0110'),
  Location.new(placename_i18n: { "en": "San José Pinula" }, location_code:"GT0103", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0103'),
  Location.new(placename_i18n: { "en": "San José del Golfo" }, location_code:"GT0104", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0104'),
  Location.new(placename_i18n: { "en": "Petapa" }, location_code:"GT0117", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0117'),
  Location.new(placename_i18n: { "en": "Palencia" }, location_code:"GT0105", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0105'),
  Location.new(placename_i18n: { "en": "Mixco" }, location_code:"GT0108", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0108'),
  Location.new(placename_i18n: { "en": "Lago De Amatitlan" }, location_code:"GT0100", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0100'),
  Location.new(placename_i18n: { "en": "Guatemala" }, location_code:"GT0101", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0101'),
  Location.new(placename_i18n: { "en": "Fraijanes" }, location_code:"GT0113", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0113'),
  Location.new(placename_i18n: { "en": "Chuarrancho" }, location_code:"GT0112", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0112'),
  Location.new(placename_i18n: { "en": "Chinautla" }, location_code:"GT0106", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0106'),
  Location.new(placename_i18n: { "en": "Amatitlán" }, location_code:"GT0114", admin_level: 2, type: "province", hierarchy_path: 'GT.GT01.GT0114'),
  Location.new(placename_i18n: { "en": "Tiquisate" }, location_code:"GT0506", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0506'),
  Location.new(placename_i18n: { "en": "Siquinalá" }, location_code:"GT0504", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0504'),
  Location.new(placename_i18n: { "en": "Sipacate" }, location_code:"GT0514", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0514'),
  Location.new(placename_i18n: { "en": "Santa Lucía Cotzumalguapa" }, location_code:"GT0502", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0502'),
  Location.new(placename_i18n: { "en": "San Vicente Pacaya" }, location_code:"GT0512", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0512'),
  Location.new(placename_i18n: { "en": "San José" }, location_code:"GT0509", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0509'),
  Location.new(placename_i18n: { "en": "Palín" }, location_code:"GT0511", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0511'),
  Location.new(placename_i18n: { "en": "Nueva Concepción" }, location_code:"GT0513", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0513'),
  Location.new(placename_i18n: { "en": "Masagua" }, location_code:"GT0505", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0505'),
  Location.new(placename_i18n: { "en": "Zacapa" }, location_code:"GT1901", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1901'),
  Location.new(placename_i18n: { "en": "Usumatlán" }, location_code:"GT1906", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1906'),
  Location.new(placename_i18n: { "en": "Teculután" }, location_code:"GT1905", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1905'),
  Location.new(placename_i18n: { "en": "San Jorge" }, location_code:"GT1911", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1911'),
  Location.new(placename_i18n: { "en": "San Diego" }, location_code:"GT1908", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1908'),
  Location.new(placename_i18n: { "en": "Río Hondo" }, location_code:"GT1903", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1903'),
  Location.new(placename_i18n: { "en": "La Unión" }, location_code:"GT1909", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1909'),
  Location.new(placename_i18n: { "en": "Huité" }, location_code:"GT1910", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1910'),
  Location.new(placename_i18n: { "en": "Gualán" }, location_code:"GT1904", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1904'),
  Location.new(placename_i18n: { "en": "Estanzuela" }, location_code:"GT1902", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1902'),
  Location.new(placename_i18n: { "en": "Cabañas" }, location_code:"GT1907", admin_level: 2, type: "province", hierarchy_path: 'GT.GT19.GT1907'),
  Location.new(placename_i18n: { "en": "Totonicapán" }, location_code:"GT0801", admin_level: 2, type: "province", hierarchy_path: 'GT.GT08.GT0801'),
  Location.new(placename_i18n: { "en": "Santa María Chiquimula" }, location_code:"GT0806", admin_level: 2, type: "province", hierarchy_path: 'GT.GT08.GT0806'),
  Location.new(placename_i18n: { "en": "Santa Lucía La Reforma" }, location_code:"GT0807", admin_level: 2, type: "province", hierarchy_path: 'GT.GT08.GT0807'),
  Location.new(placename_i18n: { "en": "San Francisco El Alto" }, location_code:"GT0803", admin_level: 2, type: "province", hierarchy_path: 'GT.GT08.GT0803'),
  Location.new(placename_i18n: { "en": "San Cristóbal Totonicapán" }, location_code:"GT0802", admin_level: 2, type: "province", hierarchy_path: 'GT.GT08.GT0802'),
  Location.new(placename_i18n: { "en": "San Bartolo" }, location_code:"GT0808", admin_level: 2, type: "province", hierarchy_path: 'GT.GT08.GT0808'),
  Location.new(placename_i18n: { "en": "San Andrés Xecul" }, location_code:"GT0804", admin_level: 2, type: "province", hierarchy_path: 'GT.GT08.GT0804'),
  Location.new(placename_i18n: { "en": "Momostenango" }, location_code:"GT0805", admin_level: 2, type: "province", hierarchy_path: 'GT.GT08.GT0805'),
  Location.new(placename_i18n: { "en": "Zunilito" }, location_code:"GT1018", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1018'),
  Location.new(placename_i18n: { "en": "Santo Tomás La Unión" }, location_code:"GT1017", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1017'),
  Location.new(placename_i18n: { "en": "Santo Domingo Suchitepéquez" }, location_code:"GT1006", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1006'),
  Location.new(placename_i18n: { "en": "Santa Bárbara" }, location_code:"GT1015", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1015'),
  Location.new(placename_i18n: { "en": "San Pablo Jocopilas" }, location_code:"GT1009", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1009'),
  Location.new(placename_i18n: { "en": "San Miguel Panán" }, location_code:"GT1011", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1011'),
  Location.new(placename_i18n: { "en": "San Lorenzo" }, location_code:"GT1007", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1007'),
  Location.new(placename_i18n: { "en": "San Juan Bautista" }, location_code:"GT1016", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1016'),
  Location.new(placename_i18n: { "en": "San José La Máquina" }, location_code:"GT1021", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1021'),
  Location.new(placename_i18n: { "en": "San José El Ídolo" }, location_code:"GT1005", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1005'),
  Location.new(placename_i18n: { "en": "San Gabriel" }, location_code:"GT1012", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1012'),
  Location.new(placename_i18n: { "en": "San Francisco Zapotitlán" }, location_code:"GT1003", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1003'),
  Location.new(placename_i18n: { "en": "San Bernardino" }, location_code:"GT1004", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1004'),
  Location.new(placename_i18n: { "en": "San Antonio Suchitepéquez" }, location_code:"GT1010", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1010'),
  Location.new(placename_i18n: { "en": "Samayac" }, location_code:"GT1008", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1008'),
  Location.new(placename_i18n: { "en": "Río Bravo" }, location_code:"GT1020", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1020'),
  Location.new(placename_i18n: { "en": "Pueblo Nuevo" }, location_code:"GT1019", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1019'),
  Location.new(placename_i18n: { "en": "Patulul" }, location_code:"GT1014", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1014'),
  Location.new(placename_i18n: { "en": "Mazatenango" }, location_code:"GT1001", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1001'),
  Location.new(placename_i18n: { "en": "Cuyotenango" }, location_code:"GT1002", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1002'),
  Location.new(placename_i18n: { "en": "Malacatán" }, location_code:"GT1215", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1215'),
  Location.new(placename_i18n: { "en": "Chicacao" }, location_code:"GT1013", admin_level: 2, type: "province", hierarchy_path: 'GT.GT10.GT1013'),
  Location.new(placename_i18n: { "en": "Sololá" }, location_code:"GT0701", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0701'),
  Location.new(placename_i18n: { "en": "Santiago Atitlán" }, location_code:"GT0719", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0719'),
  Location.new(placename_i18n: { "en": "Santa María Visitación" }, location_code:"GT0703", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0703'),
  Location.new(placename_i18n: { "en": "Santa Lucía Utatlán" }, location_code:"GT0704", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0704'),
  Location.new(placename_i18n: { "en": "Santa Cruz La Laguna" }, location_code:"GT0714", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0714'),
  Location.new(placename_i18n: { "en": "Santa Clara La Laguna" }, location_code:"GT0707", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0707'),
  Location.new(placename_i18n: { "en": "Santa Catarina Palopó" }, location_code:"GT0711", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0711'),
  Location.new(placename_i18n: { "en": "Santa Catarina Ixtahuacán" }, location_code:"GT0706", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0706'),
  Location.new(placename_i18n: { "en": "San Pedro La Laguna" }, location_code:"GT0718", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0718'),
  Location.new(placename_i18n: { "en": "San Pablo La Laguna" }, location_code:"GT0715", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0715'),
  Location.new(placename_i18n: { "en": "San Marcos La Laguna" }, location_code:"GT0716", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0716'),
  Location.new(placename_i18n: { "en": "San Lucas Tolimán" }, location_code:"GT0713", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0713'),
  Location.new(placename_i18n: { "en": "San Juan La Laguna" }, location_code:"GT0717", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0717'),
  Location.new(placename_i18n: { "en": "San José Chacayá" }, location_code:"GT0702", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0702'),
  Location.new(placename_i18n: { "en": "San Antonio Palopó" }, location_code:"GT0712", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0712'),
  Location.new(placename_i18n: { "en": "San Andrés Semetabaj" }, location_code:"GT0709", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0709'),
  Location.new(placename_i18n: { "en": "Panajachel" }, location_code:"GT0710", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0710'),
  Location.new(placename_i18n: { "en": "Nahualá" }, location_code:"GT0705", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0705'),
  Location.new(placename_i18n: { "en": "Lago De Atitlan" }, location_code:"GT0700", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0700'),
  Location.new(placename_i18n: { "en": "Concepción" }, location_code:"GT0708", admin_level: 2, type: "province", hierarchy_path: 'GT.GT07.GT0708'),
  Location.new(placename_i18n: { "en": "Taxisco" }, location_code:"GT0609", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0609'),
  Location.new(placename_i18n: { "en": "Santa Rosa de Lima" }, location_code:"GT0603", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0603'),
  Location.new(placename_i18n: { "en": "Santa María Ixhuatán" }, location_code:"GT0610", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0610'),
  Location.new(placename_i18n: { "en": "Santa Cruz Naranjo" }, location_code:"GT0612", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0612'),
  Location.new(placename_i18n: { "en": "San Rafael Las Flores" }, location_code:"GT0605", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0605'),
  Location.new(placename_i18n: { "en": "San Juan Tecuaco" }, location_code:"GT0607", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0607'),
  Location.new(placename_i18n: { "en": "Pueblo Nuevo Viñas" }, location_code:"GT0613", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0613'),
  Location.new(placename_i18n: { "en": "Oratorio" }, location_code:"GT0606", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0606'),
  Location.new(placename_i18n: { "en": "Nueva Santa Rosa" }, location_code:"GT0614", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0614'),
  Location.new(placename_i18n: { "en": "Guazacapán" }, location_code:"GT0611", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0611'),
  Location.new(placename_i18n: { "en": "Cuilapa" }, location_code:"GT0601", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0601'),
  Location.new(placename_i18n: { "en": "Chiquimulilla" }, location_code:"GT0608", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0608'),
  Location.new(placename_i18n: { "en": "Casillas" }, location_code:"GT0604", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0604'),
  Location.new(placename_i18n: { "en": "Barberena" }, location_code:"GT0602", admin_level: 2, type: "province", hierarchy_path: 'GT.GT06.GT0602'),
  Location.new(placename_i18n: { "en": "Tejutla" }, location_code:"GT1210", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1210'),
  Location.new(placename_i18n: { "en": "Tajumulco" }, location_code:"GT1209", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1209'),
  Location.new(placename_i18n: { "en": "Tacaná" }, location_code:"GT1207", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1207'),
  Location.new(placename_i18n: { "en": "Sipacapa" }, location_code:"GT1226", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1226'),
  Location.new(placename_i18n: { "en": "Sibinal" }, location_code:"GT1208", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1208'),
  Location.new(placename_i18n: { "en": "San Rafael Pie de la Cuesta" }, location_code:"GT1211", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1211'),
  Location.new(placename_i18n: { "en": "San Pedro Sacatepéquez" }, location_code:"GT1202", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1202'),
  Location.new(placename_i18n: { "en": "San Pablo" }, location_code:"GT1219", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1219'),
  Location.new(placename_i18n: { "en": "San Miguel Ixtahuacán" }, location_code:"GT1205", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1205'),
  Location.new(placename_i18n: { "en": "San Marcos" }, location_code:"GT1201", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1201'),
  Location.new(placename_i18n: { "en": "San Lorenzo" }, location_code:"GT1229", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1229'),
  Location.new(placename_i18n: { "en": "San José Ojetenam" }, location_code:"GT1224", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1224'),
  Location.new(placename_i18n: { "en": "San Cristóbal Cucho" }, location_code:"GT1225", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1225'),
  Location.new(placename_i18n: { "en": "San Antonio Sacatepéquez" }, location_code:"GT1203", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1203'),
  Location.new(placename_i18n: { "en": "Río Blanco" }, location_code:"GT1228", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1228'),
  Location.new(placename_i18n: { "en": "Pajapita" }, location_code:"GT1222", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1222'),
  Location.new(placename_i18n: { "en": "Ocós" }, location_code:"GT1218", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1218'),
  Location.new(placename_i18n: { "en": "Nuevo Progreso" }, location_code:"GT1212", admin_level: 2, type: "province", hierarchy_path: 'GT.GT12.GT1212'),
  Location.new(placename_i18n: { "en": "La Gomera" }, location_code:"GT0507", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0507'),
  Location.new(placename_i18n: { "en": "La Democracia" }, location_code:"GT0503", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0503'),
  Location.new(placename_i18n: { "en": "Iztapa" }, location_code:"GT0510", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0510'),
  Location.new(placename_i18n: { "en": "Guanagazapa" }, location_code:"GT0508", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0508'),
  Location.new(placename_i18n: { "en": "Escuintla" }, location_code:"GT0501", admin_level: 2, type: "province", hierarchy_path: 'GT.GT05.GT0501'),
  Location.new(placename_i18n: { "en": "Sansare" }, location_code:"GT0207", admin_level: 2, type: "province", hierarchy_path: 'GT.GT02.GT0207'),
  Location.new(placename_i18n: { "en": "Sanarate" }, location_code:"GT0206", admin_level: 2, type: "province", hierarchy_path: 'GT.GT02.GT0206'),
  Location.new(placename_i18n: { "en": "San Cristóbal Acasaguastlán" }, location_code:"GT0204", admin_level: 2, type: "province", hierarchy_path: 'GT.GT02.GT0204'),
  Location.new(placename_i18n: { "en": "San Antonio La Paz" }, location_code:"GT0208", admin_level: 2, type: "province", hierarchy_path: 'GT.GT02.GT0208'),
  Location.new(placename_i18n: { "en": "San Agustín Acasaguastlán" }, location_code:"GT0203", admin_level: 2, type: "province", hierarchy_path: 'GT.GT02.GT0203'),
  Location.new(placename_i18n: { "en": "Morazán" }, location_code:"GT0202", admin_level: 2, type: "province", hierarchy_path: 'GT.GT02.GT0202'),
  Location.new(placename_i18n: { "en": "Guastatoya" }, location_code:"GT0201", admin_level: 2, type: "province", hierarchy_path: 'GT.GT02.GT0201'),
  Location.new(placename_i18n: { "en": "El Jícaro" }, location_code:"GT0205", admin_level: 2, type: "province", hierarchy_path: 'GT.GT02.GT0205'),
  Location.new(placename_i18n: { "en": "San Juan Ermita" }, location_code:"GT2003", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2003'),
  Location.new(placename_i18n: { "en": "San José La Arada" }, location_code:"GT2002", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2002'),
  Location.new(placename_i18n: { "en": "San Jacinto" }, location_code:"GT2010", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2010'),
  Location.new(placename_i18n: { "en": "Quezaltepeque" }, location_code:"GT2009", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2009'),
  Location.new(placename_i18n: { "en": "Olopa" }, location_code:"GT2006", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2006'),
  Location.new(placename_i18n: { "en": "Jocotán" }, location_code:"GT2004", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2004'),
  Location.new(placename_i18n: { "en": "Ipala" }, location_code:"GT2011", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2011'),
  Location.new(placename_i18n: { "en": "Esquipulas" }, location_code:"GT2007", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2007'),
  Location.new(placename_i18n: { "en": "Concepción Las Minas" }, location_code:"GT2008", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2008'),
  Location.new(placename_i18n: { "en": "Chiquimula" }, location_code:"GT2001", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2001'),
  Location.new(placename_i18n: { "en": "Camotán" }, location_code:"GT2005", admin_level: 2, type: "province", hierarchy_path: 'GT.GT20.GT2005'),
]

Location.locations_by_code = locations.map { |l| [l.location_code, l] }.to_h
locations.each(&:name_from_hierarchy)
locations.each do |loc|
  puts "Creating location #{loc.location_code}"
  loc.save!
rescue ActiveRecord::RecordNotUnique
  puts "Skipping. Location #{loc.location_code} already exists!"
rescue StandardError => e
  puts "Cannot create #{loc.location_code}. Error #{e.message}"
  raise e
end
