FormSection.create_or_update!(
  {
    name_en: "Comprehensive Assessment",
    description_en: "Comprehensive Assessment form",
    unique_id: "assessment",
    parent_form: "case",
    visible: true,
    order: 10,
    order_form_group: 50,
    order_subform: 0,
    form_group_keyed: false,
    editable: false,
    core_form: false,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    form_group_id: "assessment",
    fields_attributes: [
      {
        name: "assessment_requested_by",
        visible: false,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Assessment requested by",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assessment_requested_on",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: false,
        disabled: false,
        display_name_en: "Date of Assessment",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "case_plan_due_date",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: false,
        disabled: false,
        display_name_en: "Date Case Plan Due",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "presenting_protection_concerns_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Presenting Protection Concerns",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "protection_concerns",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Protection Concerns",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-protection-concerns",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "protection_concerns_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "primary_protection_concern",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Primary Protection Concern",
        help_text_en: "Please identify the main and urgent protection issue that  the child is experiencing (at high risk of) that the case management intervention needs to addess.",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-protection-concerns",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "risk_level",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Priority Level",
        guiding_questions_en: "Urgent (level 1)  -  Follow up within 2 4-72 hours\n\nMedium (level 2) - Follow up within 3-5 days\n\nLow (level3) - Follow up within 15 days",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-risk-level",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "safety_shelter_supervision_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Safety, Shelter, \u0026 Supervision",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangements_type",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "What are the child's current care arrangements?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-care-arrangement-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangements_type_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relationship_caregiver",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Relationship of the Caregiver to the Child",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-caregiver-relationship",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "care_arrangements_formalized",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "If the child is not with their parents, has the living arrangement/ placement been formalized?",
        help_text_en: "If no, consider formalizing placement.",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "who_supervises_child",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Who supervises the child during the day and night?",
        guiding_questions_en: "If the child does not have a caregiver or there are concerns surrounding supervision, please describe. If the child is non-verbal, please collect this information from their caregiver.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_feel_safe",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child feel safe in their current living environment?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_feels_unsafe_why",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If no, please detail why.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_action_caregiver_reaction",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "When the child does something that makes their caregiver upset, what happens?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_access_safe_appropriate_shelter",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child have access to safe and appropriate shelter?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "observations_child_shelter",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Observations about the child's shelter.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "safety_shelter_supervision_referrals",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Are any referrals/actions needed?",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-safety-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "safety_shelter_supervision_referrals_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "shelter_service_type",
        visible: false,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Type of Service",
        guiding_questions_en: "Priority 1: Medical treatment\nPriority 1: Shelter\nPriority 1: GBV specific services\nPriority 1: Food items\nPriority 1: Nutritional Screening\nPriority 2: CAFAAG specific services (reintegration support)\nPriority 2: Family tracing\nPriority 2: Child protection issues (Case management)\nPriority 2: Mediation (Family conflicts)\nPriority 2: Provision of/support to care arrangement\nPriority 2: Specialized services for child with disability\nPriority 2: Psychosocial support/Counselling/Mental health evaluation\nPriority 3: Formal education\nPriority 3: Cash transfers\nPriority 3: Life skills/Non-formal education\nPriority 3: Livelihood services\nPriority 3: Skills/vocational training",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "health_nutrition_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Health \u0026 Nutrition",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "immediate_long_term_health_concerns",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Describe and list any immediate medical needs or long-term health concerns.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_treatment_concerns",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Has the child received treatment for the above concerns?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "child_no_treatment_concerns_reason",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If no, why?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "physical_developmental_impairments",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "From observation and conversation with relevant adults, are there any physical, or developmental impairments in the child’s functionality?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "severe_issues_food_security",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Are there severe and/or  life threatening issues related to food security?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "observations_child_food_security",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Observations about the child's food security.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "food_nurition_referrals",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Are any referrals/actions needed?",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-health-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "food_nurition_referrals_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "food_service_type",
        visible: false,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Type of Service",
        guiding_questions_en: "Priority 1: Medical treatment\nPriority 1: Shelter\nPriority 1: GBV specific services\nPriority 1: Food items\nPriority 1: Nutritional Screening\nPriority 2: CAFAAG specific services (reintegration support)\nPriority 2: Family tracing\nPriority 2: Child protection issues (Case management)\nPriority 2: Mediation (Family conflicts)\nPriority 2: Provision of/support to care arrangement\nPriority 2: Specialized services for child with disability\nPriority 2: Psychosocial support/Counselling/Mental health evaluation\nPriority 3: Formal education\nPriority 3: Cash transfers\nPriority 3: Life skills/Non-formal education\nPriority 3: Livelihood services\nPriority 3: Skills/vocational training",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "emotional_psychosocial_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Emotional \u0026 Physchosocial Wellbeing",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "emotional_psychosocial_pss",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Is the child engaged in PSS activities?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "emotional_psychosocial_two_worries",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Two things that worry the child the most.",
        help_text_en: "Follow up with open-ended probing statements/questions.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "emotional_psychosocial_adult_support",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "How does the child deal with their worries? Who does the child go to for help or when they have a problem?",
        help_text_en: "Are there any adults in the community that the child trusts and has a close relationship with?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "emotional_psychosocial_all_worries",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Based on your observation: does the child have any particular worries?",
        help_text_en: "Does the child feel safe?   Does the child appear frightened/ withdrawn? Is the child crying/ unhappy? Is the child's behaviour angry or aggressive?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "emotional_psychosocial_referrals",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Are any referrals/actions needed?",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-emotional-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "emotional_psychosocial_referrals_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "emotional_psychosocial_service_type",
        visible: false,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Type of Service",
        guiding_questions_en: "Priority 1: Medical treatment\nPriority 1: Shelter\nPriority 1: GBV specific services\nPriority 1: Food items\nPriority 1: Nutritional Screening\nPriority 2: CAFAAG specific services (reintegration support)\nPriority 2: Family tracing\nPriority 2: Child protection issues (Case management)\nPriority 2: Mediation (Family conflicts)\nPriority 2: Provision of/support to care arrangement\nPriority 2: Specialized services for child with disability\nPriority 2: Psychosocial support/Counselling/Mental health evaluation\nPriority 3: Formal education\nPriority 3: Cash transfers\nPriority 3: Life skills/Non-formal education\nPriority 3: Livelihood services\nPriority 3: Skills/vocational training",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Education \u0026 Social Activities",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_education_history",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Describe the child’s educational history.",
        help_text_en: "Please detail the child’s current/highest grade level, type of school (formal, non-formal, vocational, attended/attending.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_not_attending_school_explanation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If the child is not attending school, explain why.",
        guiding_questions_en: "Probing questions:\n\nHow long they have been out of school?\n\nWhat are the barriers preventing the child to attend school?\n\nWould the child like to go to school?\n\nAre the parents supportive of the child attending school?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_non_school_activities",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Apart from school, how does the child spend their time and with whom?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_child_labour",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Is the Child involved in any form of Child Labour?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_child_labour_hours",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If yes, how many hours per day",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_child_labour_description",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Observations about the child's work.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_child_labor_school_interference",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child's work interfere with school?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_referrals",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Are any referrals/actions needed?",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-education-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_referrals_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "education_social_activities_service_type",
        visible: false,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Type of Service",
        guiding_questions_en: "Priority 1: Medical treatment\nPriority 1: Shelter\nPriority 1: GBV specific services\nPriority 1: Food items\nPriority 1: Nutritional Screening\nPriority 2: CAFAAG specific services (reintegration support)\nPriority 2: Family tracing\nPriority 2: Child protection issues (Case management)\nPriority 2: Mediation (Family conflicts)\nPriority 2: Provision of/support to care arrangement\nPriority 2: Specialized services for child with disability\nPriority 2: Psychosocial support/Counselling/Mental health evaluation\nPriority 3: Formal education\nPriority 3: Cash transfers\nPriority 3: Life skills/Non-formal education\nPriority 3: Livelihood services\nPriority 3: Skills/vocational training",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "social_economic_separator",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Social  \u0026 Economic Reintegration",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "social_economic_family_facing_difficulty_reintegrating",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Is the child and/or family facing difficulty reintegrating into their community due to stigmatization and/or an actual/perceived association with an armed group?",
        guiding_questions_en: "If the child does not have a caregiver, move on to the referrals/actions question.",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "social_economic_family_reintegration_observations",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Observations about the reintegration into the community.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "social_economic_child_require_specialized_service",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "radio_button",
        editable: true,
        disabled: false,
        display_name_en: "Does the child require specialized service to support social and or economic reintegraton?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-yes-no",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "social_economic_specialized_service_observations",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Observations about the specialized service needed.",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "social_economic_referrals",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Are any referrals/actions needed?",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-social-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "social_economic_referrals_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "social_economic_service_type",
        visible: false,
        mobile_visible: false,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Type of Service",
        guiding_questions_en: "Priority 1: Medical treatment\nPriority 1: Shelter\nPriority 1: GBV specific services\nPriority 1: Food items\nPriority 1: Nutritional Screening\nPriority 2: CAFAAG specific services (reintegration support)\nPriority 2: Family tracing\nPriority 2: Child protection issues (Case management)\nPriority 2: Mediation (Family conflicts)\nPriority 2: Provision of/support to care arrangement\nPriority 2: Specialized services for child with disability\nPriority 2: Psychosocial support/Counselling/Mental health evaluation\nPriority 3: Formal education\nPriority 3: Cash transfers\nPriority 3: Life skills/Non-formal education\nPriority 3: Livelihood services\nPriority 3: Skills/vocational training",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-service-type",
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

