FormSection.create_or_update!(
  {
    name_en: "Inquirer",
    description_en: "Inquirer",
    name_fr: "Inquirer",
    description_fr: "Inquirer",
    name_ar: "Inquirer",
    description_ar: "Inquirer",
    'name_ar-LB': "Inquirer",
    'description_ar-LB': "Inquirer",
    name_es: "Inquirer",
    description_es: "Inquirer",
    unique_id: "tracing_request_inquirer",
    parent_form: "tracing_request",
    visible: true,
    order: 20,
    order_form_group: 20,
    order_subform: 0,
    form_group_keyed: false,
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: true,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    form_group_id: "inquirer",
    fields_attributes: [
      {
        name: "tracing_request_id",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Long ID",
        display_name_fr: "Long ID",
        display_name_ar: "Long ID",
        'display_name_ar-LB': "Long ID",
        display_name_es: "Long ID",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "short_id",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Inquirer ID",
        display_name_fr: "Inquirer ID",
        display_name_ar: "Inquirer ID",
        'display_name_ar-LB': "Inquirer ID",
        display_name_es: "Inquirer ID",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "inquiry_date",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of Inquiry",
        display_name_fr: "Date of Inquiry",
        display_name_ar: "Date of Inquiry",
        'display_name_ar-LB': "Date of Inquiry",
        display_name_es: "Date of Inquiry",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        selected_value: "today",
        required: false
      },
      {
        name: "status",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Inquiry Status",
        display_name_fr: "Inquiry Status",
        display_name_ar: "Inquiry Status",
        'display_name_ar-LB': "Inquiry Status",
        display_name_es: "Inquiry Status",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-inquiry-status",
        autosum_total: false,
        autosum_group: "",
        selected_value: "open",
        required: false
      },
      {
        name: "inquirer_details_section",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Inquirer Details",
        display_name_fr: "Inquirer Details",
        display_name_ar: "Inquirer Details",
        'display_name_ar-LB': "Inquirer Details",
        display_name_es: "Inquirer Details",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relation_name",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Name of inquirer",
        display_name_fr: "Name of inquirer",
        display_name_ar: "Name of inquirer",
        'display_name_ar-LB': "Name of inquirer",
        display_name_es: "Name of inquirer",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_nickname",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Nickname of inquirer",
        display_name_fr: "Nickname of inquirer",
        display_name_ar: "Nickname of inquirer",
        'display_name_ar-LB': "Nickname of inquirer",
        display_name_es: "Nickname of inquirer",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_age",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "numeric_field",
        editable: true,
        disabled: false,
        display_name_en: "Age",
        display_name_fr: "Age",
        display_name_ar: "Age",
        'display_name_ar-LB': "Age",
        display_name_es: "Age",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_date_of_birth",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of Birth",
        display_name_fr: "Date of Birth",
        display_name_ar: "Date of Birth",
        'display_name_ar-LB': "Date of Birth",
        display_name_es: "Date of Birth",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        date_validation: "not_future_date",
        matchable: true
      },
      {
        name: "relation_language",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Language",
        display_name_fr: "Language",
        display_name_ar: "Language",
        'display_name_ar-LB': "Language",
        display_name_es: "Language",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-language",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_religion",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Religion",
        display_name_fr: "Religion",
        display_name_ar: "Religion",
        'display_name_ar-LB': "Religion",
        display_name_es: "Religion",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-religion",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_ethnicity",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Ethnicity",
        display_name_fr: "Ethnicity",
        display_name_ar: "Ethnicity",
        'display_name_ar-LB': "Ethnicity",
        display_name_es: "Ethnicity",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-ethnicity",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_sub_ethnicity1",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Sub Ethnicity 1",
        display_name_fr: "Sub Ethnicity 1",
        display_name_ar: "Sub Ethnicity 1",
        'display_name_ar-LB': "Sub Ethnicity 1",
        display_name_es: "Sub Ethnicity 1",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-ethnicity",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_sub_ethnicity2",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Sub Ethnicity 2",
        display_name_fr: "Sub Ethnicity 2",
        display_name_ar: "Sub Ethnicity 2",
        'display_name_ar-LB': "Sub Ethnicity 2",
        display_name_es: "Sub Ethnicity 2",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-ethnicity",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_nationality",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Nationality",
        display_name_fr: "Nationality",
        display_name_ar: "Nationality",
        'display_name_ar-LB': "Nationality",
        display_name_es: "Nationality",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "lookup lookup-nationality",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_comments",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Additional details / comments",
        display_name_fr: "Additional details / comments",
        display_name_ar: "Additional details / comments",
        'display_name_ar-LB': "Additional details / comments",
        display_name_es: "Additional details / comments",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "contact_information_section",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Contact Information",
        display_name_fr: "Contact Information",
        display_name_ar: "Contact Information",
        'display_name_ar-LB': "Contact Information",
        display_name_es: "Contact Information",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relation_address_current",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Current Address",
        display_name_fr: "Current Address",
        display_name_ar: "Current Address",
        'display_name_ar-LB': "Current Address",
        display_name_es: "Current Address",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_location_current",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Current Location",
        display_name_fr: "Current Location",
        display_name_ar: "Current Location",
        'display_name_ar-LB': "Current Location",
        display_name_es: "Current Location",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "relation_address_is_permanent",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: true,
        type: "tick_box",
        editable: true,
        disabled: false,
        display_name_en: "Is this a permanent location?",
        display_name_fr: "Is this a permanent location?",
        display_name_ar: "Is this a permanent location?",
        'display_name_ar-LB': "Is this a permanent location?",
        display_name_es: "Is this a permanent location?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "relation_telephone",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Telephone",
        display_name_fr: "Telephone",
        display_name_ar: "Telephone",
        'display_name_ar-LB': "Telephone",
        display_name_es: "Telephone",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "separation_history_section",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Separation History",
        display_name_fr: "Separation History",
        display_name_ar: "Separation History",
        'display_name_ar-LB': "Separation History",
        display_name_es: "Separation History",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "date_of_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "date_field",
        editable: true,
        disabled: false,
        display_name_en: "Date of Separation",
        display_name_fr: "Date of Separation",
        display_name_ar: "Date of Separation",
        'display_name_ar-LB': "Date of Separation",
        display_name_es: "Date of Separation",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "separation_cause",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "What was the main cause of separation?",
        display_name_fr: "What was the main cause of separation?",
        display_name_ar: "What was the main cause of separation?",
        'display_name_ar-LB': "What was the main cause of separation?",
        display_name_es: "What was the main cause of separation?",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "lookup SeparationCause",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "separation_cause_other",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "If Other, please specify",
        display_name_fr: "If Other, please specify",
        display_name_ar: "If Other, please specify",
        'display_name_ar-LB': "If Other, please specify",
        display_name_es: "If Other, please specify",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "separation_evacuation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "tick_box",
        editable: true,
        disabled: false,
        display_name_en: "Did the separation occur in relation to evacuation?",
        display_name_fr: "Did the separation occur in relation to evacuation?",
        display_name_ar: "Did the separation occur in relation to evacuation?",
        'display_name_ar-LB': "Did the separation occur in relation to evacuation?",
        display_name_es: "Did the separation occur in relation to evacuation?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "separation_details",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Circumstances of Separation (please provide details)",
        display_name_fr: "Circumstances of Separation (please provide details)",
        display_name_ar: "Circumstances of Separation (please provide details)",
        'display_name_ar-LB': "Circumstances of Separation (please provide details)",
        display_name_es: "Circumstances of Separation (please provide details)",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "address_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Separation Address (Place)",
        display_name_fr: "Separation Address (Place)",
        display_name_ar: "Separation Address (Place)",
        'display_name_ar-LB': "Separation Address (Place)",
        display_name_es: "Separation Address (Place)",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "location_separation",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Separation Location",
        display_name_fr: "Separation Location",
        display_name_ar: "Separation Location",
        'display_name_ar-LB': "Separation Location",
        display_name_es: "Separation Location",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "address_last",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Last Address",
        display_name_fr: "Last Address",
        display_name_ar: "Last Address",
        'display_name_ar-LB': "Last Address",
        display_name_es: "Last Address",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "landmark_last",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Last Landmark",
        display_name_fr: "Last Landmark",
        display_name_ar: "Last Landmark",
        'display_name_ar-LB': "Last Landmark",
        display_name_es: "Last Landmark",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "location_last",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Last Location",
        display_name_fr: "Last Location",
        display_name_ar: "Last Location",
        'display_name_ar-LB': "Last Location",
        display_name_es: "Last Location",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Location",
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "telephone_last",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Last Telephone",
        display_name_fr: "Last Telephone",
        display_name_ar: "Last Telephone",
        'display_name_ar-LB': "Last Telephone",
        display_name_es: "Last Telephone",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "additional_tracing_info",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "textarea",
        editable: true,
        disabled: false,
        display_name_en: "Additional info that could help in tracing?",
        display_name_fr: "Additional info that could help in tracing?",
        display_name_ar: "Additional info that could help in tracing?",
        'display_name_ar-LB': "Additional info that could help in tracing?",
        display_name_es: "Additional info that could help in tracing?",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false,
        matchable: true
      },
      {
        name: "disclosure_other_orgs",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "tick_box",
        editable: false,
        disabled: true,
        display_name_en: "Does the inquirer agree to share collected information with other organizations?",
        tick_box_label_en: "Yes",
        display_name_fr: "Does the inquirer agree to share collected information with other organizations?",
        tick_box_label_fr: "Yes",
        display_name_ar: "Does the inquirer agree to share collected information with other organizations?",
        tick_box_label_ar: "Yes",
        'display_name_ar-LB': "Does the inquirer agree to share collected information with other organizations?",
        'tick_box_label_ar-LB': "Yes",
        display_name_es: "Does the inquirer agree to share collected information with other organizations?",
        tick_box_label_es: "Yes",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

