FormSection.create_or_update!(
  {
    name_en: "Record Owner",
    description_en: "Record Owner",
    name_fr: "Record Owner",
    description_fr: "Record Owner",
    name_ar: "Record Owner",
    description_ar: "Record Owner",
    'name_ar-LB': "Record Owner",
    'description_ar-LB': "Record Owner",
    name_es: "Record Owner",
    description_es: "Record Owner",
    unique_id: "tracing_request_record_owner",
    parent_form: "tracing_request",
    visible: true,
    order: 0,
    order_form_group: 0,
    order_subform: 0,
    form_group_keyed: false,
    editable: true,
    core_form: true,
    is_nested: false,
    is_first_tab: false,
    initial_subforms: 0,
    subform_prevent_item_removal: false,
    display_help_text_view: false,
    is_summary_section: false,
    hide_subform_placeholder: false,
    mobile_form: true,
    header_message_link: "",
    form_group_id: "record_owner",
    fields_attributes: [
      {
        name: "current_owner_section",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Current Owner",
        display_name_fr: "Current Owner",
        display_name_ar: "Current Owner",
        'display_name_ar-LB': "Current Owner",
        display_name_es: "Current Owner",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "caseworker_name",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Field/Case/Social Worker",
        display_name_fr: "Field/Case/Social Worker",
        display_name_ar: "Field/Case/Social Worker",
        'display_name_ar-LB': "Field/Case/Social Worker",
        display_name_es: "Field/Case/Social Worker",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "owned_by",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: false,
        disabled: true,
        display_name_en: "Caseworker Code",
        display_name_fr: "Caseworker Code",
        display_name_ar: "Caseworker Code",
        'display_name_ar-LB': "Caseworker Code",
        display_name_es: "Caseworker Code",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "User",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "owned_by_agency",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: false,
        disabled: true,
        display_name_en: "Agency",
        display_name_fr: "Agency",
        display_name_ar: "Agency",
        'display_name_ar-LB': "Agency",
        display_name_es: "Agency",
        multi_select: false,
        hidden_text_field: false,
        option_strings_source: "Agency",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "assigned_user_names",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "select_box",
        editable: true,
        disabled: false,
        display_name_en: "Other Assigned Users",
        display_name_fr: "Other Assigned Users",
        display_name_ar: "Other Assigned Users",
        'display_name_ar-LB': "Other Assigned Users",
        display_name_es: "Other Assigned Users",
        multi_select: true,
        hidden_text_field: false,
        option_strings_source: "User",
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "record_history_section",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "separator",
        editable: true,
        disabled: false,
        display_name_en: "Record History",
        display_name_fr: "Record History",
        display_name_ar: "Record History",
        'display_name_ar-LB': "Record History",
        display_name_es: "Record History",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "created_by",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Record created by",
        display_name_fr: "Record created by",
        display_name_ar: "Record created by",
        'display_name_ar-LB': "Record created by",
        display_name_es: "Record created by",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "created_organization",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Created by agency",
        display_name_fr: "Created by agency",
        display_name_ar: "Created by agency",
        'display_name_ar-LB': "Created by agency",
        display_name_es: "Created by agency",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "previously_owned_by",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Previous Owner",
        display_name_fr: "Previous Owner",
        display_name_ar: "Previous Owner",
        'display_name_ar-LB': "Previous Owner",
        display_name_es: "Previous Owner",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "previous_agency",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: true,
        disabled: false,
        display_name_en: "Previous Agency",
        display_name_fr: "Previous Agency",
        display_name_ar: "Previous Agency",
        'display_name_ar-LB': "Previous Agency",
        display_name_es: "Previous Agency",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      },
      {
        name: "module_id",
        visible: true,
        mobile_visible: true,
        hide_on_view_page: false,
        show_on_minify_form: false,
        type: "text_field",
        editable: false,
        disabled: true,
        display_name_en: "Module",
        display_name_fr: "Module",
        display_name_ar: "Module",
        'display_name_ar-LB': "Module",
        display_name_es: "Module",
        multi_select: false,
        hidden_text_field: false,
        autosum_total: false,
        autosum_group: "",
        required: false
      }
    ]
  }
)

